### ISSUE TITLE
Subsurface scattering non compatible with point ?

### ISSUE THREAD

**Issue by tubiana** [BradyAJohnston/MolecularNodes#10]
Hi Brady!

Sorry, another bug in sight XD

I wanted to add some subsurface scattering in the shader and when I activate it and set even a very small value, all atoms becomes very dark, like in the screenshot. I put a Suzanne mesh with subsurface scattering to check if it was not my config. 
First screenshot is on GPU render
![image](https://user-images.githubusercontent.com/8037224/166067862-58e94360-5397-40fd-a8c8-ebfb6d483489.png)
And Strangly, it seems to be a bit better with CPU (but not perfect)
![image](https://user-images.githubusercontent.com/8037224/166067827-7947e272-7c3b-4af9-bac0-6c144ed564f0.png)

But I'm wondering here if the issue doesn't come from Blender itself.... Here's the blend file if you need it for some testing ^^

Cheers!
Thibault.

**Comment by BradyAJohnston** [comment]
Yes I have come across this when playing around with it previously. I think it has to do with the point-cloud rendering not supporting it properly. You could try using the Atoms EEVEE node if you wanted some
Subsurf. Will likely affect viewport performance though.
