### ISSUE TITLE
Error when following the COVID spike video tutorial. Cannot import the trajectory: "Formal charge 1 not recognized"

### ISSUE THREAD

**Issue by famrein** [BradyAJohnston/MolecularNodes#100]
Im following the procedure exactly as per the tutorial. Used last_frame_nos.pdb as topology and trj_nos.xtc as trajectory. Im on Windows 11, blender 3.3.1, python 3.10, MDAnalysis 2.3.0. 

![image](https://user-images.githubusercontent.com/22937598/206049987-e3da57e1-ea96-4aa2-a3d7-cdb82cc07e0b.png)

![image](https://user-images.githubusercontent.com/22937598/206049036-2c7606c1-a50a-4530-860b-2734ffe90838.png)

**Comment by BradyAJohnston** [comment]
Try it with downgrading MDAnalysis to `2.2.0` which should fix the issue. 

```
pip install MDAnalysis==2.2.0
```

The development version of MN should also not have this issue hopefully.

**Comment by famrein** [comment]
Perfect! Thanks!
