### ISSUE TITLE
Unable to enable version 2.0 

### ISSUE THREAD

**Issue by Mangkun-Chen** [BradyAJohnston/MolecularNodes#101]
![image](https://user-images.githubusercontent.com/108992267/206950811-6a7c468f-7b9a-4a21-952a-663cede087fe.png)
The error is shown in the figure

**Comment by Mangkun-Chen** [comment]
![image](https://user-images.githubusercontent.com/108992267/206951434-c39452b5-65bf-4c44-b284-f1980bb8946c.png)

**Comment by BradyAJohnston** [comment]
Ah, thanks for the report. Will look into this ASAP!

**Comment by BradyAJohnston** [comment]
Try `2.0.1` this should now be fixed: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.0.1

**Comment by Mangkun-Chen** [comment]
Thank you！ It works now！
