### ISSUE TITLE
Unable to install Atomium on mac BigSur M1

### ISSUE THREAD

**Issue by xiao-guangv** [BradyAJohnston/MolecularNodes#102]
Hi, I have an issue with installing Atomium, blender is version 3.2.2. and Molecular nodes is 0.12.2 (I think this is the latest for Blender 3.2.X).
I tried a few times but always failed.
Also I tried to open Blender using terminal, as you've mentioned in previous issues, so I'll paste the picture of what terminal said.
I would be happy to get some hints on how to solve this problem...
<img width="687" alt="スクリーンショット 2022-12-12 12 03 00" src="https://user-images.githubusercontent.com/65448090/206951816-118faa3a-8877-4310-886e-e8a95bea9b88.png">

**Comment by BradyAJohnston** [comment]
Seems like the building of some packages is falling. Did you ensure you downloaded the M1 version of Blender?

**Comment by xiao-guangv** [comment]
Thanks for replying me!
Yes, I thought arm64 is for M1 version, so I downloaded it.
<img width="607" alt="スクリーンショット 2022-12-12 13 20 20" src="https://user-images.githubusercontent.com/65448090/206960068-919c4ce3-abbc-46b1-9aa9-7c2b89158210.png">

Again, I tried another version of Blender 3.3.2 and Molecular nodes 0.13.0, it also failed.

**Comment by xiao-guangv** [comment]
I'm just trying to repeat the version with someone who has successfully installed Atomium, and there is no other reason than that to use earlier version. Should I try with Blender 3.4 latest?
I'll paste what terminal said with Blender 3.3.2 and Molecular nodes 0.13.0 below just in case.

`
Looking in links: /var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/tmphqkscae2
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (63.2.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (22.2.2)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (22.2.2)
Collecting pip
  Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Successfully installed pip-22.3.1
Collecting atomium
  Using cached atomium-1.0.11-py3-none-any.whl (48 kB)
Requirement already satisfied: numpy in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (from atomium) (1.22.0)
Collecting rmsd
  Using cached rmsd-1.4-py3-none-any.whl (16 kB)
Collecting msgpack
  Using cached msgpack-1.0.4-cp310-cp310-macosx_11_0_arm64.whl (69 kB)
Collecting paramiko
  Using cached paramiko-2.12.0-py2.py3-none-any.whl (213 kB)
Collecting valerius
  Using cached valerius-0.2.0-py3-none-any.whl (4.6 kB)
Requirement already satisfied: requests in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (from atomium) (2.27.1)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pynacl>=1.0.1
  Using cached PyNaCl-1.5.0-cp36-abi3-macosx_10_10_universal2.whl (349 kB)
Collecting cryptography>=2.5
  Using cached cryptography-38.0.4-cp36-abi3-macosx_10_10_universal2.whl (5.4 MB)
Collecting bcrypt>=3.1.3
  Using cached bcrypt-4.0.1-cp36-abi3-macosx_10_10_universal2.whl (473 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (from requests->atomium) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (from requests->atomium) (2021.10.8)
Requirement already satisfied: charset_normalizer~=2.0.0 in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (from requests->atomium) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (from requests->atomium) (3.3)
Collecting scipy
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      The Meson build system
      Version: 0.64.1
      Source dir: /private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e
      Build dir: /private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e/.mesonpy-9kr7_fam/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C linker for the host machine: cc ld64 650.9
      C++ compiler for the host machine: c++ (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C++ linker for the host machine: c++ ld64 650.9
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../../meson.build:57:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e/.mesonpy-9kr7_fam/build/meson-logs/meson-log.txt
      + meson setup --prefix=/Applications/Blender.app/Contents/Resources/3.3/python /private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e /private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e/.mesonpy-9kr7_fam/build --native-file=/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      Traceback (most recent call last):
        File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-build-env-8t_9rkbn/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 1060, in build_wheel
          with _project(config_settings) as project:
        File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-build-env-8t_9rkbn/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-build-env-8t_9rkbn/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
        File "/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-build-env-8t_9rkbn/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-build-env-8t_9rkbn/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-build-env-8t_9rkbn/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 657, in _meson
          return self._proc('meson', *args)
        File "/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-build-env-8t_9rkbn/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=/Applications/Blender.app/Contents/Resources/3.3/python', '/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e', '/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e/.mesonpy-9kr7_fam/build', '--native-file=/private/var/folders/01/vb17qtm14gj_293j4jtyxqh80000gn/T/pip-install-pdp64m02/scipy_97ab9acb960b44f8b10e065f82194c6e/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Atomium installation failed.
`

**Comment by BradyAJohnston** [comment]
Looks like it's an issue with compiling `scipy`.

```
ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
```

This line indicates that it's unable to find a compiler to compile `scipy`. You'll need to install `gcc`, which on a mac can be done a variety of ways. 

Running this in the terminal may help: 

```
xcode-select --install
```

Otherwise installing `gcc` via homebrew: 
 - 1. [Install Homebrew](https://docs.brew.sh/Installation):
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)
```
 - 2. Install `gcc` via homebrew:
```
brew install gcc
```

Then restart your computer and try the installation of atomium again.
