### ISSUE TITLE
V2.0.1 Unable to import pdb file

### ISSUE THREAD

**Issue by Mangkun-Chen** [BradyAJohnston/MolecularNodes#106]
![image](https://user-images.githubusercontent.com/108992267/207233786-cbb8dc59-4075-4de6-bbb3-820e778d7a4d.png)
The error is shown in the figure. My English is not very good.

**Comment by BradyAJohnston** [comment]
Sorry about that. See if this fixes the issue: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.0.2

**Comment by Mangkun-Chen** [comment]
I still have an error message here

![image](https://user-images.githubusercontent.com/108992267/207242544-b9d6af01-deaf-4528-9042-101314bd1bfe.png)

**Comment by BradyAJohnston** [comment]
I can't reproduce the issue. Can you uninstall Moelcular Nodes, restart Blender, then reinstall 2.0.2 and see if that helps?

**Comment by Mangkun-Chen** [comment]
I follow your method: uninstall (not overwrite) first, then restart blender, then reinstall 2.0.2. Now it works
Thank you!!
