### ISSUE TITLE
Installation of Molecular Nodes 2.0.2 with Blender 3.4.0 on M1 Max Mac Ventura 13.0

### ISSUE THREAD

**Issue by gha2012** [BradyAJohnston/MolecularNodes#111]
Hi, 
I tried to install Molecular Nodes 2.0.2 with Blender 3.4.0 on M1 Max Mac Ventura 13.0. After installing the .zip file, there is a button "install packages" in the Molecular Nodes panel. When I click it, I see a beachball and after a while it says "Failed to install required packages. Please check log file: ..." 
That log file just contains this:
-----------------------------------
Installer Started: 2022-12-17 15:55:53.117289
-----------------------------------
###################################
Installer finished: 2022-12-17 15:56:24.477652
###################################

Any idea what might be the problem?

Thanks,
Gregor

**Comment by PlethoraChutney** [comment]
See if the solution here helps you, it fixed the same issue for me!

https://github.com/BradyAJohnston/MolecularNodes/issues/108#issuecomment-1355965223

In short:

1. Install miniconda
2. `conda create -n molnodes python==3.10 biotite==0.35.0 mdanalysis==2.2.0 -c conda-forge -y`
3. `mv /Applications/Blender.app/Contents/Resources/3.4/python /Applications/Blender.app/Contents/Resources/3.4/old_python`
4. `ln -s /path/to/miniconda/python /Applications/Blender.app/Contents/Resources/3.4/python`

And it should work!

**Comment by gha2012** [comment]
Great! That works! Thank you!

**Comment by BradyAJohnston** [comment]
Thanks for the bug report mate! Glad it's now working. Definitely seems to be an ARM mac issue. Will need to make sure the log file is a bit more useful ha.

**Comment by gha2012** [comment]
FYI: Before the fix, I started Blender from the terminal and clicked on the "install packages" button. There I could see that the installation of numpy failed. Below is an excerpt. Maybe that helps to fix it.

```
            SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by BradyAJohnston** [comment]
tracked in other issues
