### ISSUE TITLE
import trajectories on LINUX

### ISSUE THREAD

**Issue by mamarambio1** [BradyAJohnston/MolecularNodes#116]
Hi Brady!

I am trying to get started in the world of molecular nodes.
At the moment of installing the corresponding packages, I have not been able to load a path in Blender.
and I get the following error:

![Captura de Pantalla 2022-12-19 a la(s) 10 55 19](https://user-images.githubusercontent.com/84489348/208443821-953af263-934d-4a7c-a29f-9fe608da799b.png)

I have used both the 2.0 update and the 0.13 version of molecular nodes.
I am using linux and blender 3.4
I hope you can help me to solve it,

Thank you very much! 

Best regards

**Comment by BradyAJohnston** [comment]
It's unclear what the error might be from this screenshot. A guess could be conflicting versions of MN. 
 
 Can you try uninstalling both versions of Molecular Nodes, restarting Blender, then reinstalling just MN 2.0.2? Ensure that you try to install it before you do anything else inside of a fresh Blender scene.

**Comment by mamarambio1** [comment]
Hi Brady!

I just did what you indicated and also what you did in error #112 and I was able to load the trajectory using MN version 2.0 on Linux.

thank you very much!

Best regards!

**Comment by BradyAJohnston** [comment]
Just to be clear it was the ` sys.path.append("/usr/lib/python3/dist-packages")` that fixed the problem for you? Or a combination of restarting and appending the path? 

I don't currently have access to a linux machine so just wanting to find out what the fix is

**Comment by mamarambio1** [comment]
It was the combination of reinstalling and adding the path, as I had previously tried adding it without reinstalling and it had not worked.

**Comment by BradyAJohnston** [comment]
Thanks for the info!
