### ISSUE TITLE
MOL_atomic properties not a library

### ISSUE THREAD

**Issue by Furman-Lab** [BradyAJohnston/MolecularNodes#12]
Hi!

I installed MolecularNodes, both the add-on and the atomium installation was said to be fine. However, when I tried to load a pdb file (even from pdb or file), I get the following error:
![image](https://user-images.githubusercontent.com/93254645/166319046-1b154aea-19e9-4096-97f7-f0c3b25af71c.png)
Blender version: 2.93.4, add-on version: 0.4.0

What could the the issue?

**Comment by BradyAJohnston** [comment]
Ah apologies, I incorrectly packed the blend file. Can you re-download the 0.4 release and try again? 

Also I don't know how it's going to go on earlier versions of blender. I recommend updating to at least 3.0 or 3.1.2

**Comment by gezmi** [comment]
Hi,

I tried again the 0.4 release and reinstalled it, but I get the same result. The weird thing is that it searches something in your path...

**Comment by BradyAJohnston** [comment]
What version of blender are you on? And what operating system? 

At what point does the error occur?

**Comment by RodenLuo** [comment]
Hi Brady, Thanks for the amazing work first. 

I meet the exact same issue. But the molecules can be loaded. The error is also shown even if it is a successful loading.

I'm on Windows 10, Blender 3.1.2. After clicking `Open -> import_protein_local`, it happened.

**Comment by RodenLuo** [comment]
Oh, sorry. I confirm, in my case, the newest 0.4 release (in this commit: 207f7683e0e2958a72364dc455d171fe0ad0e499) solved the issue.

**Comment by BradyAJohnston** [comment]
Ah thanks @RodenLuo, I should have really updated the numbering on the release but it was just a very quick-fix so I skipped it which has lead to some confusion with people downloading it before I uploaded the fix. 

Glad it's working now!

**Comment by BradyAJohnston** [comment]
@gezmi I am unable to replicate this error on any other computers that I test on. Can you maybe try reinstalling Blender, and reinstalling molecular nodes again? That's the only possible solution I can think of.

**Comment by gezmi** [comment]
I tried with "original" PDB files, mine were modified, now it loads okay. It gave the same error once later, but on the 2nd click it ran... Thank you for the help!
