### ISSUE TITLE
Support .MOL / .sdf files

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#120]
Biotite can read other more chemically-oriented file types. Need to add specific support for it inside of MN. Will require some tweaking as they won't contain the same types of attributes that protein-oriented file types encode.

**Comment by TheJeran** [comment]
What needs to be done for .mol integration? I came here to post for this use case.
I could write a simple python program to organize the data from a mol file into whatever you use for MN.

**Comment by BradyAJohnston** [comment]
Thanks for being interested!

The ideal would an [`AtomArray`](https://www.biotite-python.org/apidoc/biotite.structure.AtomArray.html#biotite.structure.AtomArray) from biotite. You can potentially use biotite to parse it, or parse if with your own scripts and then create a `AtomArray` manually.

Even if not that, any kind of numpy array or easily ordered values are what I am after, so they can be added as attributes to the create 3D model. Happy to answer more questions on this also.

**Comment by BradyAJohnston** [comment]
Turns out biotite does support it: https://www.biotite-python.org/apidoc/biotite.structure.io.mol.html?highlight=mol

I don't however have any real experience dealing with these kind of files, nor do I have good examples for testing, so if you'd like to have a go it would be great!

**Comment by TheJeran** [comment]
Well I finally sat down and looked into this and got mol working. It was incredibly easy. I added a pull request if you want to add it
