### ISSUE TITLE
Addons preferences not showing

### ISSUE THREAD

**Issue by FilouPlains** [BradyAJohnston/MolecularNodes#122]
**Please note:** It's my first bug report, sorry if I do something bad!

# Configuration

- **Blender:** `3.0.1`
- **OS:** `Ubuntu 22.04.1 LTS`
- **MolecularNodes:** `MolecularNodes_2.0.2.zip`

# The actual bug
## Error thrown

```python
Error: Python: Traceback (most recent call last):
  File "/home/rouaud/.config/blender/3.0/scripts/addons/MolecularNodes/ui.py", line 41, in invoke
    return self.execute(context)
  File "/home/rouaud/.config/blender/3.0/scripts/addons/MolecularNodes/ui.py", line 27, in execute
    mol_object = load.molecule_rcsb(
  File "/home/rouaud/.config/blender/3.0/scripts/addons/MolecularNodes/load.py", line 27, in molecule_rcsb
    nodes.create_starting_node_tree(
  File "/home/rouaud/.config/blender/3.0/scripts/addons/MolecularNodes/nodes.py", line 124, in create_starting_node_tree
    node_chain_id = node_group.nodes.new("GeometryNodeInputNamedAttribute")
RuntimeError: Error: Node type GeometryNodeInputNamedAttribute undefined


location: <unknown location>:-1
```

## Why is this done

For some reasons, I do not have access to the preferences for the installed addons:

![image](https://user-images.githubusercontent.com/96999425/209029730-69e0b5c9-5330-4736-af2e-04481d0ca833.png)

As you can see on the above screenshot, this is the only things that I could access after installed this addons. I cannot, for instance, link blender to `MDAnalysis`. After, I can still use some functionality like downloading PDB files, but an error is thrown (*see above*), and I can't do much about it. Also, the PDB/molecules is only in “line” style.

What should I do about it?

Sincerely, 

\- Lucas

**Comment by BradyAJohnston** [comment]
Hi mate! Looks like is a MN / Blender version mismatch. 

You are currently running Blender 3.0.1, which is too early of a version to run MolecularNodes. If you want to use the latest MolecualrNodes (v2.0.2) then you'll need to upgrade to Blender 3.4.X.

**Comment by FilouPlains** [comment]
Hi, it was this ! I thought that snap install latest version, look like I were wrong… Thank you for your quick answer, and for this crazy cool addons!
