### ISSUE TITLE
Importing MD traj with topology != GRO VDW radii are missing 

### ISSUE THREAD

**Issue by DrDomenicoMarson** [BradyAJohnston/MolecularNodes#124]
**Describe the bug**
I just tried the last 2.0.2 version of this amazing tool, I'm particularly interested in the possibility to load MD simulations inside Blender.
When importing XTC MD trajectories selecting a topology file that is not a .gro file (which could be useful, as other formats have also bond information stored) the VDW radii information is not read properly.

**Possible solution**
I played around with the code in `md.py`, and I may have found the source of the issue. 

The element-assigment follows different code paths if the selected topology is a GRO or TPR/PRMTOP file.  In the case of a GRO file, a mda.NoDataError exception rises, so the code in the `except` block is executed, returning a simple list.
In the other cases, elements are present and the `try` statement is successful, but in this case, `elements` will be a np.array and not a simple list.

```python
    try:
        elements = univ.atoms.elements
    except:
        elements = [mda.topology.guessers.guess_atom_element(x) for x in univ.atoms.names]
```

When then the following code is executed to retrieve the VDW radii, everything works fine if the `elements` object is a list (as in the case of a GRO topology file), otherwise, a `TypeError: string operation on non-string array` exception rises, which ultimately (I think) assign a VDW value of 0.0 to all the atoms.

```python
    def att_vdw_radii():
        vdw_radii = np.array(list(map(
            lambda x: mda.topology.tables.vdwradii.get(x, 1), 
            np.char.upper(elements)
        )))
        
        return vdw_radii * world_scale
```

In my simple test case (I just played with the code, not inside blender, as I don't know how to debug things in blender), just changing the line
 
```python
elements = univ.atoms.elements
````
to
```python
elements = univ.atoms.elements.tolist()
```

fixed the issue, and in this way, I have the correct VDW radii regardless of the input topology file format.

PS: Thank you so much for this amazing tool!!!

**Comment by BradyAJohnston** [comment]
Thanks so much for the bug report! I don't think I actually have any non `.gro` topologies to test it with, so this has been very useful. I've created a PR #125 that should fix this with the `.tolist()` that you provided. I also added a default vdw_radii of 1 should the extraction of them fail during import.
