### ISSUE TITLE
atomium installation failed

### ISSUE THREAD

**Issue by haaaaaahi** [BradyAJohnston/MolecularNodes#137]
HI Brady Johnston,My Blender is 3.2 and the downloaded nodal version is 0.12.2 I tried several times but couldn't install atoms
![微信图片_20230112152643](https://user-images.githubusercontent.com/122516550/212004245-7d4444ca-6640-4a7f-851c-83ae820b6f25.jpg
Any idea what might be wrong?
Thanks

**Comment by haaaaaahi** [comment]
![微信图片_20230112152643](https://user-images.githubusercontent.com/122516550/212004925-7777e7e4-7829-4797-a4f5-9fdb2e3a2f66.jpg)

**Comment by BradyAJohnston** [comment]
Is there a reason you are using an earlier version of Blender and Molecular Nodes? 

I would recommend upgrading to Blender 3.4.1 and Molecular Nodes 2.2.2

**Comment by haaaaaahi** [comment]
<img width="383" alt="微信图片_20230112153309" src="https://user-images.githubusercontent.com/122516550/212006068-3a2dbeaf-f7da-4553-8001-1dfd88e840cf.png">
when I use Blender  3.4.4 and and Molecular Nodes 2.2.2,cannot use the install Atomium click to install,click on check box does add this but not all options like in the video to put search to appears
<img width="305" alt="微信图片_20230112153931" src="https://user-images.githubusercontent.com/122516550/212006665-e3d5b4ec-f5b0-42c4-ba33-6a172879740e.png">
<img width="349" alt="微信图片_20230112153958" src="https://user-images.githubusercontent.com/122516550/212006677-7d4f8e6a-4f1a-4c01-8d49-998e7dd949c7.png">
I am use a windows 10
Thanks!

**Comment by BradyAJohnston** [comment]
Molecular Nodes `2.X` has been re-written, so a lot of the UI has changed slightly, along with some of the nodes etc. I haven't remade the videos yet to cover the new nodes, but pretty much all of the functionality should be there. It seems that 2.2 has installed OK, I recommend using the updated version instead. 

Is there something in particular that you are trying to do, that you can't get working in the version?

**Comment by haaaaaahi** [comment]
I appreciate your help, Brady! I'll follow your tutorials to see if I can solve my questions by myself and let's keep in touch in case I have further questions. 
Best regards

**Comment by BradyAJohnston** [comment]
I will hopefully be making some more videos with the updated nodes soon. It's been a busy summer so I haven't had much time :)
