### ISSUE TITLE
Something is wrong, I think it's the PDB

### ISSUE THREAD

**Issue by 3dato** [BradyAJohnston/MolecularNodes#14]
Hi, I have followed your instructions carefully, but there is an error, see image. Any idea what it could be?

![dato2022-05-03-10-23-32](https://user-images.githubusercontent.com/86822139/166431296-7077c260-4c38-461b-8c7c-337bba1efd74.gif)

**Comment by BradyAJohnston** [comment]
Need to make sure you export the intermediate frames from ChimeraX:

Inside of [ChimeraX](https://www.cgl.ucsf.edu/chimerax/) run these three commands:
1. `open 6n2y 6n2z 6n30`
2. `morph #1,2,3 wrap true`
3. `save atp-frames.pdb #4 allCoordsets true`

I have now added these more explicit instructions to the README also.
