### ISSUE TITLE
Multiple residue id selection like PyMOL command?

### ISSUE THREAD

**Issue by YaoYinYing** [BradyAJohnston/MolecularNodes#141]
I think the Geometry nodes are amazing for those who feel hard for learning command line or any coding stuff. It's super easy to get started with molecular visualization.

As a PyMOL advanced user, I'm familiar with some thing like `select key_res, chain A and ////resi+resi+resi+resi` or `select charged, chain A and ////ARG+LYS+ASP+GLU` for multiple residue id selection. 

In MN it should be helpful to add a menu item like `MOL_sel_res_ids` more than `MOL_sel_res_id`. I tried to working on that but the repo architecture looks confusing: in `ui.py` I found `MOL_sel_res_id` in class `MOL_MT_Add_Node_Menu_Selections` but I have no idea about how it works. That is frustrating :(

Can you give me some hints on that?

**Comment by BradyAJohnston** [comment]
The repo architecture is a bit all over the place, and still needs a bit of refactoring and cleanup to make it easier to contribute to.

Unfortunately string manipulation inside of Geometry Nodes is extremely limited, so you can't currently parse a string such as `1 + 3 + 10 + 60` or `1, 3, 10, 60` and turn that into a list of integers to then match / create a selection out of.

The only current solution, which is extremely cumbersome, is to join together multiple single integer selections as so:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/36021261/213604872-1f83c294-8739-4841-a851-84ccb51dbfc5.png">

Or create  a custom node group which combines those selections:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/36021261/213604910-5b86da23-f404-4ddf-8ba7-6560c3f07103.png">

## Moving Forward

Currently we are limited by geometry nodes and what kind of string parsing it supports (although improved string parsing is being worked on).

There is potential to have a separate button in the MN panel, through which you can create a new `boolean` attribute, that contains a more advanced selection that can be specified via text. Doing this once the molecule is already loaded would be possible but potentially a little more difficult. 

## Importing via MDAnalysis

In the development version of MN, I have added such custom selections when importing via MDAnalysis. If you have a static structure you can specific it as both the topology and trajectory and create custom selections. This uses the MDA analysis selection algebra (https://docs.mdanalysis.org/stable/documentation_pages/selections.html).

<img width="416" alt="image" src="https://user-images.githubusercontent.com/36021261/213605656-0e733567-1ec7-4a60-a3d5-25587d0abc87.png">


This is currently only available when importing the protein though.

If we are to add custom selections available once the protein is already loaded into geometry nodes, it would require taking the attribute data from the protein, loading it into python, creating the selection, then adding that selection back on to the original object. It is certainly doable if a little convoluted though.

**Comment by YaoYinYing** [comment]
How about parsing resi strings into a node group like this?
<img width="701" alt="5i9f_MN_GNs_resi_groups" src="https://user-images.githubusercontent.com/33014714/215034928-8fcfe283-6982-4b16-b260-6d5892ce49ba.png">

I believe that the iterative structure will be easier to be handled once we know the way to generate such a Node Group.

<img width="1177" alt="5i9f_MN_GNs_full" src="https://user-images.githubusercontent.com/33014714/215034821-b990a9e1-da87-42f7-8226-d8b49355f4da.png">

BTW, the `and` and `not` can also be parsed like this.

**Comment by BradyAJohnston** [comment]
There is certainly potential for programmatically generating the selection node groups. I already generate them that way for chain selection and a few others, so it wouldn't be too difficult to set that up. 

The hard part I could imagine would be creating _yet another_ selection algebra language for people to learn. I suppose I could try and copy one that already exists, such as just using the specification that pymol or chimera etc already uses. I wouldn't want to overcomplicate things with yet another way to create selections, but I can certainly appreciate the need for making more complicated selections more easily. 

If you have an idea of what the UI should be, and what the selection language should be (keeping in mind the desire to keep it relatively simple, maybe limited to just `res_id`s for the now) then we can maybe put together a new feature that includes it.
