### ISSUE TITLE
Incorrect biological assemblies

### ISSUE THREAD

**Issue by mikaelabelle** [BradyAJohnston/MolecularNodes#143]
Hi, I just started using Molecular Nodes and was following the Youtube tutorials. When I got the virus assembly video, I tried following along using the 1CD3 model, but the virus didn't assemble as it should have.

![image](https://user-images.githubusercontent.com/19698567/214234467-aac94ed6-8b89-4a0e-a008-0a02d3df5f8a.png)

I tried with another virus (6IMM), and it didn't assembly properly either, with a large portion missing.

![image](https://user-images.githubusercontent.com/19698567/214235129-75bec139-4f0e-489b-9805-a7d53282194d.png)

Any help would be appreciated! I could have a setting incorrect somewhere. This is with a fresh install of Blender 3.4.1 and Molecular Nodes 2.2.1.

**Comment by BradyAJohnston** [comment]
Thanks for the bug report! I had experience some small issues with the assembly node, but this gives a couple of good examples to test against. I've got a working solution now on the #145 branch. There are still a couple of structures that I have tested it with where it fails, so will require a little more testing to get wokring.

**Comment by BradyAJohnston** [comment]
This is now fixed in the development version with all of the structures that I have been able to test. I'm currently only supporting the first biological assembly as that is usually what people want, and I plan on overhauling how this works in the future. Will close this issue when the next release including this is made.

**Comment by mikaelabelle** [comment]
Thanks for the prompt fix! All working for me drom the dev version :D

**Comment by BradyAJohnston** [comment]
Good to hear 🥳

**Comment by BradyAJohnston** [comment]
now in the released version
