### ISSUE TITLE
not defined atom types in pdb not accepted

### ISSUE THREAD

**Issue by VeriR** [BradyAJohnston/MolecularNodes#15]
Hi Brady!
Here comes the issue report :)

I have a pdb file with not defined atom types (written as X).
The objects load fine, but the properties can not be assigned correctly. 

Fixing it manually by converting X to C works, but for whatever reason I needed to add an TER before END at the end of the pdb file (might be important to mention as well). After those modifications everything worked fine.

Thanks again for your awesome work!
Verena

**Comment by BradyAJohnston** [comment]
Thanks for the report! I think I have a pretty good idea what is causing this currently, but glad there is a workaround in the mean time!

**Comment by BradyAJohnston** [comment]
Should now be fixed in the latest release: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.4.1
