### ISSUE TITLE
[for help]  cannot “install package”

### ISSUE THREAD

**Issue by Mangkun-Chen** [BradyAJohnston/MolecularNodes#150]
![lALPJw1WWUAjP8PNAp3NAVQ_340_669](https://user-images.githubusercontent.com/108992267/216223271-9c063bd0-d134-4ac9-831a-b4597f38cfe2.png)

![lALPJw1WWUAfxnLM1c0Dhg_902_213](https://user-images.githubusercontent.com/108992267/216223208-09932268-ea09-42b4-ae07-717287f65d7e.png)

Hi Brady

My friend also wants to use your add-on. But he cannot to “install package”. Do you know any way to solve it？
Thank you

**Comment by YaoYinYing** [comment]
Well  i guess your friend is one of victim of the GFW, which eliminate `pip` from accessing PyPI. To solve this issue, please walk to the directory where the build-in `python` and `pip` binary locate, and take a try with the following: 

1. set PyPI mirror to BFSU or whatever. `./pip3.10 config set global.index-url https://mirrors.bfsu.edu.cn/pypi/web/simple`
2. Install the required pacakes: 

- `./pip3.10 install atomium`
- `./pip3.10 install biotite==0.35.0`
- `./pip3.10 install MDAnalysis==2.2.0`

3. Restart Blender.

It worth noting that if MN has pinned a higher version of any one of the required package, please change the version number  to the exactly one noted at here: https://github.com/BradyAJohnston/MolecularNodes/blob/3c45ad776ba04054e3fb5f57eaa57a9f943e4021/MolecularNodes/pkg.py#L24-L25

**Comment by HCl0906** [comment]
Thanks YaoYin, it works.

**Comment by BradyAJohnston** [comment]
Should we add something about this to the documentation?

**Comment by sarahsandler** [comment]
I am having this same issue and switching the to the other mirror hasn't worked for me.

**Comment by BradyAJohnston** [comment]
Hi @sarahsandler if you could open up a new issue with as many details as possible (error messages, screenshots etc) then we can probably help you better there :)
