### ISSUE TITLE
Updating Biotite for PDB import bugfix

### ISSUE THREAD

**Issue by heejongkim** [BradyAJohnston/MolecularNodes#153]
Hi Brady,

I just encountered a weird pdb case that was associated with biotite pdb import bug.
I reported it and the developer quickly responded to the issue to resolve.
https://github.com/biotite-dev/biotite/issues/456

Would it cause any issues with your current code if the latest version of biotite is installed?

thanks,

heejong

**Comment by BradyAJohnston** [comment]
It shouldn't affect Molecular Nodes if you manually updated Biotite. I currently force install of `0.35.0` but you can manually install the latest Biotite by using the following script either in the script editor inside of Blender or by pasting it directly into the python console inside of Blender.

```python
import subprocess
import sys
import os

python_exe = os.path.realpath(sys.executable)
subprocess.call([python_exe, "-m", "ensurepip"])
subprocess.call([python_exe, "-m", "pip", "install","--upgrade", "pip"], timeout=600)
subprocess.call([python_exe, "-m", "pip", "install", "biotite"], timeout=600)

```

**Comment by BradyAJohnston** [comment]
Let me know how it goes and if anything breaks at all.

**Comment by heejongkim** [comment]
Not sure what I'm doing wrong but, after executing the script above, still biotite.__version__ says "0.35.0".
Let me dig around a bit more.
thanks.

**Comment by BradyAJohnston** [comment]
try using 
```python
subprocess.call([python_exe, "-m", "pip", "install", "biotite==0.36.1"], timeout=600)
```
to manually specify the version (and force pip to upgrade it). I was able to get the upgraded version after then restarting Blender.

```
>>> import biotite
>>> biotite.__version__
'0.36.1'
```

**Comment by heejongkim** [comment]
Got it.
It worked!
Thank you.
Let me try if it breaks.

**Comment by heejongkim** [comment]
so far so good. nothing broken and it reads pdb files flawlessly.
I'm going to close this for now.
Thank you.

**Comment by BradyAJohnston** [comment]
Thanks for the update! I'll update biotite version that I request for install which should allow better importing
