### ISSUE TITLE
Blender crash on M1 Max after Molecular Nodes

### ISSUE THREAD

**Issue by rajatthomas** [BradyAJohnston/MolecularNodes#155]
After following the instructions for Mac M1, I tried to relaunch Blender and it fails to open. 
It has to do with the python soft link. When I delete the softlink and move the old_python back to python (reversing the instructions on the [installations page](https://bradyajohnston.github.io/MolecularNodes/installation.html), I can start Blender again. Any work arounds?

**Comment by BradyAJohnston** [comment]
thanks for the bug report! I don't have access to an M1 / M2 Mac (unfortunately) so I can't really be of much help with troubleshooting in this case. 

Are you able to give more detail for any kind of error messages that you are getting?

I did have luck with helping someone install on an M1, and it just required a complete reinstall of Blender and then re-linking of the created conda environment as a potential solution.

**Comment by BradyAJohnston** [comment]
The [update installation instructions](https://bradyajohnston.github.io/MolecularNodes/installation.html#installing-biotite-mdanalysis) now has a better method for installation, that builds the required `.whl` files locally and uses them to install.

I would recommend doing a clean install of Blender and those instructions should help fix the issue.
