### ISSUE TITLE
cannot see atomic properties Node?

### ISSUE THREAD

**Issue by pseudo-simp** [BradyAJohnston/MolecularNodes#158]
Hi Brady and everyone

this might be totally be a blender learning curve issue, but when I try to import any .pdb file I do not see an associated '6z6u_properties' in the right hand drop down MolecularNodes menu (screen shot), and I do not see any "MOL_atomic_properties" geometry node which I assume is why  i do not have full control over the color scheme.

I am using blender 3.4.1 and molecular nodes 2.3.1.zip ... I am also using a macbook laptop (MacOS catalina).

Sorry in advance if I am missing something obvious, and thank you!

<img width="273" alt="Screen Shot 2023-02-11 at 4 04 19 AM" src="https://user-images.githubusercontent.com/125121625/218249919-1bdeaffb-bf85-4438-8e39-8c124873050b.png">
<img width="1513" alt="Screen Shot 2023-02-11 at 4 06 01 AM" src="https://user-images.githubusercontent.com/125121625/218250004-20216d65-a225-4acf-a179-b5f3ebec8150.png">

**Comment by BradyAJohnston** [comment]
Hello! Apologies but I haven't updated the tutorials yet. The `MOL_atomic_properties` and `*_properties` collection are no longer required and are thus not added (I set up the properties in a far more efficient way). So everything looks like it should be working properly. 

Which part of the color scheme do you want to have control over that you don't currently have?
