### ISSUE TITLE
Node "chain" can't be executed. Error message

### ISSUE THREAD

**Issue by jgaertner** [BradyAJohnston/MolecularNodes#159]
Loading of the "chain" node doesn't work for many PDB files, while  it works in Blender 3.3, Molecular nodes Version 0.13.0.
This is happening for instance with the following pdb entries: 1gri, 1xd2

**To Reproduce**
shiftA, molecular nodes, selection, chain 1gri 

**Expected behavior**
Loading of chain node.

Python:
# "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\ui.py", line 515, in execute
    input_list = obj['chain_id_unique'], 
KeyError: 'bpy_struct[key]: key "chain_id_unique" not found'

**Desktop (please complete the following information):**
 - OS: Windows 
 - Hardware: x86 PC
 - Blender Version: 3.4, 3.5 alpha
- MolecularNodes Version: 2.2.0, 2.3.1

**Comment by BradyAJohnston** [comment]
I am not able to reproduce this bug myself, with the PDBs provided. 

I'm using windows on an x86 PC, Blender 3.4 & Molecular Nodes 2.3.1. Can you try uninstalling and reinstalling MN on Blender 3.4 to see if it fixes it?

**Comment by jgaertner** [comment]
Many thanks for the quick response, Brady. I uninstalled the 2.2.0 version it in Blender 3.4, and installed the 2.3.0 version, and now it works! Thank you again.
