### ISSUE TITLE
Transparency not working

### ISSUE THREAD

**Issue by heejongkim** [BradyAJohnston/MolecularNodes#167]
Hi Brady,

With Blender 3.4.1 and molecular nodes 2.2.1, it seems like transparency (alpha) is not working with neither ribbon nor surface.
Other properties like "metallic" in the MOL_atomic_material just works fine.
Perhaps, I need to construct a separate material for ribbon and surface with different configuration?

Thank you.
best,
heejong

**Comment by heejongkim** [comment]
Sorry. Nevermind.
I accidentally used Eevee engine instead of Cycles.
Now it works.
Thank you.

**Comment by BradyAJohnston** [comment]
ah no worries! You can use the transparency in EEVEE, you just need to adjust the shader options (https://www.youtube.com/watch?v=VSR9qdJ_dRo)

**Comment by heejongkim** [comment]
oh great! thank you.
Eevee rendering is so much faster to check if i did correctly through timeline.
This will speed up my workflow tremendously.
