### ISSUE TITLE
Unable to install MDAnalysis on Blender 3.3.2 (Mol.Nodes 0.13.0)

### ISSUE THREAD

**Issue by DJ004** [BradyAJohnston/MolecularNodes#169]
Hi Brady, 
Thanks for all your hard work on Molecular Nodes and Blender tutorials. 

I'm unable to install MDAnalysis (installed with py 3.9 / 3.10 in a conda env) into **Molecular Nodes version 0.13.0** on **Blender 3.3.2** which seems to work on python 3.10.8. I'm on a **Linux Ubuntu 22.04 64bit workstation**. Atomium installation works fine though. 

If this helps, here is the path to MDAnalysis that I specify while trying to install it into Molecular Nodes: 
`~/anaconda3/envs/py39_mdanalysis/lib/python3.9/site-packages/`
Similarly, 
`~/anaconda3/envs/py310_mdanalysis/lib/python3.10/site-packages/`
When I click 'check installation', it says MDAnalysis is unavailable. Happens when MDA is installed with python 3.9 or with 3.10 in a conda env.

I couldn't find any info on how to fix this. Hence, reporting an issue. Apologies if I'm missing something obvious! Any help is appreciated 

Thanks,
Dheeraj

**Comment by BradyAJohnston** [comment]
Hi mate! Is there a reason that you are trying to install MN `0.13` rather than a newer version? (currently at `2.4`)

**Comment by DJ004** [comment]
Hi Brady. Thanks for your response! 
The only reason I installed MN 0.13 is because I had Blender 3.3.X installed. I had installed the corresponding MN version as displayed on your MN releases GitHub page. Anyway, I have now successfully installed MN 2.4 after upgrading Blender to 3.4.1.
