### ISSUE TITLE
make atom/residue selection via distance to another selections

### ISSUE THREAD

**Issue by YaoYinYing** [BradyAJohnston/MolecularNodes#170]
Hi Brady, I'm a little confused about how to use the `MOL_sel_distance` node for selecting atoms and residues based on their distance from a selection. Specifically, I would like to:

1. Select atoms within a specified distance cutoff of a selection, and
2. Select residues in a similar way, by selecting the entire residue if any of its atoms are within the distance cutoff.

Based on my understanding, the `MOL_sel_distance` node is a pre-set template that was hardcoded in the `assets/node_append_file.blend` file. Can you please show me on how to edit this node to achieve these two tasks?

**Comment by YaoYinYing** [comment]
BTW, I am happy to post my first rendered protein image at [here](https://github.com/YaoYinYing/PPRCODE_Guideline/blob/master/README.md) with the help of MN. This is absolutely cool!

**Comment by BradyAJohnston** [comment]
The `MOL_sel_distance` currently works as the distance from an empty object. Now that you point it out, I think it should be changed to take atoms instead, and have a differently named node which can handle an empty.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/36021261/222389214-2f56c679-5109-48b6-a7cb-ccf352b465a2.png">

You can use the `Geometry Proximity` node to get the distance from the nearest atom, and combine that with `MOL_sel_atoms` to measure the distances from the a selection of atoms. You can then use a `Compare` node to create the cutoff, which will give a boolean selection. 

The `MOL_sel_res_whole` will expand that selection to the entire amino acid, if any of the atoms in the residue are selected.  The example screenshot I showed should get the result you are after, but I will package this up to a node by itself also.

**Comment by BradyAJohnston** [comment]
Also a fabulous rendering @YaoYinYing ! 

I can't believe it has taken me this long to realise, but it turns out that we both work on PPR proteins. My supervisor are Charlie Bond and Ian Small. I originally started doing Blender things to try and make some nice movies of MD simulations of PPR proteins binding their RNA targets (https://twitter.com/bradyajohnston/status/1572024257223458816). They are just the coolest proteins! (https://twitter.com/bradyajohnston/status/1602467809585422337)

![image](https://user-images.githubusercontent.com/36021261/222391654-bd49e272-395e-4408-8b5e-543ef7af5321.png)

I'm writing about that PPRCODE paper at the moment for my PhD thesis. It's a small world!

**Comment by YaoYinYing** [comment]
So unbelievable about this! 
I began the studies in designer PPR even before my master's degree during my internship at the lab of my previous supervisor, Ping Yin, who is acturally a strucural biologist and solved both crystal structures of the first naturally occuring and designer PPR.  
After finishing my the PPR-related project three yrs ago, I became a phD student and left his lab with shifting my research interests to protein design tasks. The original PPRCODE website was probably down, which pushed me to find out alternative tools for PPR researchers. The most recent version of this cover is rayed from PyMOL, but MN has changed it into a beautiful work of scientific art!
And I definitely agree that PPR is the most elegant and coolest protein in the world!

**Comment by BradyAJohnston** [comment]
Closing this as it is now handled by the `Proximity` node: https://bradyajohnston.github.io/MolecularNodes/nodes.html#proximity
