### ISSUE TITLE
MolecularNodes 2.4.3 fails to activate

### ISSUE THREAD

**Issue by pgb3** [BradyAJohnston/MolecularNodes#181]
After installing MolecularNodes 2.4.3 when trying to activate it the following error occurs:
NameError: name 'get_pypi_mirror_alias' is not defined

With MolecularNodes 2.3.0 activation also fails with the following error:
NameError: name 'TrajectorySelectionList' is not defined

MolecularNodes 2.2.2 can be successfully activated

 - OS: MacOS 11.6
 - Hardware: Intel Mac
 - Blender Version: 3.4.1
- MolecularNodes Version: 2.4.3 and 2.3.0

**Comment by YaoYinYing** [comment]
Well I guess you are trying to upgrade MN - before activate the new version of that you need a restart of blender.

**Comment by pgb3** [comment]
Thank you very much for your reply. I uninstalled version 2.2.2 and then I installed version 2.4.3. That produced the error.

What I did now that solved the problem is installing 2.4.3 without uninstalling 2.2.2. I was expecting to have both versions installed, but to my surprise 2.4.3 replaced 2.2.2

**Comment by BradyAJohnston** [comment]
It is sometimes best to restart Blender after uninstalling / reinstalling addons to ensure it works cleanly. Now that you have reinstalled it okay, I would also try restarting Blender and just making sure that nothing weird is happening.

**Comment by YaoYinYing** [comment]
Hot upgrade? That's cool.
