### ISSUE TITLE
Failed installation on MacOS

### ISSUE THREAD

**Issue by SimoneMattei** [BradyAJohnston/MolecularNodes#185]
**Describe the bug**
When trying to enable the "Molecular Nodes" (version 2.5.2) add on in MacOS (Ventura 13.2.1) of an Intel based MacBook I get an error about not being able to load the module 'pyopenvdb'

Sorry I just realised that 2.5.2 is a release for Blender 3.5.x and not 3.4.x. Please ignore this issue, the installation of Molecular Nodes 2.4.3 worked. Please, ignore this report and thank you so much for the great work!

**To Reproduce**
1. Go to 'edit'
2. Click on 'preferences'
3. Click on  'add-ons'
4. Click on 'Install'
5. Select the .zip file of MolecularNodes
6. Click on the box to enable the add-on
7. The error appears

**Expected behavior**
From you video tutorial the enabling should activate the add-on, I don't get past this step...

**Error Codes**
Please include associated error codes that are shown in the python console when the error occurs.
# paste error codes from python console here
Report: Error
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.4/scripts/modules/addon_utils.py", line 333, in enable
mod = _import_(module_name)
File "/Users/mattei/Library/Application Support/Blender/3.4/scripts/addons/MolecularNodes/__init__.py", line 30, in <module> 
from .ui import *
File "/Users/mattei/Library/Application Support/Blender/3.4/scripts/addons/MolecularNodes/ui.py", line 7, in <module>
from. import density
File "/Users/mattei/Library/Application Support/Blender/3.4/scripts/addons/MolecularNodes/density.py", line 2, in <module>
import pyopenvdb as vdb
ModuleNotFoundError: No module named 'pyopenvdb'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - Hardware: Intel Mac
 - Blender Version: 3.4.1
- MolecularNodes Version: 2.5.2

**Additional context**
![Screenshot 2023-03-29 at 17 12 59](https://user-images.githubusercontent.com/47850682/228589074-123a70af-e0cd-4785-bee0-8dc98154a8e5.png)

**Comment by BradyAJohnston** [comment]
Ah it sees you found that MN 2.5 is for Blender 3.5+ only. `pyopenvdb` only ships with that version of Blender.

**Comment by SimoneMattei** [comment]
Hi Brady, yes sorry about the confusion. Once I realised my mistake I tried to delete the report but I couldn't find a way to do so (I'm not familiar with GitHub yet, so I might have missed the obvious...). Thank you very much for developing this add-on and I look forward to testing your next endeavours!
