### ISSUE TITLE
Unable to detect biological assembly information

### ISSUE THREAD

**Issue by hiyata** [BradyAJohnston/MolecularNodes#190]
Hi Brady, 

I'm a beginner and I've been following the steps on your tutorial, but I'm running into the bug "Unable to detect biological assembly information" when I create the node. Is this a known issue? I've tried it on several capsids including the one in the tutorial and I still get this issue. Any help would be much appreciated!

**Comment by BradyAJohnston** [comment]
Ah thanks for reporting this. I've found the source of the bug and will be fixing it shortly.

**Comment by BradyAJohnston** [comment]
This should now be fixed in [2.5.4](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.5.4)
