### ISSUE TITLE
No way to distinguish waters in the structure.

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#20]
Currently there is no way to select, delete or distinguish water molecules in the structures that are imported.

Having a `is_water` property would fix this issue.

**Comment by yuxuanzhuang** [comment]
Related to it, it would be great to add a (multiple) selection input during importing so that users can ignore water and/or create different visualization for different molecular components (e.g. protein and lipids)

**Comment by PlethoraChutney** [comment]
Do you hard-code the MOL_selection_AA_name node options, or are they dynamically generated from the PDB (sorry, I'm naive wrt how blender node options can be set up)?

I just noticed that you also cannot select sugars, but selecting every AA name and sending the inverse selection works (I don't have waters in this PDB), so they are properly loaded in by atomium. I assume that the fact that you don't seem to be dynamically generating res names means you can't, though :)

**Comment by BradyAJohnston** [comment]
Currently the AA names are hardcoded. You can dynamically generate some nodes (which I do for the chain selection and a couple of other nodes), just requires a bit more setup. 

Currently I am only encoding the AA names for the peptides (1-20 for the alphabetical AA), 31-34 for the RNA bases and 41-44 for the DNA bases.

I haven't tried playing around with what information is accessible via Atomium / MDAnalysis, if the sugar information is available through those packages then it will be possible to implement into the selection options. 

Whether it's just additionally included in the `AA_name` field or something else is created instead (I am getting the feeling that I might want to do some refactoring of field names and information that is stored in each).

Certainly open to any and all suggestions! I created these initial fields & classifications while I was first putting it all together with no real input from others, so advice on what would make more sense is always welcome.

**Comment by PlethoraChutney** [comment]
It does seem that sugars and UNK are available through atomium (in both `model.ligands()` and `model.residues()`):

```
>>> print(set([x.name for x in pdeg.residues()]))
{'GLU', 'TYR', 'GLY', 'THR', 'LEU', 'CYS', 'NA', 'PHE', 'MET', 'PRO', 'ILE', 'TRP', 'LYS', 'VAL', 'SER', 'ASP', 'GLN', 'ARG', 'NAG', 'ASN', 'ALA', 'HIS', 'MAN', 'BMA'}

>>> print(set([x.name for x in pdeg.ligands()]))
{'NAG', 'BMA', 'UNK', 'MAN'}
```

Weirdly, water doesn't seem to be in there? I can't find how to get waters in the atomium documentation unfortunately.

And if I remember correctly, you can only access numbers in Fields, which is why you have to encode them using the dicts? If that's the case, I have a **very** stupid idea:

```
def str_to_field(in_string:str) -> int:
    # all uppercase letters are two digits, 65 -- 90
    int_list = [str(ord(x)) for x in in_string.upper()]
    return int(''.join(int_list))

def str_from_field(in_field:int) -> str:
    in_field = str(in_field)
    characters = []
    # certainly a faster way to do this part, but just for example
    i = 0
    while i < len(in_field):
        # convert every two digits to a character
        characters.append(chr(int(in_field[i:i+2])))
        i += 2
    return ''.join(characters)

test = 'Hello Brady!'
fielded = str_to_field(test) # fielded == 726976767932668265688933
reverse_fielded = str_from_field(fielded) # reverse_fielded == HELLO BRADY!
```

Since this method is dumb and the resulting numbers would be quite large, you could try something like:
```
def get_str(in_field:int) -> str:
    if in_field <= 100:
        return aa_names[in_field]
    else:
        return str_from_field(in_field)
```

If I misremembered the reason for the AA_name dict, feel free to view this simply as a window into my mind on the weekend :)

**Comment by BradyAJohnston** [comment]
You are right in that everything has to be numerically encoded for Blender / Geometry Nodes to understand it currently.

The size of the numbers wouldn't necessarily be a problem, it would just require dynamic creation of the selection nodes inside of Molecular Nodes, based on what was detected during the parsing of the file.

The `Atomium` docs leave a fair bit to be desired, unfortunately. It's currently undergoing a complete overhaul which improves a whole bunch of features, but also it seems like that may have stalled, with the [last commit being 7 months ago](https://github.com/samirelanduk/atomium/tree/2.0). 

What I have considered doing is including a standalone `atomium` installation inside of Molecular Nodes itself, which removes one of the installation steps (but blows out the download from ~ 1 MB to ~ 80MB).  That way we could do manual tweaks to our own fork of atomium that is designed more specifically for use inside of Molecular Nodes. 

I haven't gone down this road yet because I don't really have the time, and certainly not the python knowledge, to try and do such a task, but certainly something I'd like to attempt in the future.

**Comment by BradyAJohnston** [comment]
I will however have a play around with the sugar detection, as it should be able to work with Molecular Nodes 'asis'. Do you have a particular PDB that you have been testing it with?

**Comment by PlethoraChutney** [comment]
> it would just require dynamic creation of the selection nodes inside of Molecular Nodes

I see, so encoding the names using numbers in Blender's geometry nodes wouldn't be that helpful.

> I haven't gone down this road yet because I don't really have the time, and certainly not the python knowledge, to try and do such a task, but certainly something I'd like to attempt in the future.

That totally makes sense, you're a busy man! I'd be happy to try and take a look at the guts of `atomium` with you if you do go that route, although if anything you're operating from a greater base of python knowledge than me haha.

> Do you have a particular PDB that you have been testing it with?

Unfortunately I've been testing it with a PDB I can't release yet. But anything with sugars works --- you could try our model `6WTH`, which I've screenshotted below. Leaving all AA names selected and passing the inverted into a select atom nodes will do the trick, as well as picking up UNK (which it seems you're already aware of in line 247 of `import_structure.py`).

<img width="856" alt="image" src="https://user-images.githubusercontent.com/27385979/194994276-330b5c71-627f-4779-9f9f-082c0af39004.png">

**Comment by BradyAJohnston** [comment]
Closing this as the sugar and ligands are discussed in #79 and water is now able to be ignored on import.
