### ISSUE TITLE
Mac issue with python library pyopenvdb

### ISSUE THREAD

**Issue by lucasdavid85** [BradyAJohnston/MolecularNodes#207]
I'm working on mac computer and I tried to install the last version of MolecularNodes to get the cartoons feature and I had a problem with importation module pyopenvdb. It's maybe due to the dependancie location on mac. 
I tried to install on terminal the dependancie but it doesn't work 

**I tried to**
1. Go on linux termial and run this command : 
brew install pyopenvdb 
brew install openvdb 

**Screenshots**
<img width="659" alt="Capture d’écran 2023-04-28 à 17 57 55" src="https://user-images.githubusercontent.com/34141493/235199608-63f60be4-41d1-44a3-ba85-7ed630f1dac1.png">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Hardware: Intel Mac 2018
 - Blender Version: version 3.1.4 (12/2020)
- MolecularNodes Version:2.6.0

**Comment by BradyAJohnston** [comment]
Hi @lucasdavid85, the later versions of MolecularNodes require later versions of Blender. MolecularNodes v2.6.0 requires at least Blender 3.5.0. If you upgrade blender and try the installation again, it should resolve the issue :)

**Comment by lucasdavid85** [comment]
Than you for solving my problem. I had no verify if I was in the latest blender version. After a fight with wheel file and MDAnalysis installation on mac (it's always difficult to install dependencies on mac...), your add-on is running. 
Thank you for the big step in molecular visualization on blender, It's an amazing add-on.

**Comment by BradyAJohnston** [comment]
no worries at all, glad it is working now!
