### ISSUE TITLE
PDB without 4-character code

### ISSUE THREAD

**Issue by Alexsg14** [BradyAJohnston/MolecularNodes#21]
I'm trying to load a PDB from a MD simulation from a folder. It has no 4-character code and all the times i tried to, it failed.

Is there a way to load a "custom" pdb or only from PDBDatabank?

![image](https://user-images.githubusercontent.com/105719066/168800891-26efe58f-b842-48c9-b455-2f84ced7c20d.png)

Thank you!

**Comment by BradyAJohnston** [comment]
Yep, use the "local file" option, click the small folder icon to find the file or paste in the file path, then click the "open" button.

![](https://user-images.githubusercontent.com/36021261/165198468-84e813b5-e5e6-4cfb-b735-cc78ae45791f.png)

**Comment by Alexsg14** [comment]
It works if I use an atomistic PDB but for my Coarse Grained doesn't, at least for big membrane systems. For small peptides like LL-37 in CG worked too.

**Comment by BradyAJohnston** [comment]
Are you able to share an example file so I can debug? It's likely there a bunch of custom PDB files out there that will break the import, but I should hopefully be able to support it in a future release.

**Comment by BradyAJohnston** [comment]
I am also adding support for MD trajectories via the python package MDAnalysis in the next release, so any formats that can be parsed by that should be able to be opened as well.

**Comment by Alexsg14** [comment]
Yeah, I attached here the PDB. I have to send it to you by link because git hub does not suppport the file: [https://nubeusc-my.sharepoint.com/:u:/g/personal/alejandro_seco_rai_usc_es/EZcCuAtZLV9AoWCl4lEalYsBK8htk3hsRBnhNpnAi6U1Og?e=1wkb1a](url)

**Comment by BradyAJohnston** [comment]
I seem to be able to open that file without any problems. Is this a multi-frame file? 

I am using the development version, so it may be that I have changed something that has improved the ability to import.

Currently MolecularNodes is unable to process all of the non-standard names for atoms etc, but I have an idea of how to support this going forward better.

![image](https://user-images.githubusercontent.com/36021261/169674632-738ab8f1-668d-4d53-9291-d2566fbf8b1c.png)

**Comment by Alexsg14** [comment]
Oh! It looks awesome on your screen!

No, actually is only one frame, prior to simulation. I am using Blender 3.1.2, I don't know if that coud be a reason.

Thanks! I'll be aware to the updates of Molecular Nodes.

**Comment by BradyAJohnston** [comment]
What version of Molecular Nodes are you using? If it's < 0.4.1 try downloading the most recent release and seeing if that works for you. Blender 3.1.2 should be ideal

**Comment by Alexsg14** [comment]
I'm using 0.3.8. I'll try with the last version

**Comment by Alexsg14** [comment]
Okey! Now for the same file I sent to you and for another one it worked. Thanks!

I will do some more tests with other files and locations, but for now, perfect!

![image](https://user-images.githubusercontent.com/105719066/169690431-49aec66c-3ef7-4846-aa2b-532f5489281d.png)

**Comment by BradyAJohnston** [comment]
Excellent! Glad it's working now :) The water atoms I believe still aren't being processed properly, but at least they are being imported. I should be able to implement better handling of them in the next update or so.

**Comment by Alexsg14** [comment]
Perfect! I don't if now we can do that, but it would be awesome to be able to, for example, hide the water or select freely. (I'm totally new here, if we can do that already, forget it, further work for me)

And thanks again! :D
