### ISSUE TITLE
Problems with Cartoon Helices

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#215]
There are some minor issues with generation of cartoon helices, will be documenting them here: 

Tasklist:
- [x] Fix smoothing with high subdiv
- [x] Fix breaking in 3HET
- [x] Fix alpha-fold model cartoons
- [x] Fix 3AXT bad geometry

With lots of subdivisions, non-smooth bumps where the alpha-carbons are (32 subdivisions):

![image](https://user-images.githubusercontent.com/36021261/235359105-8d1fd5d7-dd61-4bee-a6a1-3f3be53635bb.png)

Can be fixed by changing the color ramp to a `Ping Pong` -> `Map Range` (Smooth Step) node combination.

Totally fails on 3HET (no idea why): 
![image](https://user-images.githubusercontent.com/36021261/235359493-442fc109-8df7-43da-8b72-317b1244e4b9.png)

There were also some errors with I think 3-10 helices, but I can't seem to find examples of them, maybe I fixed it without knowing.

Some shartp turns in helices result in bad geometry (3AXT): 

![image](https://user-images.githubusercontent.com/36021261/235359950-f9ee5e4d-dd76-4f43-9e6e-e07301937e1f.png)

This is a result of interpolating between the rotations of the alpha-carbons, rather than properly lofting them. Might have to create a system for lofting around the helices.

**Comment by passm97** [comment]
There's also an issue with cartoon representations in some alphafold models, whereby the helices are twisted and rather sharp. They do still seem to be detected correctly though, but rotation of the helix doesn't fix the issue.

**Comment by BradyAJohnston** [comment]
@passm97 can you by any chance link to any specific models? or is it just for all of them?

**Comment by passm97** [comment]
[bamb.pdb.zip](https://github.com/BradyAJohnston/MolecularNodes/files/11364879/bamb.pdb.zip)

It's all the models I have currently tried (about 10), I've attached an example one here - issue seems to be exactly the same between them all and they were made with a variety of different alphafold versions

**Comment by BradyAJohnston** [comment]
Thanks for the example! I've got a working fix. I'll try and get some other problems cleaned up as well then release a patch
