### ISSUE TITLE
Loading oxytocin from local pdb with ball and stick fails to find S-S bond.

### ISSUE THREAD

**Issue by kendrick90** [BradyAJohnston/MolecularNodes#218]
Loading oxytocin from local pdb with ball and stick fails to find S-S bond.

1. use Avogadro to load oxytocin -> import from chemical name -> save as pdb
2. Load pbd in MN 
3. add ball and stick node
4. check find bonds
5. No bond between the two large sulfur atoms

![image](https://user-images.githubusercontent.com/50811104/235869761-7debd02b-8059-488c-b0af-4e14ce849b77.png)

I am also unable to separate the double bonds but I see you already know about that one. Maybe this is actually the same problem of how pdbs of smaller molecules are used?

**Comment by BradyAJohnston** [comment]
Thanks for the bug report! 

I have tested and disulphide seem to be imported on protein structures, but not for the `.pdb` files. I think you are right that it is likely the same issue as the double bonds. Hopefully there will be a fix coming soon for that.

In the mean time, to create the disulphide bond you can do the following steps as a work around:

- 1. With the structure selected, press <kbd>Tab</kbd> to go into `Edit Mode` which will show you the underlying vertices & edges which make up the mesh / atom (atoms & bonds). You may have to additionally press <kbd>Shift</kbd> + <kbd>Z</kbd> which will go into X-ray mode to view the underlying mesh.


![image](https://user-images.githubusercontent.com/36021261/235873492-fe9ac041-fd6e-4cc2-aced-669979e8f208.png)

- 2. Once in edit mode, select both the sulfur atoms which you wish to create a bond between, by <kbd>Shift</kbd> + <kbd>Left Click<kbd>'ing them.

![image](https://user-images.githubusercontent.com/36021261/235873716-b32a1e62-4bd1-4045-9a88-740025232245.png)

- 3. With the atoms selected in `Edit Mode`, press <kbd>F<kbd> which will create an edge / bond between the two atoms.

![image](https://user-images.githubusercontent.com/36021261/235873750-38416434-0bf9-46e4-8798-a6d4cc6da646.png)
- 4. Exit `Edit Mode` by <kbd>Tab</kbd> / <kbd>Shift</kbd> + <kbd>Z</kbd>
![image](https://user-images.githubusercontent.com/36021261/235873779-eef2b3a5-6b98-42da-810f-3b52982d0167.png)
