### ISSUE TITLE
Atomium failed to install on Mac with M1

### ISSUE THREAD

**Issue by ktamiola** [BradyAJohnston/MolecularNodes#22]
Ladies and gentlemen how to install `atomium` on a Mac M1 so that Blender's Python 3.10 can use it?

**Comment by BradyAJohnston** [comment]
Is the 'install Atomium' button not working? Can you give more details about the addon version and the error that you are getting?

**Comment by ktamiola** [comment]
@BradyAJohnston apologies for a laconic explanation. The installation was failing due to an issue with the installation of `scipy`. I have sorted both. **MolecularNodes** are working like a charm. This ticket should be labeled as **invalid**.

**Comment by BradyAJohnston** [comment]
Glad it's all working!
