### ISSUE TITLE
Can't get imported morph to stop looping

### ISSUE THREAD

**Issue by kailinguo24** [BradyAJohnston/MolecularNodes#224]
I generated a morph between two states in pymol and imported it into blender and it plays, but I'm unable to stop it from looping. This is an issue for my particular use case because I'm trying to make a kind of explanation video for a catalytic cycle, so I need to animate and talk about some other things while it's in one state, then be able to show the morph transition into another state, then talk about that. I've tried changing the frame start and end, but it seems to only control the segment of the animation that loops? I could just replace it with the "still frames" at either end and have the morphed shape appear and disappear, but it would be nice to have control over the playback directly in the nodes.

**Comment by BradyAJohnston** [comment]
The animation will play back from the first frame till the last, as the `Animate 0..1` value changes from 0 to 1. You can manually keyframe this value if you want particularly fine control over the animation playback, or you can create your own map range setup as below: 

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/94b5f20d-1e8f-4069-91cb-98b6cc9bd0a4)


This will play back the entire animation from frames `1` till frames `100`. You can change the `To Max` value to `0.5` and this will play back half of the animation across those frames etc.

I have realised there is a slight bug that at `Animate 0..1` value of exactly `1`, the animation loops back to the first frame. I will change this in a future version, but for now you can fix it as below: 

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/72e9e309-26aa-4d9b-834e-15849042b375)

I hope this gets at what you are after! Let me know if you need more help.

**Comment by kailinguo24** [comment]
Got it, thank you so much!
