### ISSUE TITLE
Alpha-helix design/shape 

### ISSUE THREAD

**Issue by FilouPlains** [BradyAJohnston/MolecularNodes#236]
# Alpha-helix design/shape

**First, I want to thank you for the amazing job you have done so far! Your tool is very efficient to draw great structure, and I love the fact that we can now use cartoon representation!**

## Example image

![helix](https://github.com/BradyAJohnston/MolecularNodes/assets/96999425/f31fc456-091a-4f87-91cd-fe1ff861863f)

## Is it possible to do the same?

I actually tried to used cartoon, and I do like the fact that you can personalize a lot of its aspect. I was wondering though if it was possible to add option about:

1. Colouring the inside of the helix _(as shown is the upper picture)_ to have better results.
2. Having the helix extremities more like in a triangle shape _(as shown is the upper picture)_ than a squared shape.

I think adding those option would be great to have better results and personalization! I am still doing those manually (using `VMD` wavefront, then selecting helix inside for the colouration…), but it was possible to do it with this tool, I will be greatly pleased!

Else, keep going your fantastic job!

**Comment by BradyAJohnston** [comment]
Hi @FilouPlains, thanks for the kind words! The image is only half loaded, but I think I get what you mean. It should certainly be possible, and something that I would be happy to implement. 

I'll be away for a couple of weeks from next week so I don't know if I'll get time to work on it before / during then, but it is certainly on the list!

**Comment by FilouPlains** [comment]
Thanks a lot for your quick answer! I just figured out about the half load image, sorry about that! Have a nice day!

**Comment by BradyAJohnston** [comment]
Tracking in #382, will overhaul and include more options in 4.1
