### ISSUE TITLE
Error with instalation packages depenedencies

### ISSUE THREAD

**Issue by emmc316** [BradyAJohnston/MolecularNodes#250]
I'm having problems to use MolecularNodes in Blender 3.5, I had used before but today I was to use it. I notice that now it requires some dependices (in this case) *biotite*.

The problem is that it never is installed. Always i got this output and I tried open Blender as Admin I got the same output in the console.

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/82389602/ccffdb1f-b54f-44f3-9364-f4475583b999)

I checked that folder but is empty

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/82389602/e74102b3-a71f-4e2c-b9c4-a7213cec7a3f)

**Comment by BradyAJohnston** [comment]
are you able to provide more details as to your computer and operating system? Initially I would suggest maybe an uninstall and clea reinstall of both Blender and Molecular Nodes.

Do all of the package installations fail the same way?
