### ISSUE TITLE
Cylindrical helices lose sharp edge when turning on strand arrows

### ISSUE THREAD

**Issue by PlethoraChutney** [BradyAJohnston/MolecularNodes#259]
Hey Brady, thanks so much for all your work on this incredible project!

# Bug Description
When turning on "Arrows" in `MOL_style_cartoon` while "Cylinders" and "Shade smooth" are both true, the cylinders lose the sharp edge between the side and faces. Strands also lose sharp edges when arrows are added, but this may be expected behavior.

No arrows:
![no-arrows](https://github.com/BradyAJohnston/MolecularNodes/assets/27385979/599e9813-3774-4984-97fe-6ff6e07c4409)

Arrows:
![arrows](https://github.com/BradyAJohnston/MolecularNodes/assets/27385979/5e596b8a-d0c6-47a2-8f12-ac42ccacfa24)

Arrows, shade smooth False:
![arrows_no-shade-smooth](https://github.com/BradyAJohnston/MolecularNodes/assets/27385979/fcc645c7-2201-431b-939d-a834b6beedf9)

# To reproduce
1. Load a PDB (e.g., 6WTH)
2. Replace Atoms style with Cartoon
3. Check `Cylniders` [also, here's a typo :)]
4. Check `Arrows`

# Expected Behavior
Cylinders should retain their sharp edges regardless of style chosen for strands.

# Specs
 - OS: MacOS Ventura 13.4.1
 - Hardware: M2 Mac Air 2022
 - Blender Version: 3.6.0
 - MolecularNodes Version: 2.7.4

**Comment by BradyAJohnston** [comment]
Thanks for the bug report! Just had play around and I've got a working fix. I should be able to improve the smooth shading for AH / BS as well when you go down to a `Profile Resolution` of 4.

Additionally thanks for catching the typo, amazed nobody has pointed it out until now

**Comment by PlethoraChutney** [comment]
Awesome! Thanks, and as always, loving MolNodes!
