### ISSUE TITLE
Selection > AA Name doesn't insert new node

### ISSUE THREAD

**Issue by tubiana** [BradyAJohnston/MolecularNodes#28]
And last one of today's batch 😅

when I tried to insert a node "selection > AA Name", nothing happens and no new nodes are inserted...

Cheers!
Thibault.

**Comment by BradyAJohnston** [comment]
Thanks for reporting!

**Comment by BradyAJohnston** [comment]
Fixed in [v0.5.21](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.5.21)
