### ISSUE TITLE
biotite module not found error during installation on Apple Silicon

### ISSUE THREAD

**Issue by karlduderstadt** [BradyAJohnston/MolecularNodes#291]
**Describe the bug**
A 'biotite module not found' error occurs when attempting to install MolecularNodes in a fresh copy of Blender 3.6.1 on apple silicon. 

I was able to resolve the issue by following the MacOS M1 instructions on the [installation page](https://bradyajohnston.github.io/MolecularNodes/installation.html) suggested for MDAnalysis package but adapted for the biotite package. See detailed instructions at the bottom.

**To Reproduce**
1. Go to Edit
2. Click on Add-ons
3. Install MolecularNodes using the downloaded zip file
4. Check the box next to Molecular Nodes
5. This triggers the error message, which is a python backtrace ending with biotite module not found.

**Expected behavior**
Installing MolecularNodes using the downloaded zip file should prompt the user to install biotite and other required packages without throwing an error.

**Error Codes**
Unfortunately, I didn't take a screenshot when it happened and now it is fixed on my system. I am happy to break it again to make a screenshot if you like, but I think the problem is pretty clear from my description.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Hardware: M2 Mac
 - Blender Version: 3.6.1
- MolecularNodes Version: 2.8

**Workaround**
Install [miniconda](https://docs.conda.io/en/latest/miniconda.html)
Download and build the required packages for your system

```
mkdir ~/biotite-wheel
cd biotite-wheel
conda create -n wheel-builder python=3.10 cython
conda activate wheel-builder
python -m pip wheel biotite==0.35.0 --cache-dir .
conda deactivate
```
Install the built .whl packages, into Blender’s bundled python. Navigate to your Blender’s python folder (this is the default path for Blender 3.6)
```
cd /Applications/Blender.app/Contents/Resources/3.6/python/bin/
```
Install the cached .whl into the bundled python that came with Blender.
```
./python3.10 -m pip install biotite --cache-dir ~/biotite-wheel
```
The Install biotite button should now successfully install the remaining packages or they already appear installed in the add-ons panel in the Blender Preferences. 

You don't need to create the conda environment twice if you already created wheel-builder to install the MDAnalysis package. In that case you can skip the `conda create` command and just activate it directly.

**Comment by BradyAJohnston** [comment]
Apologies for the bug and great to see your workaround. This problem should also be resolved in [2.8.1](https://github.com/BradyAJohnston/MolecularNodes/releases).
