### ISSUE TITLE
Missing tutorial DNA tools

### ISSUE THREAD

**Issue by gbayarri** [BradyAJohnston/MolecularNodes#297]
**Describe the bug**
Some of the tutorial DNA tools are not currently available

**Desktop (please complete the following information):**
 - OS: MacOS
 - Hardware: M1 Mac
 - Blender Version: 3.6.1
- MolecularNodes Version: 2.7.4

**Additional context**
Trying to reproduce the DNA video tutorial (https://www.youtube.com/watch?v=Slk0e_cRmlk), I noticed that some DNA tools such as _Curve join_ and _Curve extract_, are not available in the current version (2.7.4). Is there another way to execute these tools?

**Comment by m-dr** [comment]
Have you found solution for this? I'm in the same boat with 2.10.

**Comment by BradyAJohnston** [comment]
Apologies for missing the reply to this! The DNA stuff I am in the process of overhauling and refactoring. Some of the nodes are missing from the last refactor, and I didn't put them in as I wanted to fix it up again first. 

You can download the earlier versions of the nodes which will include them, which are mentioned in the tutorial, but hopefully I can have some newer DNA nodes out soon!

**Comment by BradyAJohnston** [comment]
Collecting and tracking in #405
