### ISSUE TITLE
feature request : add residue_number to MOL_atom_properties

### ISSUE THREAD

**Issue by sokrypton** [BradyAJohnston/MolecularNodes#3]
will allow selection or coloring by residue index

**Comment by BradyAJohnston** [comment]
It is already available! Under the `AA_sequence_number`. The naming of it all probably needs rethinking, open to suggestions.

**Comment by sokrypton** [comment]
Maybe call it "residue_number". I assumed "AA_sequence_number" indicated the amino acid type at each position. :)

**Comment by BradyAJohnston** [comment]
Will make more consistent and clear naming part of the next update :)

**Comment by BradyAJohnston** [comment]
fixed in [0.4 release](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/0.4)
