### ISSUE TITLE
add MolecularNodes to the MDAnalysis "used by" page

### ISSUE THREAD

**Issue by orbeckst** [BradyAJohnston/MolecularNodes#30]
MolecularNodes is awesome, and it's fantastic that MDAnalysis can help with importing trajectories. Thank you for acknowledging our library!

MDAnalysis has a "Used-by" page https://www.mdanalysis.org/pages/used-by/ . I opened a PR to add MolecularNodes to this page at https://github.com/MDAnalysis/MDAnalysis.github.io/pull/228 — it would be great if you could have a quick look that you're happy with the representation of your project. A quick comment on the PR is all I am looking for.

Should you not want to be listed then we'll respect your wish, of course, you just have to say something.

**Comment by BradyAJohnston** [comment]
Thanks for mentioning Molecular Nodes on the official website, very exciting! It all looks good :)
