### ISSUE TITLE
Install biotite, MDAnalysis, and others unavailable in 2.9.0

### ISSUE THREAD

**Issue by hiyata** [BradyAJohnston/MolecularNodes#305]
Hi Brady, 
In the newest version It seems like the options to install biotite, MDAnalysis, mrcfile, starfile, and eulerangles are unavailable in the add-ons section. Downgrading to 2.8.1 made the options appear again. I'm running on Blender 3.6.2 as administrator on windows 11. I'm not sure if I did something wrong in the installation or if it's a bug. Thanks!

**Comment by BradyAJohnston** [comment]
I am not able to replicate this immediately, but I am on a mac machine and I can try again at home on my windows machine. 

What about if you uninstall old MN, restarted Blender, then reinstall?

**Comment by subunit23** [comment]
Hi Brady, I had the same issue on a M1 and like the OP downgrading to 2.8.1 showed the options again. Restarting Blender and re-installing didn't appear to solve the issue.

**Comment by BradyAJohnston** [comment]
Are you able to provide some screenshots? If possible also to start blender from the terminal, then copy & paste error messages that are printed.

**Comment by BradyAJohnston** [comment]
I managed to recreate the issue on one of my windows machines at home. I have created a slightly updated release which _seems_ to fix the issue, but I am still 100% unsure what was causing the issue in the first place, so I am unsure if it is actually fixed. 

Please try this release and let me know how it goes: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.9.1

**Comment by hiyata** [comment]
It seems like the issue has been fixed for me using the new version! Not sure what the problem was but thanks for the quick update!
