### ISSUE TITLE
Ribbon Nucleic

### ISSUE THREAD

**Issue by AlaaHuwaidi** [BradyAJohnston/MolecularNodes#307]
I am not sure where to categorize this. Basically I want model my DNA with "Ribbon Nucleic", the reason is to cover the gap in the backbone of the DNA, but the input of the "Ribbon Nucleic"node is "Atom" so this Atom doesn’t match with other nodes (the input/output is "Base"). is there a middle nodes that could convert the Atom to Base?
![Screenshot 2023-09-17 at 12 55 22 PM](https://github.com/BradyAJohnston/MolecularNodes/assets/29840879/82668aa8-c522-443b-a8d9-a51b3a89ffc6)

**Comment by BradyAJohnston** [comment]
You can do so using the 'helix curve' output from the DNA node. You can use 'Curve to Mesh' and that will create the backbone ribbon. 

The DNA system I am most of the way overhauling, so things may change soon.

**Comment by BradyAJohnston** [comment]
collecting and tracking in #405
