### ISSUE TITLE
Mol style ribbon cannot be loaded

### ISSUE THREAD

**Issue by sjpiper** [BradyAJohnston/MolecularNodes#31]
Hi all,
I am getting the following error, when trying to add the Ribbon style node, under Styling-Style ribbon.
(The same thing happens when trying to add any of the nodes from the Molecular Nodes package).
Thanks!

Python: Traceback (most recent call last):
  File "C:\Users\sarah\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 2501, in invoke
    return self.execute(context)
  File "C:\Users\sarah\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 2495, in execute
    bpy.context.active_node.node_tree = bpy.data.node_groups[
AttributeError: 'FunctionNodeRandomValue' object has no attribute 'node_tree'

location: <unknown location>:-1

**Comment by BradyAJohnston** [comment]
Can you share which version of Molecular Nodes you are using, operating system you get this error on and the blender version?

**Comment by sjpiper** [comment]
Thanks, all fixed now with the latest upload :)
