### ISSUE TITLE
Overhaul Python Node Creation for Blender 4.0

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#313]
With the upcoming Blender 4.0 release, there are a number of dramatic changes coming.

Import and parsing of files seems to be unaffected (mostly uses non-`bpy` functions), the only breaking change I have encountered being the node group API for creating node custom node groups.

 Details of the API changes in the [release notes](https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API).

I have wanted to overhaul API node creation for a while, but I held off as I knew there were breaking changes coming.

Tasks for Blender 4.0 release: 
- [x] Identify affected functions (basically all functions inside of `MolecularNodes/nodes.py`)
- [x] Design a more generalisable method for creating node trees programmatically (inspiration from [Blender Plots](https://github.com/Linusnie/blender-plots) which has some nice classes for reducing boilerplate).
- [x] Reimplement custom node groups with new API

**Comment by BradyAJohnston** [comment]
@Linusnie do you have any advice / suggestions, from your implementation in Blender Plots? (Also you'll want to update yourself with the upcoming API changes in 4.0).

**Comment by Linusnie** [comment]
@BradyAJohnston thanks for the heads up! From what I can tell from the notes it should just be a matter of updating the 
 `NodeLinker` class. Though I'll probably hold off until the full 4.0 release.

For the implementation the trickiest part was to parse each kwarg to a node socket name/value. I found it works well for the nodes I use in blender plots, but there are probably a few socket types that I don't handle

**Comment by BradyAJohnston** [comment]
Thanks for the details @Linusnie. It's still another month and and a half until the 4.0 release so I won't be tackling it for a while, but I'll certainly be taking heavy inspiration from your implementation.

**Comment by BradyAJohnston** [comment]
Still not as generalised as I would like to it be, and will revisit soon, but the 4.0 PR #349 fixed all of the broken node creation node and simplified a lot of it.

**Comment by Linusnie** [comment]
@BradyAJohnston in case you find it helpful somehow, I recently added support for 4.0 in blender-plots https://github.com/Linusnie/blender-plots/commit/729e8a6c0c64524b52e63357edcc4532d3ad3304 :)

**Comment by BradyAJohnston** [comment]
Thanks @Linusnie, good to see it's updated (and that yours still handles 4.0 / 3.6).
