### ISSUE TITLE
Attribute Error in Blender 3.2 when loading Molecular Nodes

### ISSUE THREAD

**Issue by prateekbansal97** [BradyAJohnston/MolecularNodes#32]
Hi, 

I have installed molecular nodes on Blender 3.2 on macOS Catalina on Intel hardware. The installation is successful (doesn't pop up any errors) but fails to load the Geometry Nodes specific to Molecular Nodes. I am attaching a screenshot of the error I faced. Please let me know what I might be doing wrong. Thanks!

![image](https://user-images.githubusercontent.com/37157969/175332325-94b1f04f-fb48-475d-8222-9d762a891cfa.png)

**Comment by BradyAJohnston** [comment]
Hi mate! Thanks for the error report. What version of Molecular Nodes are you using? If you are using < 0.7, try upgrading to the most recent version (https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.7) which should fix those errors that were introduced with Blender 3.2.
