### ISSUE TITLE
Installation of dependencies appear to be installing to the wrong instance of python

### ISSUE THREAD

**Issue by sfhbarnett** [BradyAJohnston/MolecularNodes#326]
**Describe the bug**
Pressing the "install Biotite" button causes an error which says to check the logs. Checking the logs seems to suggest that everything installed correctly however the stout shows the wrong python interpreter. (I was also running as administrator). I've attached the log file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Hardware: [ x86 PC]
 - Blender Version:  3.3
- MolecularNodes Version: 2.10

[side-packages-install.log](https://github.com/BradyAJohnston/MolecularNodes/files/12860454/side-packages-install.log)

**Comment by sfhbarnett** [comment]
Ok this was me not realising I had multiple blender installations on the computer and was opening the wrong one (that was out of date)

**Comment by BradyAJohnston** [comment]
I still sometimes run into this problem myself, all good!
