### ISSUE TITLE
Required packages using an Externally Managed Environment

### ISSUE THREAD

**Issue by bejucoo** [BradyAJohnston/MolecularNodes#328]
**Describe the bug**
When trying to install the required packages to use the addon I get a `This environment is externally managed` error. I tried installing the packages using **pipx** following the log recommendations. I was able to install all of them: `biotite 0.38.0`, `mdanalysis 2.6.1`, `mrcfile 1.4.3` and `starfile 0.5.0`.

But it seems like the addon doesn't recognize them as installed. In the addon panel I get a _Please install biotite in the addon preferences_.

How should I handle this with my python environment being externally managed?

**Error Codes**
```
INFO:root:Running Pip: '['/usr/bin/python3.11', '-m', 'ensurepip']'
ERROR:root:Command failed: ['/usr/bin/python3.11', '-m', 'ensurepip']
ERROR:root:stdout: 
ERROR:root:stderr: error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.
```

**Desktop (please complete the following information):**
 - OS: Linux-6.1.58-1-lts, EndeavourOS 03-2023
 - Hardware: x86_64, Intel i5
 - Blender Version: 3.6.4
 - MolecularNodes Version: 2.10.0

**Comment by BradyAJohnston** [comment]
I am unfamiliar with environment management on Linux, so I a may not be the best person to try and help. It seems though that you might not be using the python kernel that ships with Blender. How do you have Blender installed? 

If it is a non-standard installation then this might be causing issues, but if it is a standard download / install, there should be a python kernel that ships with Blender. On ARM macOS if is here: 
```
/Applications/Blender.app/Contents/Resources/3.6/python/bin/python3.10
```

So you could manually ensure that you are installing the packages with the specific environment via (but whatever the equivalent for the Linux installation is): 
```
/Applications/Blender.app/Contents/Resources/3.6/python/bin/python3.10 -m pip install MDAnalysis==2.6.1
```

This might help? Again I don't have any experience with environments in Linux.

**Comment by bejucoo** [comment]
I installed Blender using [pacman](https://wiki.archlinux.org/title/Pacman), my distribution package manager.

You were correct, my installation is using the system's python kernel (3.11.5). I checked but it seems that when I install Blender using pacman it doesn't create a python folder. It'd normally be in `/usr/share/blender/3.6/python`, but it doesn't exist.

So I installed Blender using the direct download from the site which does have the python folder and was able to correctly install the required packages using the kernel that ships with the program (3.10.12).

The only things I had to do was to install `libxcrypt-compat` (using pacman) and pip:

`./python3.10 -m ensurepip --upgrade`

I'll keep trying to install the required packages in my original Blender installation. I'll write the updates here.

Thanks Brady!

**Comment by BradyAJohnston** [comment]
Okay glad it was a relatively straightforward fix. I would assume you could probably have the pacman installed version work, if Blender is given the right paths to find the packages. Unsure why it wouldn't have access to system packages if it is using the system python, but it could potentially be a fix to just make it aware of the package installation locations.

It could also be an error with versions. Blender are very specific with their python versions. Currently they are locked to 3.10.X, with no guarantee outside of that version that things won't break as a lot of the API can be sometimes fragile. In theory not much should break from increasing the version, it's probably best to stick to 3.10 as well.
