### ISSUE TITLE
Problems with importing Amber trajectory .nc with topology .prmtop

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#337]
### Discussed in https://github.com/BradyAJohnston/MolecularNodes/discussions/335

<div type='discussions-op-text'>

<sup>Originally posted by **vagra98** October 29, 2023</sup>
I'm trying to import a trajectory done in Amber with .nc file format and topology .prmtop but nothing shows up and no error is given. I did also tried to convert everything using Parmed to GROMACS type files but also without success. Any idea of what could be going wrong? I'm doing everything via the GUI in the MD Trajectory sector inside Scene. Thanks again Brady :) </div>

**Comment by BradyAJohnston** [comment]
Hi @vagra98 I created an issue which will be better for tracking than a discussion. 

Are you able to provide some more information to debug? If you share the files then I can ensure that they work properly, otherwise if you share some screenshots of pre and post import to see if anything changed. 

It might be that the structure is imported, but depending on the style that you have selected, which can display in some render views and not others, or might not work for particular topology types.

In the example below there has been an object created when importing the trajectory, has anything appeared for you?

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/b2399d46-220a-4d8d-a296-2f22eb8000a1)

**Comment by vagra98** [comment]
This is what I get from importing them, no mesh is being formed. Could this be a problem with MDAnalysis? I did managed to open the files with VMD with no issues. 
I'm not really sure how to send larger files in comments, I've uploaded the files I've tried in Google Drive: 
[https://drive.google.com/drive/folders/1qXyR9Bkt_TxabqWABnDmMPa4MLkZeAi3?usp=sharing](url)

<img width="1920" alt="Captura de pantalla 2023-10-30 083226" src="https://github.com/BradyAJohnston/MolecularNodes/assets/79974624/b2cc426b-8d25-435f-8cf4-5688e2f25a43">
<img width="295" alt="Captura de pantalla 2023-10-30 082424" src="https://github.com/BradyAJohnston/MolecularNodes/assets/79974624/e95e7c2c-c92f-4bd3-bf22-d2ac7c1c703c">
<img width="1920" alt="Captura de pantalla 2023-10-30 082637" src="https://github.com/BradyAJohnston/MolecularNodes/assets/79974624/6dd8c3ea-0c80-43f0-9db4-898be3d717f3">

Thanks for replying so quickly, this is massive for me in both personal and professional work :)

**Comment by BradyAJohnston** [comment]
It is loading correctly, but the 'style_cartoon' doesn't currently work with MD trajectories as secondary structure information isn't imported or calculated currently. 

If you use one of the other styles when importing, or use a different style node it should show up.

**Comment by BradyAJohnston** [comment]
Just tested it out and managed to load the trajectory without any trouble. 

There is a more recent version of Molceular Nodes as well, so you could update to get some newer features, but it should work regardless.

https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/b2dd7550-f256-425f-b29e-f331927d480f

**Comment by vagra98** [comment]
Alright, that makes sense. Updated and, indeed, it works.
