### ISSUE TITLE
How to select a specific residue by residue number 

### ISSUE THREAD

**Issue by prateekbansal97** [BradyAJohnston/MolecularNodes#34]
Hello,

I'm sorry if the answer is obvious, but I've been trying to figure out how to select a specific residue by its residue number and show it as ball and sticks. For example, if I want to show residue `TRP853` as ball and sticks I'm not sure how to do it. I've been able to select all TRPs in the molecule (using the select by amino acids node available in the selections menu), but haven't been able to figure out how to limit the selection to a specific `TRP` (`TRP853`, for example). I'm not even sure if this is possible to do yet, but I'm still trying to see if this is possible. 

Any guidance would be super helpful. Thank you so much!

**Comment by BradyAJohnston** [comment]
Hi @prateekbansal97 thanks for the comment!

It is certainly possible, but it might not be obvious and I haven't covered it in any of the docs or tutorials yet. 

There is a property that is the `AA_sequence_number` and this is the residue numbers. You can use this with a `Compare Node`. This is a geometry nodes node, not through my Molecular Nodes. You can find in under `Utilities -> Compare` and and compare to the number that you want. You could also do "Great Than" / "Less Than" to get a range of residue numbers. 

Then you put that boolean value (pink) into the Atom Selection node and you will only have the atoms that match that selection.

![image](https://user-images.githubusercontent.com/36021261/177224001-6a86c436-eb2b-4631-afe2-197e3d3ac298.png)

![image](https://user-images.githubusercontent.com/36021261/177224192-90f3c5e3-14c5-4ef8-9af6-8d1c7ced1f0d.png)

![image](https://user-images.githubusercontent.com/36021261/177224202-56feeb46-a693-4864-ae7a-22c56fb76c25.png)


I'll leave this issue open until I document this properly inside of the docs!
