### ISSUE TITLE
 Install biotite, MDAnalysis, and others unavailable in 2.11.2 

### ISSUE THREAD

**Issue by dlackner** [BradyAJohnston/MolecularNodes#348]
**Describe the bug**
Similar issue to one of the more recently closed issues.  The options to install biotite, MDAnalysis, mrcfile, starfile, and eulerangles are unavailable in the add-ons section. I am using Blender 4.0.1 with 2.11.2 MN. I tried uninstalling MN, restarting blender, reinstall. Ubuntu 22.04

**To Reproduce**
1. Install 2.11.2
2. Add ons should appear 
3.  No option for add ons

**Expected behavior**
After a successful installation we should see an option to install the required dependencies. 

**Screenshots**
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/23264976/0283bea4-fde4-4745-9745-1ad03dc6fb0a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Hardware: x86 PC, i7
 - Blender Version: 4.0.1
- MolecularNodes Version: 2.11.2

**Additional context**
Thanks Bradley, I know this may be hard to reproduce with your current setup. Let me know if there is any more information I can provide.

**Comment by BradyAJohnston** [comment]
The current release isn't set to work with Blender 4.0 (3.5 / 3.6 only) so I'm guessing that will be the main issue. 

Can you start Blender from the terminal, then copy in any error codes that might be showing up? I don't have a linux machine to test on unfortunately.

**Comment by BradyAJohnston** [comment]
might also help to untick the add-on, uninstall / remove it, restart Blender then reinstall again and see how it goes

**Comment by sulista88** [comment]
> might also help to untick the add-on, uninstall / remove it, restart Blender then reinstall again and see how it goes

Didn't work here, same issue using windows 10.

**Comment by BradyAJohnston** [comment]
@sulista88 which version of Blender are you using? Can you go `Window` -> `Show System Console` and then copy and paste any error codes / messages that show up when you disable and re-enable the add-on?

**Comment by dlackner** [comment]
I switched to Blender 3.6 stable release and was experiencing the same issue with 2.10.0 MN. No option for the ad ons. I removed MNs and rebooted. After rebooting my computer, the issue was resolved and in turn I was able to upgrade to 2.11.2. I am sorry I didn’t catch any of the logs, I hope this helps someone else who encounters this issue. Thank You!

**Comment by BradyAJohnston** [comment]
There can be some issues with switching Blender / Molecular Nodes versions, which is usually solved by a good reboot. Hopefully that's all it is!

**Comment by sulista88** [comment]
> @sulista88 which version of Blender are you using? Can you go `Window` -> `Show System Console` and then copy and paste any error codes / messages that show up when you disable and re-enable the add-on?

Blender 4.0.1
Console:
Read prefs: "C:\Users\Romulo Manoel\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
addon_utils.disable: MolecularNodes not disabled
Modules Installed (MolecularNodes) from 'C:\\Users\\Romulo Manoel\\Downloads\\MolecularNodes_2.11.2.zip' into 'C:\\Users\\Romulo Manoel\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
Template Installed () from 'C:\\Users\\Romulo Manoel\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\MolecularNodes\\assets\\template\\MolecularNodes.zip' into 'C:\\Users\\Romulo Manoel\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\startup\\bl_app_templates_user'

**Comment by sulista88** [comment]
@dlackner I've tried but didn't work for me =/

**Comment by sulista88** [comment]
I've managed to solve the issue apparently....
I've installed Blender 4.0, so I tried to install MN 2.10, didn't show up the addons, I closed Blender and opened it again and then I could install the addons biotite, MD, etc. After I've updated MN to 2.11.2, I can't see the addons preferences panel as in 2.10, but it seems it's working properly since MN in the Scene Panel isn't asking to install biotite as before.

**Comment by BradyAJohnston** [comment]
MN remains broken currently (auto setup of nodes doesn't work) in Blender 4.0, so you will likely run into other problems. 

I'm working on the release for 4.0 which I should have out this weekend.

**Comment by bolerodan** [comment]
Just following up here.

Fresh install of Blender 3.6.5
Install the latest version (or 2.11.0). Same issue. No option to install dependencies. The scenes panel asks me in red to install the dependencies in the addon preferences. No such way.

**Comment by rabiakd** [comment]
Using Windows 10 - Installed Blender 3.6.2 - downloaded and installed the .zip MN 2.11.2 - The add-on preferences Biotite and MDAnalysis doesn't show. Attaching the screenshot from system console.
![Screenshot 2023-11-27 163032](https://github.com/BradyAJohnston/MolecularNodes/assets/152224779/fceaa7ae-1071-48f8-8905-c658b0165a13)

**Comment by loot001** [comment]
yea, i have same issue using 3.6.5. will wait for new version for blender 4

**Comment by BradyAJohnston** [comment]
I have just released the Blender 4.0 compatible version, please try it out and see if the issue is fixed: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v4.0.0

**Comment by BradyAJohnston** [comment]
I was able to finally reproduce this error on another machine, and have released (yet another) version which should finally fix it (v4.0.1): https://github.com/BradyAJohnston/MolecularNodes/releases

**Comment by BradyAJohnston** [comment]
@ErikPoppleton do you have to stick with 3.6 Blender? Seems to be fixed in 4.0.2 and Blender 4.0 brings a bunch of nice improvements. I can make a release that targets 3.6 if need be as I have now figured out what should be causing it.

**Comment by ErikPoppleton** [comment]
One of my colleagues is doing a tutorial next week for a bunch of people who probably won't have developer tools installed, so the dependency of MolecularNodes 4 on SciPy and the associated installation issues (see my response [here](https://github.com/BradyAJohnston/MolecularNodes/issues/367#issuecomment-1835817746)) is going to be a problem for getting the rest of the group set up (4.0 works fine for me).

I'm not sure what the best solution for this problem is, since compilers and linear algebra libraries are such a basic part of programming, but for biologists who's first exposure to this sort of thing is MolecularNodes, the error messages that Scipy throws is very intimidating and unhelpful.
