### ISSUE TITLE
Group Input Node not Available

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#35]
@orbeckst Thanks for the installation guide! That's really helpful and I got atomium and MDA linking to work(now both buttons are grey). When I was trying to load the pdb and xtc, I still got the following error. It seems to be something from blender
![blender-bug](https://user-images.githubusercontent.com/42550849/177223792-98dbd286-5d31-43cf-be93-ffde7c200c57.png)
.

_Originally posted by @ChenouZhang in https://github.com/BradyAJohnston/MolecularNodes/issues/24#issuecomment-1174447127_

**Comment by BradyAJohnston** [comment]
Hi @ChenouZhang can you try some earlier versions of molecular nodes (maybe 0.7.X) and see if that works at all?

**Comment by ChenouZhang** [comment]
@BradyAJohnston with 0.7.2 I got the same error. @orbeckst made them to work with Blender 3.1.2 + molecular_notes 0.5.19. My hunch is that they updated group input in blender 3.2.

**Comment by BradyAJohnston** [comment]
I haven't had anyone else with issues on Blender 3.2. When is this error happening? Opening a local file? Downloading from PDB? Opening an MD trajectory?

**Comment by orbeckst** [comment]
For the record: I installed Blender 3.2.0 (macOS 10.15.7, x86) and Molecular Nodes 0.8.1. (MDAnalysis is 2.2.0 from conda-forge on Python 3.10).

**Comment by ChenouZhang** [comment]
@BradyAJohnston I tried PDB 6z3z/7dsw directly downloaded through blender and some other local pbds. All of them referred to the same error.

**Comment by BradyAJohnston** [comment]
Can you send a screenshot of your preferences panel showing Molecular Nodes? Just so I can see all of the details and file path etc

**Comment by ChenouZhang** [comment]
Hope this included everything
![blender-3](https://user-images.githubusercontent.com/42550849/177227247-57d12d25-fa9b-48bb-a0c5-d829815cc972.png)
.

**Comment by BradyAJohnston** [comment]
Hmm I can't see anything immediately wrong. Could you try reinstalling Blender & molecular nodes? Might help. Seems to be working with Blender 3.2 & Molecular Nodes 0.8.1 for myself and others. 

What OS are you on?

**Comment by ChenouZhang** [comment]
@BradyAJohnston I reinstalled everything. Blender 3.2 + Molecular Nodes 0.8.1 worked just fine. Maybe getting mda ready before any of those installations can help(I did update me conda during the process so that could mess up).

**Comment by BradyAJohnston** [comment]
Hi @ChenouZhang this is good to hear! Sometimes the classic 'turning it off and on again' is just the trick. It will remain a mystery what was going wrong...
