### ISSUE TITLE
Can't see atoms in blender < 3.2

### ISSUE THREAD

**Issue by FedeClaudi** [BradyAJohnston/MolecularNodes#36]
Hey, 

Thanks for developing this ad-on. I've been following your updates on twitter and it looks amazing, finally I've had an evening to give it a try.

Unfortunately I could not get it to work with Blender 3.1.2. I've followed the installation and getting starting docs and it all went smoothly but I couldn't see the atoms in any way. Updating to Blender 3.2 fixed everything. Perhaps I've missed it in the docs but it might be good to have a warning to encourage prospective users to update to the latest blender.

keep up the amazing work!

**Comment by BradyAJohnston** [comment]
Hi mate! It is mentioned in the docs currently, but I should probably make it a lot more obvious. I've updated the docs with some more explicit mentions of the version requirements.
