### ISSUE TITLE
Currently unable to install Molecular Nodes 4.0.2 on Blender 4 in Mac (specifically, Scipy)

### ISSUE THREAD

**Issue by lmardcarvalho** [BradyAJohnston/MolecularNodes#367]
Today I tried installing the new molecular nodes 4.0.2 on two different MAC devices (older IOS, versions 10 and 11).

Installation on molecular nodes proceeds fine.

Then, one of two issues happens:

1. "Scipy" installation fails. Before this failure users are prompted to install "Xcode command developer tool for mac".

2. There is no option to install any of the additional modules of Molecular Nodes. The usual interface for Biotite, MDA Analysis, Scipy does not show up.

Since I don't own the MACs I'm unable to paste the error log at this moment. Will try to update the post as soon as possible.

**Comment by BradyAJohnston** [comment]
hmmm this sounds strange. I develop on Intel and M2 Macs and I haven't come across this, so would be interested to see what the error codes are.

**Comment by ErikPoppleton** [comment]
I solved this for somebody a couple days ago.  If you don't have the Xcode tools, you don't have a Fortran compiler or OpenBLAS, which are two external libraries that Scipy depends on to build.  If you use Conda, you can install both of these with Conda, but it's probably just easier to get the dev tools.  Note that you will also probably be missing the Python.h header files and will have to follow [these instructions](https://github.com/BradyAJohnston/MolecularNodes/issues/108#issuecomment-1534648555).

I am also having the problem with the interface not showing up in both Blender 4.0 and 3.6 and haven't figured out how to solve it yet.

**Comment by BradyAJohnston** [comment]
@ErikPoppleton thanks for the details on installation. I have found that Blender has some built-in math utilities that should be able to replace the requirements for scipy (which I currently just using to convert rotation matrices to eulers), but I won't get to doing that for a few days, just made a new release (v4.0.3) which should fix at least the initial requirement to install it: https://github.com/BradyAJohnston/MolecularNodes/releases

**Comment by ErikPoppleton** [comment]
Awesome, thank you!  This should solve our version conundrum!
