### ISSUE TITLE
Split atoms/bonds geometry

### ISSUE THREAD

**Issue by FedeClaudi** [BradyAJohnston/MolecularNodes#37]
As mentioned in the previous issue, I've just started using the ad-on so apologies if I'm creating an issue for something that is obvious/already implemented. 

I was trying to create a balls and stick visualization of DNA
![image](https://user-images.githubusercontent.com/17436313/177424662-871846e7-74b4-4ebb-9b63-38ecde70b916.png)

if I load it with the bonds enabled I can see them:
![image](https://user-images.githubusercontent.com/17436313/177425438-c081fb68-5acd-49c2-a077-538f3392dded.png)

but I can't change their thickness or appearance.

So what I did is I've converted the bonds geometry to curve and then back to mesh with a circle curve around it and passed that as a separate group output instead of merging it to the nodes geometry:
![image](https://user-images.githubusercontent.com/17436313/177424782-662e4af3-2865-46c8-a09f-6740e948762b.png)

then it's simply a matter of setting the material for the bonds separately: 
![image](https://user-images.githubusercontent.com/17436313/177424865-92d7f711-d60b-4d71-9389-fac4bc20b91a.png)

and of course the circle curve radius can be changed too:
![image](https://user-images.githubusercontent.com/17436313/177424933-7f732327-9a07-427b-9d93-6c2ff87303df.png)

The reason why the material needs to be separately is that otherwise the bonds are colored based on the closest atom:
![image](https://user-images.githubusercontent.com/17436313/177425660-65442e8f-c51c-4460-98e1-3470d712e6f9.png)

So I was thinking it might be a nice option to separate the two so that users can color/scale  the bonds independently of the atoms.

Ps. it might be easier if `atoms radii` (and perhaps in the future `bonds radii`) was an input to the main molecular nodes geometry node so that they can be changed without having to look into the node group.

**Comment by BradyAJohnston** [comment]
You can use the `Style Sticks` node to visualise the bonds, and the `Rescale Radii` to change the scale of the radius. Have a watch of the my youtube tutorials that walk through the functionality of it: https://www.youtube.com/watch?v=CvmFaRVmZRU

**Comment by FedeClaudi** [comment]
That makes sense. Sorry I should've looked into the docs more before opening an issue, I was just too excited to dig in!
Outstanding work!

**Comment by BradyAJohnston** [comment]
All good, it's great to see that you were able to poke-around behind the scenes and figure out how it was all working. Feel free to ask about / request other features that you might think of :)
