### ISSUE TITLE
no color when plugged into volume.

### ISSUE THREAD

**Issue by tubiana** [BradyAJohnston/MolecularNodes#38]
Hi Brady :) 

I saw something strange... I see no color information when I plugged the shader into `volume`. Is it a bug from the new attribute system ?
Exemple : 
- Plugged into `Surface`
![image](https://user-images.githubusercontent.com/8037224/177550146-4db8bb8e-7c44-4fee-9f02-218e105c865f.png)

- Plugged into `Volume` 
![image](https://user-images.githubusercontent.com/8037224/177550668-0ad0ccde-62cb-49dc-878f-606b4f4eece5.png)

- Expected results (with just random color here, I tried to check if it was possible to have different colors when plugged into Volume..)
![image](https://user-images.githubusercontent.com/8037224/177550504-74d40e2f-c39a-4c24-8637-0e0805169e0f.png)

Thank you ;)

**Comment by BradyAJohnston** [comment]
I will however just close this as it’s a Blender-issue and not Molecular Nodes  (unless you come across something else, in which case feel free to re-open the issue).
