### ISSUE TITLE
Selection > Multiple Residue Selection doesn't work as expected

### ISSUE THREAD

**Issue by lesburg** [BradyAJohnston/MolecularNodes#385]
When trying to select multiple residues using the Molecular Nodes > Selection > Multiple Residue Selection, the automatically generated node only selects the last residue id in the list. This is due to problems in the connections in the autogenerated node.

To reproduce, follow these steps:
1. launch Blender (there is no need to load a protein)
2. enter Geometry Nodes workspace and click "New" at the top of the Geometry Nodes pane to create a new group
3. in the Geometry Nodes pane, type A to add a new node, and select Molecular Nodes > Selections > Multiple Residue Selection
4. in the Multiple Residue Selection dialog, type "1,2,3" (no quotations). This generates a new node called "Select Res Id Custom" with three residues (1, 2, and 3) defining the selection.
5. Select the new node by clicking on it, then type tab to enter the node
6. It it clear that the selection connected to Group Output only contains the last selection

Rather, I would expect it to result in all specified residues to be selected. See image of the node logic that has been made to function as expected.

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/232603/00a122be-f17a-4704-ad75-77f642fb62fe)
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/232603/0826d63a-3d78-49f6-80b6-0457053a7594)
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/232603/0c8e4728-c8a9-40fc-9478-f13c77fc53d1)
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/232603/7542ae66-c55a-486c-b2af-5e8208f096aa)

I'm using Blender 4.0.2 and Molecular Nodes 4.0.6 on Windows 10

P.S. this is *amazing* software and I deeply appreciate your work on this!

**Comment by BradyAJohnston** [comment]
Hello! Thanks for catching and reporting this. I can confirm this is a bug, and I've got a (very quick) fix for it that I should be able to have out shortly.
