### ISSUE TITLE
Freestyle issue

### ISSUE THREAD

**Issue by FedeClaudi** [BradyAJohnston/MolecularNodes#40]
Hi, 

It's me again. This time I've read the docs and I'm starting to get the hang of it, outstanding work with this package!

Recently I was toying around with using Blender for maths [illustrations](https://twitter.com/Federico_claudi/status/1539748908229955584?s=20&t=BQhgtehebwaCQ_ZFNLk5pg) 
For that, one of my favorite effects if FreeStyle to add a line around geometry after rendering
![image](https://user-images.githubusercontent.com/17436313/177841673-65a1b60b-353b-4729-ad94-a91cff2f9754.png)
![image](https://user-images.githubusercontent.com/17436313/177841754-3987a64a-430a-4af2-af8f-f6dbaf1f0634.png)

But I couldn't get it to work with molecular nodes:
![image](https://user-images.githubusercontent.com/17436313/177841469-e2880235-b35d-42c3-921e-33ebce9b8947.png)
![image](https://user-images.githubusercontent.com/17436313/177841882-53d8d8b1-55a0-4fb0-ab1f-dbfb41f0def1.png)

it only picks up the edges, not the atoms. I've tried playing around with a few things, but I'm not very familiar with the point cloud structure. Would you have any advice on how to get this to work?

**Comment by BradyAJohnston** [comment]
Try using the 'Style Atoms EEVEE' node for the atoms, should solve it. I think the point-cloud rendering isn't picked up by freestyle modifier. 

Could also try the grease pencil outline modifier I think that works with point clouds.

**Comment by FedeClaudi** [comment]
Hey,  style atomes EEVEE did the trick: 
![image](https://user-images.githubusercontent.com/17436313/177942615-98ccc9d7-11b5-4958-a714-69d8532f9b70.png)

it also made rendering 8x faster without any noticeable change in appearance, win win!

**Comment by BradyAJohnston** [comment]
Glad it all works out!
