### ISSUE TITLE
importing star file: object is not subscriptable

### ISSUE THREAD

**Issue by DrJesseHansen** [BradyAJohnston/MolecularNodes#403]
Hi Brady,

I am trying to import a star file for a single tomogram. I have it formated for RELION 3.1 (with an optics header).  Note that I have also tried removing the optics header and that does not work.

here is the input data:

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/118282980/b750ca01-ea3d-4d8d-9caa-04270a22ea47)

when I click load it gives me the error "object is not subscriptable" see below.

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/118282980/63449835-b507-4bef-a19f-e0ea36192948)

this is with molec nodes 4.0.2 running on Mac M2

thanks!

Jesse

**Comment by BradyAJohnston** [comment]
I believe this was fixed in 4.0.4, try upgrading to the latest release (4.0.7) and see if you have any luck!

**Comment by DrJesseHansen** [comment]
that was indeed the solution, thanks!

**Comment by BradyAJohnston** [comment]
Let us know if you have any other questions or problems!
