### ISSUE TITLE
Unable to install atomium

### ISSUE THREAD

**Issue by Mangkun-Chen** [BradyAJohnston/MolecularNodes#41]
![image](https://user-images.githubusercontent.com/108992267/178114080-6ab96530-889c-4f97-a7e3-21d58fcc3326.png)

I'm located in China. Maybe it's because of the network. I tried many times and couldn't install Atomium. Is there any other way?

**Comment by BradyAJohnston** [comment]
You should still be able to download OK. Are you able to share what version of Blender & what version of Molecular Nodes you are using? Also if possible to show blender console during install to see the error. (Windows -> Console)

**Comment by Mangkun-Chen** [comment]
I tried version 0.9 and 0.81 of Molecular Nodes. Blender is 3.2.
I'm downloading again. The speed is very slow. It's been 3 minutes. But I installed it successfully this time. Thank you！！
![image](https://user-images.githubusercontent.com/108992267/178126889-dcdb56b5-c672-4509-ac94-ad5bdabd41d3.png)

**Comment by BradyAJohnston** [comment]
I'm glad it is working now! Was v0.9 not working? And now v0.8.1 is working? I might have to double check the release.

**Comment by Mangkun-Chen** [comment]
I started with version 0.9 yesterday, but this version failed to install atomium. Later, I tried version 0.8.1 which was also unsuccessful. This morning, I open the console according to your method, and then it succeeded. (The version is 0.8.1)

**Comment by Mangkun-Chen** [comment]
Another problem has just been encountered, but it has been solved. In blender version 3.2.0, I can't import protein, and a few lines of errors will be displayed. However, after updating to 3.2.1, it was successful.

**Comment by Mangkun-Chen** [comment]
I found the problem. If my blender is set to Chinese, I cannot download protein. If it is changed to English, there is no problem, and it may not be a version problem. In the morning, I changed blender to English in order to find "(windows - > console)", which may be the reason for my success.

**Comment by Mangkun-Chen** [comment]
![image](https://user-images.githubusercontent.com/108992267/178127478-825401ed-4a93-47fd-b430-4ef623c03b04.png)

When I change the interface to Chinese, I can reproduce the error

**Comment by BradyAJohnston** [comment]
Ah I see. Yes this has come up once before in #29 where changing from Japanese -> English fixed the issue. Seems to be that in non-english languages this changes some of Blenders internal Python API. I will try to come up with a way around this, but for the time being it seems that Switching to English will fix the problem. Thanks for the detailed error report and being able to reproduce this!

**Comment by BradyAJohnston** [comment]
Now tracking in #63
