### ISSUE TITLE
Ribbon style settings for DNA

### ISSUE THREAD

**Issue by satary** [BradyAJohnston/MolecularNodes#424]
Hello, Brady!
I am struggling with the DNA visualization. I would like to only show the DNA trace (without bases, or show them as sticks), but the ribbon style always contains bases. If I use a backbone selection, the bases are still shown, though seriously distorted (see figure, looks like they are drawn from some backbone atom to the coordinate zero). 

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/2101895/ef118b83-f801-42d6-ac57-4c5af6b9cce8)

Is there any way to disable bases drawing/changing base shape?

**Comment by BradyAJohnston** [comment]
Thanks for reporting this. I haven't implemented any kind of check for if the base atoms actually exist, so while it's getting the backbone and creating the ribbon, it is instancing the bases but when trying to decide on their rotations it fails and rotates to the `(0, 0, 0)` world origin. It makes sense that if you select just backbone that it should only display the backbone ribbon, and something that I'll implement going forward.

On the `Style Ribbon` node, you can press <kbd>Tab</kbd> to go inside the node. If you connect the `Ribbon Curve` output from the `.MN_utils_style_ribbon_nucleic`to the `Group Output`. That will expose the curve that is generated for your own usage.

![CleanShot 2024-01-30 at 11 18 46@2x](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/e0d24814-d67d-44b8-b503-dc1c1fe66133)

<kbd>Ctrl</kbd> + <kbd>Tab</kbd> to exit the node, and use that curve to generate your own ribbon.

![CleanShot 2024-01-30 at 11 20 34@2x](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/c3597481-c09e-4cfb-bc24-574bee6fcd80)

Hopefully this works for what you are after, and I will make this simpler going forward.

**Comment by satary** [comment]
Wow! That's cool, thanks for the advice!
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/2101895/98bbc257-2fc7-42b6-856c-d1a9224234dc)
