### ISSUE TITLE
Biotite not installing on Blender 4.0.2 with MN ver. 4.0.9

### ISSUE THREAD

**Issue by JimHBean** [BradyAJohnston/MolecularNodes#426]
**Describe the bug**
Biotite and MD Analysis would not install after the Molecular Nodes 4.0.9 zip was installed in Blender 4.0.2. It produced an error message saying "error installing packages" and directed me to a log file. I have attached the contents of the file below.

**To Reproduce**
1. Install MN 4.0.9 the usual way and click on either Install Biotite or Install MD Analysis 
2. Follow path provided in the error message

**Error Codes**
[side-packages-install.log](https://github.com/BradyAJohnston/MolecularNodes/files/14179963/side-packages-install.log)

Computer is MacBook Air (M1 2020) running macOS Monterey v 12.2.1

**Comment by BradyAJohnston** [comment]
The logs look OK. If you restart Blender, are you able to use the import panel?

**Comment by BradyAJohnston** [comment]
I'm closing this, but feel free to re-open if it remains an issue

**Comment by JimHBean** [comment]
Hi
Sorry I thought we got back to you on this. This is sorted, and so was the issue we had with the CIF file not opening with the new release 😊
Thanks for your efforts,
James.

Mr James Hodgkinson-Bean (He/Him) | Bachelor of Science (Adv) Honours
PhD candidate

The Department of Microbiology and Immunology
University of Otago | Te Whare Wānanga o Otāgo
Mobile/Waea pūkoro  +64 0213 10 448
Department of Microbiology and Immunology Building
720 Cumberland Street, Dunedin North, 9016, Dunedin | Ōtepoti
New Zealand | Aotearoa

Email/Īmera ***@***.***


From: Brady Johnston ***@***.***>
Date: Monday, 19 February 2024 at 9:07 pm
To: BradyAJohnston/MolecularNodes ***@***.***>
Cc: James Hodgkinson-Bean ***@***.***>, Author ***@***.***>
Subject: Re: [BradyAJohnston/MolecularNodes] Biotite not installing on Blender 4.0.2 with MN ver. 4.0.9 (Issue #426)

I'm closing this, but feel free to re-open if it remains an issue
