### ISSUE TITLE
Find and break bonds nodes are not present.

### ISSUE THREAD

**Issue by CFisicaro** [BradyAJohnston/MolecularNodes#428]
I can't find the `find bonds` and `break bonds` nodes under _add molecular nodes_.

1. Go to 'Add->Molecular Nodes'
2. No `bonds` option is present

I thought the option to view the bonds would be displayed there.

![Screenshot 2024-02-10 at 03 19 18](https://github.com/BradyAJohnston/MolecularNodes/assets/66260709/de739f35-7b32-499c-ac18-270b114bbce1)

 - OS: MacOS
 - Hardware: M1 Mac
 - Blender Version: 4.0.1
- MolecularNodes Version: 4.0.9

It's not critical because I can get the bonds outside MN but it would be very convenient to have such a feature.
Finally, I've seen that the `bonds` nodes are present in `MN_data_file.blend`

**Comment by BradyAJohnston** [comment]
You are correct! I didn't realise they weren't properly exposed. I'll add them back to the menu
