### ISSUE TITLE
Add trajectory smoothing when importing via MDAnalysis

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#440]
Support potentially trajectory smoothing when importing an MD trajectory via MDAnalysis. (https://docs.mdanalysis.org/stable/documentation_pages/transformations/positionaveraging.html)

Potential for in theory to add enable / disable support for a variety of transformations. Some of these will be best implemented through Geometry Nodes node groups, but when streaming the trajectory from disk, transformations like averaging will be best done via MDAnalysis as Geometry Nodes won't have access to any frames other than the one that is currently loaded.

**Comment by BradyAJohnston** [comment]
Seems that it might be a bit more complex, as we can't directly alter a transformation after it has been applied (https://github.com/MDAnalysis/mdanalysis/discussions/4477#discussioncomment-8669043). Potential for us to have a panel for the trajectory to add or alter a transformation, but that it would require a bit of load time as the universe is re-loaded.

**Comment by Dan-Burns** [comment]
Smoothing frames would be great. I don't know the blender python API well enough but it's easy to take the coordinates from two frames you want to interpolate between and make the intermediate coordinate arrays.

**Comment by BradyAJohnston** [comment]
Subframes that interpolate between frames of a trajectory are already implemented and can be accessed via the 'Object' tab of the 'Molecular Nodes' panel after importing a trajectory. As you increase the number of subframes, the number of interpolated frames in between are increase.

![image](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/6c45da77-54e5-46eb-9011-2a85a45a5c93)

This enhancement is more about utilising the trasnformations inside of MDAnalysis, which can load several frame (say 5 at a time) and then average their coordinates to create a smoother overall trajectory, rather than just interpolating between existing frames of a trajectory

**Comment by Dan-Burns** [comment]
That's great - glad I know that now!
