### ISSUE TITLE
Missing secondary structure

### ISSUE THREAD

**Issue by francoviscarra** [BradyAJohnston/MolecularNodes#442]
Hi,

I'm new to molecular nodes and I'm trying to render a protein with cartoon representation, but apparently if I import locally it doesn't get any secondary structure attributes (actually I don't see any attributes at all). I have read that there is a DSSP implemented in MN, but I can't seem to find it, has it been removed?

Is there any other way to provide secondary structure information to render the cartoon representation?

Best wishes,
Franco

**Comment by BradyAJohnston** [comment]
Hi @francoviscarra which version of blender / MN are you using? Importing locally should still attempt to guess some secondary structure, but but this wasn't the case in some earlier versions of the add-on.

There was some version of the `DSSP` in a node, but I removed that in the mean time as it was breaking with me changing a bunch of nodes. If you can import from a `.cif` file, then it should definitely contain the secondary structure information and will import that instead of having to guess.

**Comment by BradyAJohnston** [comment]
@rbdavid that's an interesting workaround that I might have a look at. Might be able to include DSSP in the import method if installed on someone's system.

I'm confused why you create a new `mkdssp_sec_struct` attribute instead of just writing to the `sec_struct` attribute?

**Comment by rbdavid** [comment]
I didn't want to overwrite data is all. An added bonus was it allowed me to switch between standard MN Cartoon style and the MKDSSP Cartoon style to see the differences in results/rendering. 

I really struggled to install MKDSSP on my Windows desktop where my blender is running. I certainly am not a Windows power-user so maybe its an easy install process for someone who is. Specifically, MKDSSP has numerous dependencies that were not easily installed on Windows. So I gave up on running MKDSSP through a script within my blender instance. There is a slightly-outdated conda-packaged version but I still struggled to get that to install correctly. On my Linux desktop, the installation process was much easier just a couple of "apt-get" lines. 

Don't even get me started on why I'm not running Blender on my linux desktop. Grumble grumble grumble.

**Comment by rbdavid** [comment]
> I'm confused why you create a new `mkdssp_sec_struct` attribute instead of just writing to the `sec_struct` attribute?

Also, the Cartoon representation nodes were built around the MN_select_sec_struct node, which only differentiates residues by helix-like, sheet-like, or loop-like. The MKDSSP attribute values are more diverse than those reported by biotite.structure.annotate_sse so I had to create a geo-node that pared down the diverse secondary structure types into similar selections as MN_select_sec_struct. The Cartoon rep shouldn't care if a helix is a \alpha, 3_{10}, or \pi helix to draw those residues as a helix, for example. That being said, the left-handed helix might render weirdly but those are rare. 

That .blend file in my github has a frame in the geo-node window where I did all of the node-tree editing. Nodes that I had to change/replace were colored in red and kept in close-proximity to the working nodes for documentation purposes.

**Comment by francoviscarra** [comment]
@BradyAJohnston I'm using blender 4.0 with MN 4.0.10, and I'm loading a PDB obtained from an MD trajectory. Whenever I try to add an StyleCartoon node I get the `Attribute does not exists 'idx'` warning.

@rbdavid Thank you, I will give your script a try!

**Comment by rbdavid** [comment]
@francoviscarra Well, I'm not confident that my script will solve the problem you are seeing with Attribute error. I have not pushed up to MN 4.0.10. Is the PDB file a single frame's structure or a multi-framed trajectory?

**Comment by francoviscarra** [comment]
@rbdavid Well, if I convert my PDB to annotated mmCIF with mkdssp (I ended using the webserver since I'm missing a few libraries and can't be bothered to install everything right now) I can render cartoon representation in blender. So that's one way of fixing it. Thank you!

**Comment by rbdavid** [comment]
I haven't come across this issue with attribute `idx`. 

Does reloading the pdb file into a new blender object still raise the error? Maybe post some screenshots of what's going on, showing the Geometry Nodes Editor and Info views.  

Great to hear that the mkdssp output file is working for you!

**Comment by francoviscarra** [comment]
Here's an screenshot of the PDB loaded into cartoon representation:

<img width="1280" alt="image" src="https://github.com/BradyAJohnston/MolecularNodes/assets/98550346/b4ad5264-3482-4c41-b02d-e518b1532698">

**Comment by rbdavid** [comment]
Try out the `.MN Utils Style Cartoon` node instead. Its in **MolecularNodes -> Utilities -> Cartoon Utilities** dropdown menus. Looking at my MN objects' spreadsheets, I'm not seeing an `idx` attribute associated with the atoms (listed in the `Original` spreadsheet not the `Evaluated` spreadsheet).

**Comment by BradyAJohnston** [comment]
@francoviscarra glad that it's working if it goes through dssp & becomes `mmcfi`. If you would be willing to share the `.pdb` I can maybe troubleshoot what might be going on in that node group

**Comment by BradyAJohnston** [comment]
Apologies I just went and tested it - secondary structure information doesn't seem to be imported for any `.pdb` file. When I did an internal refactor I seemed to have accidentally dropped the fallback calculation when secondary structure isn't extracted from the file!

**Comment by Dan-Burns** [comment]
Hi Brady,

I installed the latest version but seem to be having this issue with cartoon representation.

I also tried the "find_bonds" node which I believe was the trick in an older version. 

Spheres representation populates the "point" spreadsheet but everything disappears from it with the cartoon style node.


![Screenshot from 2024-03-21 12-12-33](https://github.com/BradyAJohnston/MolecularNodes/assets/58605062/2ad2a47e-e43b-4ba3-b4ac-36003b210736)

**Comment by BradyAJohnston** [comment]
@Dan-Burns this is an issue with importing via MDAnalysis / MD import. Currently no secondary structure information is read from the `.pdb` file by MDAnlysis - so that is why it doesn't work.

If you load via the 'open local' and then also via the MD, you can sample the `sec_struct` attribute from the locally imported version to get the secondary structure information and use in the in the MD animated version.

![CleanShot 2024-03-22 at 10 30 06@2x](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/862ecb80-024c-4ee3-a288-75116f9de07e)

An important point is that the structure being sampled from has to have the exact same atoms as the structure storing the new attribute (as it is just sampling based on corresponding `Index`.). So remove any of the node groups on the structure you are sampling the secondary structure from and this should work on your MD imported structure.
