### ISSUE TITLE
"Centre Structure" option removes Center of Geometry translations rather than Center of Mass

### ISSUE THREAD

**Issue by rbdavid** [BradyAJohnston/MolecularNodes#443]
Hey Brady, 

I'm trying to visualize an analysis where two protein structures are aligned side-by-side. At the moment, I can't seem to recover the true alignments that I see in VMD (used as a test case). I think this is because I've been using the `Centre Structure` option when loading the structure files into Blender. As far as I can tell, that option utilizes the biotite.structure.centroid method (https://www.biotite-python.org/apidoc/biotite.structure.centroid.html) that removes the center of geometry (CoG) translation from of the protein atom positions. Having just realized this, I really need to be removing the center of mass (CoM) from the structures before applying the pre-calculated rotation matrix. I could calculate the CoM externally and remove that from the atoms' 'position' attribute but I'd much rather be able to remove the CoM and calculate the alignment rotation matrix internally to the blender instance.   

So a couple questions: 
1) MDAnalysis has a nice AtomGroup.center_of_mass() function to calculate the very flexible AtomGroup object's CoM (https://docs.mdanalysis.org/2.7.0/documentation_pages/core/groups.html#MDAnalysis.core.groups.AtomGroup.center_of_mass). Similarly, MDA has a set of alignment calculation methods (for example, https://docs.mdanalysis.org/2.7.0/documentation_pages/analysis/align.html). Is it possible to access the MDA universe object that MolecularNodes creates/uses? I feel like I've seen a MDA Universe object created somewhere within MN code. I just can't remember where. 
    - Along those lines, is MDA becoming more central to initializing MN objects? That would be an awesome development, if possible. I see that you are presenting during a MDA workshop tomorrow. Good luck! I hope to catch the VOD when that gets published. 

2) Can the MolecularNodes/molecularnodes/data.py file include the atomic masses of elements listed in the elements dictionary? Maybe the mass can be included as an attribute associated with atoms of a MN object? 
    - I have created a dictionary that mirrors all key-values in the MN data.py `elements` dictionary but also includes the atomic masses for elements that match with key naming in the atomicWeightsDecimal dictionary (https://github.com/HegemanLab/atomicWeightsDecimal; found this just through a quick google search). MDA also includes a table for atomic masses (MDAnalysis.topology.tables.masses). Here's my file: https://github.com/rbdavid/Blender_files/blob/main/Data/element_data.py

I'm happy to help implement these changes if help is needed. Thanks in advance!

**Comment by BradyAJohnston** [comment]
I'm happy to include the masses in the `data.py` dictionaries - and would be something useful to have in MN going forward.

When importing via downloading from the PDB or parsing a local file, `biotite` is used and `MDAnalysis` is only used when importing via the `MD` import method. Trying to use methods from `MDAnalysis` while importing via `biotite` would get messy and I'd ideally want to avoid it. 

If we get the masses from the `data.py` though, the `com` calculation could happen during import, or it could also be done via nodes (probably options for both). 

If first you wanted to create a PR to include the masses that would be great. I can give some help with turning that into an attribute if you'd like. If you'd like to contribute a `com`  calculation we can use that, otherwise that can be implemented later.

**Comment by BradyAJohnston** [comment]
Looking at that dictionary you linked as well - I have also been meaning to create a dictionary for converting from `atomic_number` to letters etc for potentially writing `.pdb/.cif` files. We could replace my existing dictionary with the ones you have there.

**Comment by rbdavid** [comment]
Before I make a PR, can you explain where the elements dictionary is used? I'm noticing instances of duplicate entries (ex: Na and NA both mapping to sodium), which suggest maybe the dictionary is used for interpreting atom names used in structure files. Similarly, there are some interesting entries such as D mapping to a carbon atom instead of deuterium. And a smattering of course-grained particle types also included in the dictionary. 

Maybe a second dictionary is appropriate that contains a mapping between standard atom names used in structure files (originating from AMBER, CHARMM, OPLS force fields or crystallographic naming conventions that I'm not familiar with) and their associated element. This way, hopefully the ambiguity/diversity of atom name formatting gets accurately mapped to the element symbol and subsequently can be mapped to the element's atomic number/vdw radius/full name/ mass (info held within the `elements` dictionary). 

Additionally, there are a whole bunch of 100 values in the `'vdw_radii'` keys in the `elements` subdictionaries, which I suspect are just place-holders. Should a default vdw_radii value be set, for visualization purposes, that is overwritten if an atom has an element with a `'vdw_radii'` key in its `elements` dictionary entry?

**Comment by BradyAJohnston** [comment]
> Before I make a PR, can you explain where the elements dictionary is used?

They are used when creating the models inside of Blender, usually to translate from string to integer values, or for looking up values like VDW radii. 

When parsing regular structure files:

https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/molecule.py#L384-L389

https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/molecule.py#L438-L445

When importing a MD trajectory: 

https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/mda.py#L172-L176

https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/mda.py#L180-L185

>I'm noticing instances of duplicate entries (ex: Na and NA both mapping to sodium), which suggest maybe the dictionary is used for interpreting atom names used in structure files. Similarly, there are some interesting entries such as D mapping to a carbon atom instead of deuterium. And a smattering of course-grained particle types also included in the dictionary.
> Maybe a second dictionary is appropriate that contains a mapping between standard atom names used in structure files (originating from AMBER, CHARMM, OPLS force fields or crystallographic naming conventions that I'm not familiar with) and their associated element. This way, hopefully the ambiguity/diversity of atom name formatting gets accurately mapped to the element symbol and subsequently can be mapped to the element's atomic number/vdw radius/full name/ mass (info held within the `elements` dictionary).

There are some entries relating to course grained simulations and other non-standard elements etc. I would be in favor of us moving those out into a separate backup dictionary perhaps that can be used as a fallback, to help with organisation.

> Additionally, there are a whole bunch of 100 values in the `'vdw_radii'` keys in the `elements` subdictionaries, which I suspect are just place-holders. Should a default vdw_radii value be set, for visualization purposes, that is overwritten if an atom has an element with a `'vdw_radii'` key in its `elements` dictionary entry?

You are correct that these are currently just placeholders. I just at the time (when I very first started writing this add-on years ago) wither couldn't be bothered or couldn't reliably get values for those elements and so left them as is. Would be in favor of removing them and using just a fallback value. 

I have been thinking also of potentially removing the `vdw_radii` attribute from being added explicitly from being added, and instead turning this dictionary into a lookup table inside of Geometry Nodes that is only used when needed (for spheres, bond calculations etc). I wouldn't be doing that till Blender 4.1 though when they introduce some new nodes for it.

**Comment by BradyAJohnston** [comment]
Happy to discuss more about potential design implementations as well. 

I'm still not _super_ happy with how I internally go about getting the attributes added to the structure. It was a solution that worked at the time and I just haven't revisited it since.

**Comment by rbdavid** [comment]
Great! 

- [ ]  I'm gonna remove the placeholder vdw_radii values, remove duplicate and non-element entries (stashing them in a backup dict), and add atomic masses to the `elements` dict. 

- [ ] For vdw_radii, a default value of 100 picometers can be used in line 185 of https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/mda.py#L180-L185 similar to what's done in https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/molecule.py#L438-L445.

- [ ]  I'll implement a function in both molecule.py and mda.py to gather the atomic masses into a numpy array, mirroring the functions used for `vdw_radii`.

Towards this last task and 
> I'm still not _super_ happy with how I internally go about getting the attributes added to the structure. It was a solution that worked at the time and I just haven't revisited it since.
What's wrong with using `bpy.data.objects[MN_object_name].data.attributes[attribute_name]` and then converting it to a numpy array or mathutils matrix? 

Finally, are there unit/integration tests for `data.elements` or instances where changes to `data.elements` will cause tests to fail? I haven't done too much digging into the `MolecularNodes/tests` directory.

**Comment by BradyAJohnston** [comment]
>Finally, are there unit/integration tests for data.elements or instances where changes to data.elements will cause tests to fail? I haven't done too much digging into the MolecularNodes/tests directory.

I haven't got any tests specfically for the `data.py` files, but they are used for most of the other tests. If you'd like to add some tests specifically for them, I won't say no to more robust tests.

> What's wrong with using bpy.data.objects[MN_object_name].data.attributes[attribute_name] and then converting it to a numpy array or mathutils matrix?

I am unsure what you are saying here. I have happy with the `mn.blender.obj.set_attribute()` and `mn.blender.obj.get_attribuet()` which get and set attributes from meshes, these take and return numpy arrays.

What I mean more specifically is that I set up all the potential attributes as a function (for the example of the vdw_radii, `att_vdw_radii()`, which is only evaluated when the function is called. This way I can delay the creation of attribute into a simple loop with `try` `except` in case the attribute can't be generated. I am unsure what would be a better approach, of there even would be a better approach, but it feels a bit messy for my liking.

**Comment by rbdavid** [comment]
Yeah, thinking about this more, the `data.elements` dictionary is used whenever a structure is loaded - so basically every test is potentially affected by the changes in that dictionary, albeit not likely resulting in any fatal errors. The most precarious type of changes being made... 

I don't think a test handle needs to be written around the `data.py` data structures directly. I guess a better question for me to ask is, how do I run all or a subset of the tests before doing the PR?  My previous experience has been using a series of test handles stashed in module files in `if __name__ == '__main__':` blocks. Then, just run `python module.py` in a terminal and check the output via assert statements. Is it a similar process here, just in the blender python interpreter? Maybe I'm being overly cautious here though.

**Comment by BradyAJohnston** [comment]
The tests I run outside of Blender, utlising the `bpy` module that is installable from pip. You can run the test suite inside of Blender but it can be a bit of a mess around.

```bash
conda create -n molecularnodes python==3.10
conda activate molecularnodes
pip install -e .
pip install pytest pytest-snapshot pytest-cov scipy
```

To run run tests:

```bash
# run all tests with verbose output
pytest -v

# run pattern matched tests for a string
pytest -v -k attribute

# run tests in a single file
pytest -v tests/test_attribute.py
```

**Comment by BradyAJohnston** [comment]
Apologies as I do need formalise all of this better in a `CONTRIBUTING.md`

**Comment by rbdavid** [comment]
I've got code for calculating the Center of Mass but I'm not sure where to place it in the module files. Should users be given the choice to center by the CoG or CoM in the Scene -> Molecular Nodes -> import options? 

Here's the code block though: 

```
def center_by_CoM( positions, masses): 
    """
    :parameter positions: np.ndarray, shape = (nAtoms, 3), cartesian coordinates of the structure(s), assumed units of \AA
    :parameter masses: np.ndarray, shape = (nAtoms,), atomic masses of atoms in the structure(s), assumed units of daltons 
                                    and assumed same order as positions
    :return centered_positions: np.ndarray, shape = (nAtoms,3), CoM translation removed from the coordinates
    """
    return positions - np.sum(masses[:,None] * positions, axis = 0) / np.sum(masses)
```

**Comment by BradyAJohnston** [comment]
I think giving the option in UI is a good idea. 

You can use an enum to display the properties like so: 

```python
bpy.types.Scene.MN_center_type = bpy.props.EnumProperty(
    name="Method",
    items=(
        ('mass', "Mass", "Adjust the centre of mass to be at the world origin.", 0),
        ('centroid', "Centroid", "Adjust the centroid (ignoring mass) to be att he world origin.", 1)
    )
)
```

Then display that property on each of the panels for the import methods. 

The panels are defined under `io/wwpdb`, `io/local` `io/md` for the relevant import methods.

**Comment by rbdavid** [comment]
My apologies for dropping this for five days. I've finally got a complex (at least for me) render started so will be turning my attention back to this. 

Code needing to be added: 
- [ ] Add the center_by_CoM() and center_by_centroid() functions to an appropriate location. 
- [ ] Add UI options. (see https://github.com/BradyAJohnston/MolecularNodes/issues/443#issuecomment-1972495852)

Then its a bunch of testing and checking that the UI panels are working appropriately.

**Comment by rbdavid** [comment]
> ```python
> bpy.types.Scene.MN_center_type = bpy.props.EnumProperty(
>     name="Method",
>     items=(
>         ('mass', "Mass", "Adjust the centre of mass to be at the world origin.", 0),
>         ('centroid', "Centroid", "Adjust the centroid (ignoring mass) to be att he world origin.", 1)
>     )
> )
> ```
> 
> Then display that property on each of the panels for the import methods.

I don't have a great sense for what this will look like in the UI. Is it going to be a single check box for the `centre` option that then unlocks a choice for `mass` or `centroid` via a drop-down menu or further checkboxes?

**Comment by rbdavid** [comment]
MN_import_centre is defined in [~/molecularnodes/props.py](https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/props.py#L4-L8). I assume that's where the MN_center_type, suggested above, would be defined. 

Then, in wwpdb.py and local.py, a few chunks of codes need to be updated. 
- The `def panel(layout, scene):` functions need to have `grid.prop(scene, 'MN_center_type')` added. 
-  Add a `centre_type` keyword argument to the `fetch()` function (https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/wwpdb.py#L7-L40) and how that function is implemented (https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/wwpdb.py#L94-L102). 
- Do similar for the `load()` function in https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/local.py#L22-L55 and https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/local.py#L78-L86. 

Then I'll need to update the `Molecule` class' `create_model()` method (https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/molecule.py#L176-L262) and the `_create_model` function (https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/molecule.py#L321-L606). Add in a `centre_type` keyword argument to both. 

In the `_create_model()` function, the https://github.com/BradyAJohnston/MolecularNodes/blob/f3dbff0f4dcc48e0f9429f74324e1b5cd940534f/molecularnodes/io/parse/molecule.py#L344-L350, do a check to see `if centre and  centre_type == 'centroid'`. If true, run through the code as normal, removing the centroid from the `locations`. Otherwise, `if centre and centre_type == 'mass'`, need to wait to center the structure until after all attributes are looped over and added to the blender object (line 568). Once atom attributes have been created for the MN object's atoms, then the `elements` dictionary can be used to map that atomic_number array to an atomic_mass array, which can then be thrown into the code above to calculate the CoM. Remove the CoM from locations and update the `position` attribute.

**Comment by rbdavid** [comment]
Log file from the `pytest -v` is at https://github.com/rbdavid/MolecularNodes/blob/main/tests_results.txt. I haven't done any digging about the various failures. There wouldn't be a log of test results from the original 4.0.11 release, would there?

**Comment by BradyAJohnston** [comment]
All of the logic looks good that you were laying out above. Instead of adding another attribute, we could change `centre` to take an enum, with default to `None` meaning no centering. I think that would be better.

**Comment by BradyAJohnston** [comment]
For the test result failures - for now run `pytest --snapshot-update` and it will update the failing snapshots with their new values. Where there are snapshots that say `The selected attribute 'entity_id' does not exist on the mesh.             Possible attributes are: attribute_names=['b_factor',...` It makes sense that they would fail and change - but I should update them in the future that they wouldn't change with the addition of another attribute. Might be something that I tweak in another PR and then you work from that if you'd prefer (and would result in a smaller diff for your PR).

**Comment by rbdavid** [comment]
Yeah, I'd rather not be the one who pushes the `pytest --snapshot-update` since I haven't done any work on verifying previous and current tests.

**Comment by rbdavid** [comment]
> ```python
> bpy.types.Scene.MN_center_type = bpy.props.EnumProperty(
>     name="Method",
>     items=(
>         ('mass', "Mass", "Adjust the centre of mass to be at the world origin.", 0),
>         ('centroid', "Centroid", "Adjust the centroid (ignoring mass) to be att he world origin.", 1)
>     )
> )
> ```

So, if I want to add the default value of `None` to this enum, just do `default=None,` within that chunk of code? Or do I also need to add a third item to the items tuple? 

Something like 
`('', 'None', 'Do not centre the structure on the world origin.', _some_value_)` where maybe the `_some_value_` should be zero and the other two items should be shifted by 1? I have zero experience making a GUI panel for Blender.

**Comment by BradyAJohnston** [comment]
I just merged #447 which should remove most of the failed snapshot tests. Those that now fail should be legitimate failures.

**Comment by BradyAJohnston** [comment]
> So, if I want to add the default value of None to this enum, just do default=None, within that chunk of code? Or do I also need to add a third item to the items tuple?

The enum property types can only take strings, so yes you could supply `''` as an option - but it might be better from a UX to keep the tickbox for centering. If unticked then the type is grayed out, if ticked then the user can specify the type of centering.

It would look like the current option for adding a style, which can be disabled, but when enabled provides a dropdown menu (which is how the enum is displayed) to choose the type of style.

![CleanShot 2024-03-08 at 16 21 50@2x](https://github.com/BradyAJohnston/MolecularNodes/assets/36021261/d51c4162-324e-45cd-b8e3-7f0298af08f2)

https://github.com/BradyAJohnston/MolecularNodes/blob/5ac81da1ab4681f6da8452555807bcf3c16b9d65/molecularnodes/io/wwpdb.py#L132-L135

**Comment by BradyAJohnston** [comment]
Yep please make a PR! Can have a look at it then :)
