### ISSUE TITLE
Cartoon Style Not Showing for Local PDB

### ISSUE THREAD

**Issue by klmcguire** [BradyAJohnston/MolecularNodes#445]
I go to Molecular Nodes -> Import -> Local and select an AlphaFold2 PDB I made and choose the cartoon style, and then click load. The file loads, but the only style that doesn't work is cartoon.  I can visualize the AlphaFold2 PDB in sphere, surface, ball and stick, but not cartoon.  I don't get any errors.  Should I be able to see the cartoon style or is it not available for local PDB or AlphaFold2 PDBs?

I also ran a quick minimization with the AlphaFold2 PDB using NAMD. I tried importing the DCD to see if I could get the cartoon style that way, but same issue. I could visualize it in every style but cartoon.

I get the same issue if I try to do Import -> Method: PDB -> PDB Format -> Fetch.  The cartoon style only works for mmtf format.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Hardware: AMD 5950X, RTX 3090
 - Blender Version: 4.0.1
- MolecularNodes Version: 4.0.11

**Comment by BradyAJohnston** [comment]
Yes apologies this is a bug. It was fixed in #444 but I have not generated a new release with that yet. If you download from the AlphaFoldDB or the PDB as a `.mmcif/cif` file then it will fix the issue in the mean time.

**Comment by klmcguire** [comment]
Ok no worries, just wanted to make sure this one was reported, but it looks like it's already known, thanks!

**Comment by smouilleron** [comment]
Hi Brady, I'm having the same issue with a few structures I'm refining but I don't have .mmcif/cif for it.  I'll wait for the next release as I'd like to use cartoons as well as the new surface representation, which is great btw...

**Comment by BradyAJohnston** [comment]
This is now fixed in the latest 4.0.12 :)

**Comment by Aseamann** [comment]
I believe this is now broken again in Blender 4.1 with MN 4.1.0
