### ISSUE TITLE
Usage of a missing attribute in the Molecule class

### ISSUE THREAD

**Issue by Blastorios** [BradyAJohnston/MolecularNodes#456]
**Describe the bug**
I tried to use MN inside jupyter lab, but had a surprising error -- a missing attribute. I wonder if this is intended behavior (since blender might inject a 'data' attribute?) or whether this is a legit bug?

**To Reproduce**
```python
import bpy
import molecularnodes as mn

file = mn.io.download('4ozs', 'cif', cache=None, database='rcsb')
model = mn.io.parse.CIF(file)
model  # or 'print(model)'
```
 gives:
```text
File ~/.pyenv/versions/3.10.13/envs/jupyter/lib/python3.10/site-packages/molecularnodes/io/parse/molecule.py:292, in Molecule.__str__(self)
    291 def __str__(self):
--> 292     return f"Molecule with {len(self.data)} atoms"

AttributeError: 'CIF' object has no attribute 'data'
```

**Expected behavior**
I would expect the base class to only use attributes existing in the class itself.

**System**
 - OS: [e.g. Windows / MacOS / Linux] = Windows WSL2 / Ubuntu 20
 - Hardware: [e.g. Intel Mac, M1 Mac, x86 PC] = x86 PC
 - Blender Version: `bpy==4.0.0`
- MolecularNodes Version: `molecularnodes==4.0.12`

**Additional Context**
As a bioinformatician and Pythonista, I love this package. Would not mind to open a PR for it and solve the problem if you agree this is a bug. (Although I wouldn't be to sure what info would be present in `data`. Perhaps `self.name` makes more sense (removing the `len(data)` altogether), as it would return an empty `Molecule()` if no data has been loaded, matching the `None`)

**Comment by Blastorios** [comment]
Just saw #454

**Comment by BradyAJohnston** [comment]
If you'd like to contribute discussion or PRs around improving the bit of a mess that the classes are in at the moment, I welcome that! Apologies for the bit of a confusing API at the moment.
