### ISSUE TITLE
Introducing a Dev branch

### ISSUE THREAD

**Issue by Blastorios** [BradyAJohnston/MolecularNodes#458]
**Is your feature request related to a problem? Please describe.**

I wonder if you would agree on implementing a `develop` branch for the MN project? 

Redesigns, such as the API refactor, are quite destructive to the workflows of others. Especially since the versioning is following Blender, causing breaking changes to occur within _patch_ versions of the package. Most package managers in Python mostly consider _major_ + _minor_ versions (e.g. Python >= 3.10) as these represent a 'stable' API (although not upheld by all in the field, I think it's a good effort to strive towards).

**Describe the solution you'd like**

I think a simple `dev` or `devel` branch can add a great amount of value to keep track of future redesigns of the package without disturbing the `main` from which others might want to reliably capture their beloved package. For example, there are a few broken notebooks in the wild, simply from moving functions behind `.io` (which is currently a bit hard to discover since the docs do not explicitly mention it, I went to the `tests` to look for similar patterns). You would eventually push a completed API overhaul onto `main` when all destructive cases have either been documented, or contain some form of backwards compatibility. (and preferably going into a new major version, but this would clash with the 'Follow Blender's Version')

**Additional context**

I understand this might not align with the way you like to work, so this is more of a question than a recommendation. I do think it might help to mature the package a bit. Perhaps the _major_ version could still follow Blender's _major_, but the _minor_ becomes the new _major_?

Given the currently refactored API `a` and the new API `b`, MN's version would match:
4.0.12 = current (`a`)
4.0.13 = current API refactor hotfix (`a`)
4.1.0 = first release of the newly designed API (`b`)
5.0.0 = newly designed API tested for Blender 5.x.x (`b`)
5.1.1 = API overhaul (backwards incompatible) for Blender 5 (API `c` ?)

**Comment by BradyAJohnston** [comment]
While I am in general agreement with what you are suggesting, Molecular Nodes is very much an add-on first and is only _experimenting_ with being a `pip` installable python package second.

I am in agreement to follow more strictly with not introducing breaking API changes on 'patch' versions, but I would consider and have tried to state that none of the API should be considered stable currently. I have deliberately not published any documentation on the API so as not to give the idea that it could be relied upon. I welcome discussion and suggestions in #359, but like I say in that thread, the API should not be considered stable. The versions are published to `pypi` to enable some tinkering and testing, but this is very much a secondary consideration.

While the versioning might be a bit misleading, given that we are on `v4.0`, like you got from the documentation this is to follow the versioning of Blender the priority is ease of use as an add-on.

I do not have the time / development resources to focus on backwards compatibility or different branches, especially to do with API changes that are currently intended only for internal usage and improvements.

I would certainly welcome efforts from anybody who wanted to help with stablising and maintaining the API going forward, and I would like to formalise more official guidelines about what could be considered 'supported' and for how long in the future. The focus for me is to develop for the currently available version of Blender and improve what I can for that.

**Comment by Blastorios** [comment]
Thanks for the clear explanation! It makes a lot of sense to focus your efforts on the add-on capability first, with the `pypi` package as a nice follow-up. 

I am also looking at #359 in the meantime, as I think MN is a very valuable asset for both the bioinformatics and blender community.
