### ISSUE TITLE
How to slice protein so that we can show the interior region

### ISSUE THREAD

**Issue by ChenouZhang** [BradyAJohnston/MolecularNodes#46]
The idea of slicing protein is important in preparing atomic images since a lot interesting atom-atom interactions are located under the surface of a protein. Is there a function in molecular nodes to select all atoms on one side of a plane so that we can hide that part of the protein to show the interior region?

**Comment by BradyAJohnston** [comment]
I have just uploaded a tutorial video on how to do exactly that by combining the selections: https://youtu.be/ruzrQ6uKvDQ
