### ISSUE TITLE
Extend requirements file in a manner, that we can run the tests locally

### ISSUE THREAD

**Issue by kainszs** [BradyAJohnston/MolecularNodes#461]
Hi,
I noticed while working on the last issue that I had to install additional modules to run the tests locally. I used the github actions as a guide.

Can we cover this via the requirements.txt? This does not affect the project.toml, but only for developers of the project who install it from the repository.

**Comment by Blastorios** [comment]
Do you mean the `dev` dependencies? They are defined the `pyproject.toml` and can be installed using
```bash
poetry install --with dev
```

Perhaps it would help to add this step to the `Contributing` section inside the README.

**Comment by BradyAJohnston** [comment]
The `requirements.txt` is just for use by the add-on inside of Blender, to generate the list of python packages which need to be installed. The required packages for installing via `pip` and for development are defined in the `pyproject.toml`. 

I don't like that the packages & versions are defined twice - but currently the add-on is created from the `molecularnodes/` folder, and only has access to the contents of that folder. Supporting it as both an add-on and a `pypi` package currently means we have to define in two places (unless someone knows a smart way to resolve this)

**Comment by BradyAJohnston** [comment]
And yes @Blastorios this should be defined in the Contributing section. I'll prioritise putting together more contributing documentation over the next couple of days.

**Comment by BradyAJohnston** [comment]
Added a `CONTRIBUTING.md` in #463 . I welcome input on what should also be covered / what should be made more clear. As more questions around development are answered I can ensure that they also go in there.
