### ISSUE TITLE
Can these four formats be imported? If so, which one should I choose?

### ISSUE THREAD

**Issue by Jackbrobeep** [BradyAJohnston/MolecularNodes#488]
![微信截图_20240426180741](https://github.com/BradyAJohnston/MolecularNodes/assets/136829587/a8c02aa1-def9-4276-9b86-8e054745f5a2)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbdavid** [comment]
I am not familiar with ASNT format but if its similar to SDF, JSON, and XML, then likely no. Currently, two python modules are used to import structural data to blender. Biotite and MDAnalysis. 

Biotite documentation for what files can be imported into their structure object: https://www.biotite-python.org/apidoc/biotite.structure.io.html#module-biotite.structure.io (see the submodules list to get the list of file types). 

MDAnalysis documentation for reader/writer file types: https://docs.mdanalysis.org/stable/documentation_pages/coordinates/init.html#supported-coordinate-formats

**Comment by BradyAJohnston** [comment]
SDF should be importable when importing via the 'local file' tab.
