### ISSUE TITLE
Un-centered object import broken

### ISSUE THREAD

**Issue by m-dr** [BradyAJohnston/MolecularNodes#489]
**Describe the bug**
Seems like, using version 4.1 in Blender 4.1, one can't import an object without centering it. This is apparent when trying to import a few separate parts of a larger object.

**To Reproduce**
1. Export separate cif or pdb sub-objects
2. Import them in addon version 4.1 with the 'Centre Structure' unchecked
3. The object is centered anyway (4.0.8 in b4.0 works as expected)

Edit: Seems like it behaves similarly in 4.0.12 (tested in 4.1)

**Comment by BradyAJohnston** [comment]
Thanks for the bug report, I can confirm this happens when importing via the 'local' method.
