### ISSUE TITLE
MN 4.1.0 and Blender 4.1.1 not working

### ISSUE THREAD

**Issue by rkpicada** [BradyAJohnston/MolecularNodes#492]
**Describe the bug**
When I try install biotite I receive an error

**To Reproduce**
1. Go to 'Scene Prop'
2. Click on 'Install biotite'
4. I have a log error... 

**Expected behavior**
Biotite installed

**Error Codes**
Please include associated error codes that are shown in the python console when the error occurs.
> To view the python console on Windows, `Window` -> `Toggle System Console`, on Mac you must start Blender from the terminal.
```
# paste error codes from python console here
```Error: Error installing package. Please check the log files in 'C:\Users\rkpic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\molecularnodes\logs'.

**Screenshots**
If applicable, add screenshots to help explain your problem.

Would you like all the txt from log? If yes, please, let me know in this email    rkpicada@hotmail.com

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Hardware: Intel
 - Blender Version: 4.1.1
- MolecularNodes Version:4.1.0

**Additional context**
sorry my english

**Comment by rkpicada** [comment]
Mr. Brady: I did the above report bug right now and I think the problem was solved after restarting Blender...

**Comment by BradyAJohnston** [comment]
@rkpicada it seems to be a common issue that a few people run into. Glad it's all working now!
