### ISSUE TITLE
Hals of the surface disappear when we unselect "separate" in Surface MN 

### ISSUE THREAD

**Issue by smouilleron** [BradyAJohnston/MolecularNodes#496]
**Describe the bug**
If you load a pdb 5bwx from the pdb and display the protein in surface and centered it loads ok, but then if in the surface representation mode you unselect "separate" half of the surface disappear

**To Reproduce**
1. select PDB = 5BWX
2. Select pdb file
3. Select style = Surface 
4. Select center structure
5. load the pdb
6. Then in the Surface style MN unselect separate
7. Half of the surface should disappear

**Expected behavior**
Half of the surface disappear once you unselect Separate in SUrface MN

**Screenshots**

Before selecting "Separate"
<img width="1122" alt="Screenshot 2024-05-18 at 08 07 39" src="https://github.com/BradyAJohnston/MolecularNodes/assets/58088307/1a52811b-589d-4813-88f6-9896c8bfcf1b">
After selecting "separate"
<img width="1122" alt="Screenshot 2024-05-18 at 08 07 50" src="https://github.com/BradyAJohnston/MolecularNodes/assets/58088307/fb1b6943-1285-45ce-96e6-08417ef0f7e8">

**Desktop (please complete the following information):**
 - OS: [ MacOS]
 - Hardware: [M1 Pro Mac]
 - Blender Version: 4.1.1
- MolecularNodes Version:4.1.0

**Additional context**

**Comment by smouilleron** [comment]
It looks like if you don't recenter it is not doing it...  something wrong happening after centering the structure when loading it.

**Comment by BradyAJohnston** [comment]
Thanks for reporting this! Looks like it is related to #439 . I'll look into a fix!
