### ISSUE TITLE
import_protein_local does not import frames

### ISSUE THREAD

**Issue by sokrypton** [BradyAJohnston/MolecularNodes#5]
I was trying to debug why my generated PDB files were not working and I think I tracked it down to the import_protein_local function.

If I try enter PDB code and download, all is good. 

But if I manually download, enter the location of pdb file, I get this error:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/4187522/165543938-7cbfce8a-e3e9-46d5-a07d-2d64ea7e9f66.png">

The frames are not imported.

Here is the pdb file I tried:
https://files.rcsb.org/view/7QIL.pdb

**Comment by sokrypton** [comment]
Solved it! Turns out I forgot to give the node a "Name"! 🤦

**Comment by BradyAJohnston** [comment]
Ooh thanks for this comment though! It shouldn't break if you don't input a name and should default to one instead. I will ensure to implement that :)

**Comment by BradyAJohnston** [comment]
Should be fixed in `0.3.8`
