### ISSUE TITLE
ChainID reading error (release 0.10.1)

### ISSUE THREAD

**Issue by ChenouZhang** [BradyAJohnston/MolecularNodes#51]
I'm learning the new selection feature and got a error when Molecular Nodes read my customized chainIDs. It seems to use the wrong ID on the wrong chain. 
For example, chain 'C' stands for chloride in my pdb, but it represents one of the protomer when Molecular Nodes read it.
![image](https://user-images.githubusercontent.com/42550849/179348035-2dde106b-7b0d-4b06-a59d-26d2c69f84e2.png)

The naming convention I used for chains is:
ProtomerA-'A',   ProtomerB-'B', lipids-'X', sodium-'S', chloride-'C'

I've attached the test file here. I changed the original file format from pdb to txt just to get it uploaded,
[NapA-test.txt](https://github.com/BradyAJohnston/MolecularNodes/files/9125439/NapA-test.txt)

**Comment by BradyAJohnston** [comment]
Thanks for the bug report! The chain numbers were off by 1 when importing via MDAnalysis and I hadn't noticed it, so I appreciate it!

Should now be fixed in latest release: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.10.2
