### ISSUE TITLE
pdb file doesn't import to M-Nodes

### ISSUE THREAD

**Issue by AlaaHuwaidi** [BradyAJohnston/MolecularNodes#53]
Hi Brady 

I am working with phospholipid bilayer it is downloaded from "http://www.fos.su.se/~sasha/SLipids/Downloads.html" in pdb format, when I am uploading it from my Desktop to M-Nodes it shows an error. could you try it by yourself and tell me what to do instead. 

Sincerely

**Comment by BradyAJohnston** [comment]
You might have to be more specific with which one is giving you an error. 

I have been able to load some of them with the local-file import, but there were errors with the detection of the elements. 

I was able to more successfully import some of the files via MDAnalysis using the 'MD Trajectory' import panel, and just choosing a file to be both the topology and the trajectory as below: 


![image](https://user-images.githubusercontent.com/36021261/179631786-c8b771a3-743f-431c-9362-fed6b1df158b.png)
