### ISSUE TITLE
Entity detection in trajectories with protein-ligand complexes

### ISSUE THREAD

**Issue by rabiakhd** [BradyAJohnston/MolecularNodes#533]
> Blender 4.1
> Molecular Nodes 4.1.4
> Windows 11
> 
> MD simulation software: Schrodinger Maestro
> Trajectory conversion form .cms to .dcd using VMD
> 
> topology and trajectory files: [https://miami.box.com/s/mdwiau38bho3dv635flszy3169602l9a]

**The ligand and solvent are grouped together and identified as one chain on MD import**
Automatic ligand detection from protein-ligand complexes inside trajectories will be awesome.

**Comment by BradyAJohnston** [comment]
This seems to be more an issue the topology. Looking at the data you sent, there are only two chains identified in the topology to begin with. 

```py
>>> np.unique(universe.atoms.chainIDs)
array(['A', 'X'], dtype=object)
```

There is potential to improve the ligand detection though - how would you extract ligand information from this trajectory currently?
