### ISSUE TITLE
Local file import does not work

### ISSUE THREAD

**Issue by JorikWaeterschoot** [BradyAJohnston/MolecularNodes#54]
Hi Brady,

Short question,
I am following the m-node toturial number two on youtube. But I am stuck at importing the ATP-synthase frames from my desktop, I have made them with chimeraX but when I try to upload them in blender via the local file window the open button does not become highlighted. Any idea how I could solve this issue?
<img width="316" alt="ATP-synthe" src="https://user-images.githubusercontent.com/109551648/179603638-7b2f75b9-5953-4ac7-ad9a-69b63ada3662.png">

Best,
Jorik

**Comment by BradyAJohnston** [comment]
Hi Jorik! 

Yes it's a little annoying, but blender doesn't like relative paths for opening files. The button will remain grayed out until blender successfully detects that the path exists, to stop you from getting an error when trying to open and it failling.

When selecting a file, you have to make sure you un-tick relative paths in the file browser (settings cog on the right, then un-tick). 

![](https://user-images.githubusercontent.com/36021261/169821803-aae1e977-8f0d-4f1c-896e-fb69ca52899b.png)

It's a little annoying that sometimes relative paths are used and sometimes not inside of Blender, but I've found that you just have to ensure that everything is absolute paths to be safe.

**Comment by JorikWaeterschoot** [comment]
Thank you this worked!!!!
