### ISSUE TITLE
PDB stays as black points after importing. No nodes being created upfront.

### ISSUE THREAD

**Issue by EnsTimm** [BradyAJohnston/MolecularNodes#55]
Hi Brady,

when I am importing a PDB and set up the Cycles render engine, the PDB file is displayed as black points. It seems that the nodes are not set up as in your YouTube video from the 30th of June. 

When I do set up the nodes, the model stays grey. When I do insert a ribbon node the model become a black flat shape. When I set up the surface node, the model disappears from the view point. 

Thanks so much for your work and the help!

Best regards
Timm

![Screenshot 2022-07-23 202855](https://user-images.githubusercontent.com/109872222/180618619-3545fa14-6e44-490f-85cc-0011a8a1026c.jpg)

![Screenshot 2](https://user-images.githubusercontent.com/109872222/180618620-d973a540-f885-4e19-b0e9-2a8bf26490a1.jpg)

![Screenshot 3](https://user-images.githubusercontent.com/109872222/180618621-08f54d87-3ca9-458d-a2a6-c41d19cbcd23.jpg)

**Comment by BradyAJohnston** [comment]
Hi @EnsTimm which version of Molecular Nodes & Blender are you using? If less than Blender 3.2 please upgrade as it won't properly on an earlier version. From looking at your screenshots, the atomic properties aren't set up properly. On the first node, select the '4nro_properties' collection and that should fix the setup of the atomic properties.

**Comment by EnsTimm** [comment]
Hi @BradyAJohnston 

I am using the latest version of Blender (3.2.1) and version 0.10.4 of molecular nodes. 

Best regards Timm

**Comment by BradyAJohnston** [comment]
Can you change your Blender to English and see if the issue resolves itself? Seems that non-english breaks the import currently (looking into fixing it).

**Comment by EnsTimm** [comment]
Switching Blender to English solved the problem. Thanks a lot for the help AND the awesome plug in!

**Comment by BradyAJohnston** [comment]
Glad to hear this is resolved! Flagging this as the same issue as in #29 and #41

**Comment by BradyAJohnston** [comment]
Now tracking in #63
