### ISSUE TITLE
Unable to load some PDB files

### ISSUE THREAD

**Issue by Mangkun-Chen** [BradyAJohnston/MolecularNodes#550]
I downloaded the file of the full-length spike protein, 6vxx, from this website and it failed to load via local read. I uploaded the file.

I have version 4.1 of blender, and MolecularNodes is also the latest version.

https://charmm-gui.org/?doc=archive&lib=covid19
[6vsb_1_1_2.zip](https://github.com/user-attachments/files/16250334/6vsb_1_1_2.zip)
![2024-07-16 222036](https://github.com/user-attachments/assets/77def6dd-98ee-4f8d-a085-7dfc438962f3)

**Comment by BradyAJohnston** [comment]
The `.pdb` files from CHARMM-GUI aren't formatted properly to the PDB spec. `biotite` which does the parsing underneath is _very particular_, and is throwing the error that you are seeing when trying to parse it.

Those `.pdb` files are intended to be topology files. You can import it via MDAnalysis if you set it as both the topology and the trajectory: 
![CleanShot 2024-07-16 at 19 20 03@2x](https://github.com/user-attachments/assets/09e87c05-1800-492a-ab44-fde78577c338)

**Comment by Mangkun-Chen** [comment]
However, previous versions of Molecular Nodes seemed to be able to be directly imported locally. I discovered this issue while imitating a video tutorial from 2022. The original author can import pdb files from CHARMM-GUI through Molecular Nodes.

**Comment by Mangkun-Chen** [comment]
I tried importing using MDAnalysis on another computer, but it also reported an error. Blender version is 4.0, Molecular Nodes version is 4.0.11

![Dingtalk_20240717113903](https://github.com/user-attachments/assets/89d3a31e-1643-45b3-a7bc-ae8071bbfffb)
![Dingtalk_20240717113919](https://github.com/user-attachments/assets/23081edd-dbed-4ec2-96b1-62d92c8a0e3d)

**Comment by BradyAJohnston** [comment]
The new error you are getting should be fixable by restarting Blender after installing MDAnalysis.

**Comment by Mangkun-Chen** [comment]
Thank you very much, it's okay now
