### ISSUE TITLE
Hydrogens not showing in sidechain selection

### ISSUE THREAD

**Issue by sfmvisuals** [BradyAJohnston/MolecularNodes#557]
**Describe the bug**
When I try to select for sidechains before inputting to a style node (i.e. Ball and Stick), the hydrogen atoms on the amino acid sidechains do not show.

**To Reproduce**
1. Load a PDB molecule.
2. Add  the node 'Style Ball and Stick'.
3. In the Geometry Nodes Editor, add  the node 'Is Side Chain'.
4. Connect the 'Is Side Chain' Selection option to Selection in the Style node.
5. Hydrogens are not included in Side Chain selection.

**Expected behavior**
I expected to see hydrogens since they should be a part of the sidechain!

**Error Codes**
Please include associated error codes that are shown in the python console when the error occurs.
> To view the python console on Windows, `Window` -> `Toggle System Console`, on Mac you must start Blender from the terminal.
```
# paste error codes from python console here
```

**Screenshots**
![Screenshot 2024-07-24 113004](https://github.com/user-attachments/assets/6e0757eb-a187-417a-9a35-6ed31a710ba9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Hardware:  x64 PC
 - Blender Version: 4.2
- MolecularNodes Version: 4.2.4

**Additional context**

**Comment by BradyAJohnston** [comment]
Thanks for reporting! Will address this in an upcoming version.
