### ISSUE TITLE
Store In Memory option for trajectories missing

### ISSUE THREAD

**Issue by davidkastner** [BradyAJohnston/MolecularNodes#564]
**Describe the bug**
I am using the newest version of molecular nodes with Blender 4.2 LTS installed using the new `Get Extensions`. However, it looks like the option to store MD frames "In Memory" is not there. I checked the release notes to see if it was removed intentionally but I didn't see it mentioned. It could have to do with the trajectories overhaul. When I move my trajectory data or the blender file, my animation stops working and gets stuck on the first frame. I need to render on a remote linux machine since my laptop is pretty old so I often have to move my blender files before rendering. For now, it looks like molecularnodes 4.1 works for me though.

<img width="469" alt="Screenshot 2024-08-07 at 4 28 24 PM" src="https://github.com/user-attachments/assets/e6d9e7a6-bc0d-44b7-a264-5e9aeea37bd5">

**Comment by BradyAJohnston** [comment]
Hi David - you are right in that it has currently been removed. Given the complexity of the refactoring I was doing for the trajectories - I dropped the support for loading into the .blend file / memory. I thought this would be simpler and more performant for everyone. 

I have just tested and can confirm that if any of the paths change, even if I move a folder that contains the .blend file and the trajectories inside of it, that the connection to the trajectory breaks.

This is a pretty major bug that I should be able to hopefully resolve for the live trajectory. Whether I add back the in-memory option I am unsure, as performance wise the streaming is much better, but there are are potential creative things that could be done inside of Geometry Nodes if all of the frames are in memory.

A question - are you just interested in the in-memory option for this remote rendering possibility, or are you wanting it for other things also?

**Comment by davidkastner** [comment]
Thank you for the quick response! I was only using the in memory option to allow me to move my blender file around. If the blender file used relative paths to the MD trajectory, or another way, that would also work great for me! As long as I can prepare a blender job on my laptop and then render it on a remote GPU, then that works perfectly. Oh but would that cause issues since MDAnalysis would need to be installed on the remote machine as well?

**Comment by BradyAJohnston** [comment]
It would mean that the remote machine would also require Molecular Nodes to be installed (which comes with MDAnalysis).

Will have a poke around to try and get something working.

**Comment by BradyAJohnston** [comment]
I've a fix working in #566 but the tests are failing on Linux so I'll need to investigate further.

**Comment by BradyAJohnston** [comment]
This should now be fixed in 4.2.5 which can be installed from the extensions website / updated from within Blender. 

Please let me know if it doesn't properly resolve the issue.

**Comment by davidkastner** [comment]
Thank you for taking a look! I'll give it a try.
