### ISSUE TITLE
Materials field in Mol_DNA_bases is empty

### ISSUE THREAD

**Issue by ABanny** [BradyAJohnston/MolecularNodes#57]
Hi, 

I think I am facing an issue with the Material field in the MOL_DNA_bases. The field on your video tutorial has something, but on my end, the field is empty. Any idea how to get that?  

![image](https://user-images.githubusercontent.com/62797550/181020389-4ed74b12-4f2b-42a1-86a2-da0c29b5211f.png)

I have attached the image from my end for you reference.

**Comment by BradyAJohnston** [comment]
Ah yes the material doesn't auto setup when adding just the DNA bases. That's something that it should do, for convenience without you having to import a protein first - thanks for pointing it out!
