### ISSUE TITLE
Formatting issues of the PDB file 

### ISSUE THREAD

**Issue by hanjiahe1999** [BradyAJohnston/MolecularNodes#576]
I succeed to use the MolecularNodes to show the 4ozs.pdb in blender, it is so awesome !!!!!
Then, I want to be take my file in the MolecularNodes, it seems to meet some problems and PDB file have something wrong.
there is my PDB file, 
[alal2o3300.zip](https://github.com/user-attachments/files/16601981/alal2o3300.zip)
it contain  Al and Al2O3.  

Did you have some suggestions to solve this problem? I would appreicate it

**Comment by BradyAJohnston** [comment]
Looking at the pdb file, you are correct that it is not formatted correctly.

```
HETATM    1 Al1                  1.914  25.569  31.678  1.00 -0.00          Al
HETATM    2 Al2                  0.642  19.098  37.562  1.00 -0.00          Al
HETATM    3 O1                   1.765  18.543  36.306  1.00 -0.00           O
HETATM    4 Al3                  0.529  21.643  37.427  1.00 -0.00          Al
HETATM    5 Al4                  4.113  23.837  33.041  1.00 -0.00          Al
HETATM    6 O2                   1.641  23.090  37.334  1.00 -0.00           O
HETATM    7 O3                   1.694  20.477  38.169  1.00 -0.00           O
```

When attempting to parse the file, it is complaining about not having a number for the residue.

If you open it inside of pymol and then save it as a `.pdb`, it will re-save the file and be able to be parsed by MN. 

This is something that could potentially be improved and relaxed during parsing.
