### ISSUE TITLE
Relative path fails for opening local file

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#577]
If opening local file, the relative paths fail to be parsed. This was fixed for MD simulation paths but hasn't been fixed for local PDB paths.

**Comment by hanjiahe1999** [comment]
if I only have xyzfile，could i use the MolecularNodes？

**Comment by BradyAJohnston** [comment]
@hanjiahe1999 not currently. You can convert an `.xyz` to a `.pdb` or `.mol` and import that though. Please also try to keep discussion in particular topics limited to that topic, if you have questions you can open a new issue.
