### ISSUE TITLE
Can't interpolate .xtc trajectory with animation node. (No frames collection)

### ISSUE THREAD

**Issue by CeraveWasTakenLOL** [BradyAJohnston/MolecularNodes#582]
**Is your feature request related to a problem? Please describe.**
I am unable to use the animation nodes to interpolate/smoothen between frames in .xtc. 
I suspect this is because the animate frames node is designed only to work with multi-frame PDB files.

**Describe the solution you'd like**
I would like to be able to smoothen .xtc trajectory files 

**Describe alternatives you've considered**
I tried to use gromacs to convert over to a multi-frame pdb file and import that but still no frames collection even with multi-frame pdb topology.
Also tried just uploading the multi-frame pdb directly through atomic blender but blender and my computer cannot handle this

**Additional context**
Here's a link to my trajectory files: (see the fam_bicelle.xtc for trajectory and fam_bicelle.gro for topology)
https://github.com/bio-phys/MemCurv

**Comment by BradyAJohnston** [comment]
Which version of Molecular Nodes are you using? In the later versions (4.2) the reading of trajectory files and updating of positions are handled my MDAnalysis under the hood. There is now an option during playback for subframes to be added, that will interpolate between positions, slightly smoothing the trajectory playback (as in this example below).

https://github.com/user-attachments/assets/3d480aed-ede3-4796-9dfd-728cfbdcef2d

Is this what you are after?

**Comment by CeraveWasTakenLOL** [comment]
Subframes was exactly what I was after! Thank you!!
