### ISSUE TITLE
b_factors the same across all frames?

### ISSUE THREAD

**Issue by sokrypton** [BradyAJohnston/MolecularNodes#6]
From what I can gather, the same b_factor (from model 1) is used for all animation frames.

**Comment by BradyAJohnston** [comment]
Currently the addon only imports properties from the first frame of the animation - as in theory they should all stay the same (AA number, element etc). But this is a good point that B-factor would not stay static, and so I should be able to add this in.

**Comment by BradyAJohnston** [comment]
Should now be fixed and available in the latest release: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.4.1
