### ISSUE TITLE
open files using molecular nodes

### ISSUE THREAD

**Issue by jonbind** [BradyAJohnston/MolecularNodes#60]
Hi Brady
first of all thanks for the great work !

I installed Molecular Nodes on Kubuntu (22.10) with Blender 3.2 and Python3.10. I realized, that you cant import files unless they are in the same folder as your blender project.
![different_folder](https://user-images.githubusercontent.com/89415196/183605590-2d9ccfc5-d403-42cc-b411-8fa1785896b0.png)
![Same_folder](https://user-images.githubusercontent.com/89415196/183605597-f6592ad1-f186-4c1b-bf89-cd2f990b9c2f.png)

**Comment by BradyAJohnston** [comment]
It's an issue with relative path imports (Blender doesn't like them, but it seems to try and use them a bunch of times). 

See #54 but it should just be a matter of unticking relative imports when trying.

**Comment by jonbind** [comment]
Sorry didnt realized this open issue existed. Fixed it for me !

**Comment by BradyAJohnston** [comment]
All good, the issue wasn't open. I'll leave this open though because I really need to try and track fix this because it's quite the stumbling block.

**Comment by BradyAJohnston** [comment]
Now tracking in #64
