### ISSUE TITLE
How to change the radius of each element?

### ISSUE THREAD

**Issue by hanjiahe1999** [BradyAJohnston/MolecularNodes#602]
In the MNs，We can define the color of each element ourselves, but could we define the radius of the different atom? I hope the distinction between the two elements is very high. 

You may have thought of it, but I can't find any relevant tutorials. I hope you can help me.

**Comment by rbdavid** [comment]
The default sphere VDW radii are set in the ``molcularnodes/data.py::elements`` dictionary (see issue #468 ). If you are comfortable with editing that file, you could hard-code the radius values for all atoms in your system. 

If you want to emphasize a small set of atoms via changing their radii, you can alter your geometry nodes setup to select the subset of atoms and use a different radius scale value relative to the rest of the atoms'. I'm imagining you are using the `Style Spheres` geonode, which has the `Radii` slider. Use two or more of those style nodes each with its own selection geonode to control how atoms' spheres are drawn.

**Comment by BradyAJohnston** [comment]
@rbdavid mentioned if you wanted to change the hardcoded values, but here are some examples of how you might approach it inside of the nodes. The relevant attribute is the `vdw_radii` attribute, which you can write a new value two, or change the scaling factor applied on the spheres.

The method with the most control is the `Index Switch` node, which you can use the `atomic_number` attribute to set a new value for each element if you wish.

![image](https://github.com/user-attachments/assets/42d0460e-475c-4829-975a-ff9e6bab0030)
![image](https://github.com/user-attachments/assets/63aa6ac5-4b62-4e49-aa88-5de5071d0c3f)
![image](https://github.com/user-attachments/assets/d8fa6743-c848-4476-ba1e-999ccb12cb7b)
