### ISSUE TITLE
Cannot install Atomium

### ISSUE THREAD

**Issue by ChiragSharma6283** [BradyAJohnston/MolecularNodes#61]
cannot use the install Atomium click to install 
<img width="518" alt="Screenshot 2022-08-14 at 8 08 22 AM" src="https://user-images.githubusercontent.com/111210668/184520170-fd72ea1b-1dcb-4a9b-aefe-1cde35d00170.png">
)

**Comment by ChiragSharma6283** [comment]
click on check box does add this but not all options like in the video to put search to appears

<img width="518" alt="Screenshot 2022-08-14 at 8 17 06 AM" src="https://user-images.githubusercontent.com/111210668/184520331-088cdaa9-dc10-4bda-b5cc-88edc520cd98.png">

**Comment by BradyAJohnston** [comment]
Are you able to provide more details? I can't really help without details. What is your computer, what operating system are you using, are there any particular errors that are showing up when you are attempting to install? From what you have sent so far I don't know what the issue could be, but with more details I might be able to help

**Comment by BradyAJohnston** [comment]
Additionally, what version of Blender are you using?

**Comment by ChiragSharma6283** [comment]
Hi Brady! 
so I am use a Mac air (Mac OS) there are not errors showing up it is just that when click on the check box there should be a popup of Install Atomium, it is not there! what it leads to is creation of toggle bar with PDB showing but cannot use it,
and I am using 3.2.2 ver of Blender!
Thanks!

**Comment by ChiragSharma6283** [comment]
see there is just no Install Atomium button to click on after marking checkbox.

<img width="518" alt="Screenshot 2022-08-14 at 2 43 40 PM" src="https://user-images.githubusercontent.com/111210668/184530349-701f7282-9ced-4081-a766-a8dc30b0716a.png">

**Comment by BradyAJohnston** [comment]
I tried on my MacOS 2017 Macbook Pro and I wasn't able to replicate this issue, it seems to install without issue. 

Can you try reinstalling Blender and reinstalling Molecular Nodes?

Do you have Blender set to another language other than English? There have been some issues with the python API in non-english Blender settings (see #55 )

**Comment by ChiragSharma6283** [comment]
Downloaded both files again and installed, checked language - set to English not sure if there is some other setting where language needs to be turned to English, but let me know if this is correct and if it is correct then what are my options?
<img width="518" alt="Screenshot 2022-08-15 at 6 43 29 AM" src="https://user-images.githubusercontent.com/111210668/184562614-7b187105-204e-4b5a-bf13-b553c0e1c19b.png">

**Comment by BradyAJohnston** [comment]
I am honestly not sure. I haven't seen this error before and there is nothing obvious that I can think of. 

As you are on MacOS, can you do the following steps:

1. Uninstall Molecular Nodes
2. Start Blender via the terminal (should just be running `blender` in the terminal)
```bash
blender
```
3. Try install & enabling the Molecular Nodes addon. If there are errors, they should show up inside of the terminal window. Can you please send any errors that appear in the terminal window.

**Comment by ChiragSharma6283** [comment]
Hey Brady!
Tried starting Blender via Terminal window, did run the whole process 2 times here is what the terminal window showed error of 
<img width="520" alt="Screenshot 2022-08-15 at 10 18 13 PM" src="https://user-images.githubusercontent.com/111210668/184678854-06702b48-edc0-4dee-9de6-2523121c7eec.png">
<img width="520" alt="Screenshot 2022-08-15 at 10 21 21 PM" src="https://user-images.githubusercontent.com/111210668/184679637-5f7ea5e3-7439-4f4d-87bf-ce5e6f0a8995.png">

**Comment by BradyAJohnston** [comment]
It looks like you may have several copies of the addon installed which might be why it is breaking. 

Can you try uninstalling & removing molecular nodes, close Blender. Delete all of the downloaded versions of Molecular Nodes in your `~/Downloads` folder.

Navigate to the following path: 
```
/Users/akritisharm/Library/Application Support/Blender/3.2/scripts/addons/
```

Remove all of the folders that are there. Likely will only be `molecular_nodes` but remove any folders just to be sure.

Try booting blender from the terminal again using `blender`, downloading the latest Molecular Nodes from the [releases page](https://github.com/BradyAJohnston/MolecularNodes/releases), and installing it to see if that fixes the problem.

**Comment by ChiragSharma6283** [comment]
It worked!!⚡️ Thanks!!

<img width="520" alt="Screenshot 2022-08-16 at 10 35 10 AM" src="https://user-images.githubusercontent.com/111210668/184801999-66ef6db6-2e5e-44be-b7d7-808fd4ab17d0.png">

**Comment by BradyAJohnston** [comment]
This is great news! Glad it has resolved.
