### ISSUE TITLE
Cartoon node "Quality" input doesn't update Loop resolution MN 4.2.6

### ISSUE THREAD

**Issue by julioarvellos** [BradyAJohnston/MolecularNodes#613]
**Describe the bug**
I just noticed that the Quality option from Cartoon node does not update the resolution of the loops. I figured out what happened and  the socket "Loop Resolution" (from inside the Cartoon node) isn't plugged to the "Curve Custom Profile" inside ".CA to loops" node.

 - Blender Version: Blender 4.2.1
- MolecularNodes Version: MN 4.2.6

https://github.com/user-attachments/assets/6fc31eab-79e3-4132-9684-59c09ff18717

**Comment by BradyAJohnston** [comment]
Ah thanks for catching this! I went through and refactored a bunch of stuff and miss that component :)
