### ISSUE TITLE
MNSession File System Is Bugged

### ISSUE THREAD

**Issue by CeraveWasTakenLOL** [BradyAJohnston/MolecularNodes#614]
**Is your feature request related to a problem? Please describe.**
Everytime blender crashes or closes I lose my trajectory and have to re-import. 

**Describe the solution you'd like**
I would like to be able to cache to my disk so that I can use the same object if I need to close the app or if it craches

**Comment by CeraveWasTakenLOL** [comment]
i literally just lost two full days of work because the blend file won't re-open the trajectory i have to recache everything form scratch

**Comment by CeraveWasTakenLOL** [comment]
i have so many keyframes and nested parenting i can't just reopen fueverythiung i  lost everyting

**Comment by BradyAJohnston** [comment]
Hi @CeraveWasTakenLOL, can you please provide more of the requested information so I can potentially help. OS, Blender version, MN version would all be helpful. 

When you save, exit then reopen a file MN should reload the session that was previously running - this is still a bit fragile with some edge cases so if you could give more details around error messages that print to the console, what was setup when the save & load wasn't working and maybe even test files that reliably reproduce the error I can try and help to debug it.

Regardless of the previous errors, it is also possible to reload a trajectory into a new object, then link the underlying data to the old object that contains all of the keyframe information. Again, if I know more about what kind of errors specifically you are getting I can potentially help more.

**Comment by CeraveWasTakenLOL** [comment]
macOS Ventura Blender 4.2 molecularnodes-4.2.4-macos_arm64

There are no error messages just the object doesn't move. I can recall maybe two times where Blender crashed or closed and I opened the blend without having to re-import to a new object. 

But when I make many modifications to the geonodes with tons of parented transformations and keyframes in the geonodes it is a very painful headache to re-import with on a new object and line it up by eye. 

The MNSession file system is extremely flawed.

This is what killed two days of rendering:
![Screenshot 2024-09-21 at 14 56 20](https://github.com/user-attachments/assets/71b5aa9a-8c0b-4f2e-9d25-d510895297bf)


File size is 91 KB. Basically if the script is saving a MNSession file that is 91 KB it is killing itself

**Comment by CeraveWasTakenLOL** [comment]
![Screenshot 2024-09-21 at 14 59 03](https://github.com/user-attachments/assets/f9e8721b-c4aa-4fbb-b77c-e68bdecabaab)

**Comment by CeraveWasTakenLOL** [comment]
[mol9reimport.blend.MNSession.txt](https://github.com/user-attachments/files/17085566/mol9reimport.blend.MNSession.txt)
it says reimport but its dead. I literally watched blender kill it while I was resaving it

**Comment by CeraveWasTakenLOL** [comment]
If it is too hard to fix the bad data @BradyAJohnston Is there a way we can add a button that saves a dedicated MNSession file so that if something goes wrong with the default one like it overwrites with bad data we can recover from the (locked) back up?

**Comment by BradyAJohnston** [comment]
The `*.MNSession` file is a binary pickled file, so opening it inside of a text editor won't be of any use to you, that's why it looks corrupted / gibberish. 

If you can launch Blender from the terminal, `/Applications/Blender.app/Contents/MacOS/Blender` then you can see any error messages that print to the console when attempting to load the file which might be of help, as trying to open / inspect the `.MNSession` won't currently help us.

As a temporary quick fix, you can load a new object that will be linked to the Universe in question, and then re-use the mesh data on your old keyframed object. You can disable the visibility of the new object, but the updating data will still be used for the old object and this should be a temporary quick fix. Obviously this isn't an ideal way of recovering the session, but this should return you to where you were before the link to the universe was lost.

https://github.com/user-attachments/assets/80b0590a-0c0f-4984-9aeb-eb9381760573

**Comment by BradyAJohnston** [comment]
I have just created a PR that adds an operator for the Object, to quickly reload a universe from the filepaths for the trajectory / topology without having to import a new object: #616

**Comment by CeraveWasTakenLOL** [comment]
Awesome!

**Comment by BradyAJohnston** [comment]
The updated add-on is now uploaded to the Blender extensions website, so you should hopefully be able to update the add-on and then be able to reload the universe with new functionality. Please do give any feedback for it.

**Comment by CeraveWasTakenLOL** [comment]
Sorry for the late reply I was able to update and save my project thank you!

**Comment by BradyAJohnston** [comment]
@CeraveWasTakenLOL glad it's all working again - apologies about the trouble!

**Comment by CeraveWasTakenLOL** [comment]
@BradyAJohnston No worries at all! It's amazing what you've built and the effort you put into it
