### ISSUE TITLE
Some Nodes missing Soft Limits

### ISSUE THREAD

**Issue by julioarvellos** [BradyAJohnston/MolecularNodes#618]
I accidentally noticed (after a crash) that some nodes have a resolution or quality input with no soft limits. I checked all the nodes from following categories:

**Style**
- [x] Surface > Relaxation Steps
- [x] Ball and Stick > Quality

**Geometry**
- [x] Primitive Arrow > Vertices
- [x] Primitive Gimbal > Vertices

**DNA**
- [x]  Style Ball and Stick > Bond Resolution
- [x] Style Ball and Stick > Double Bond Resolution

**Density**
- [x] Density Wire > Resolution

I didn't check all other categories, because I rarely use them, but I'll report if I find anything else.

**Comment by BradyAJohnston** [comment]
Thanks for finding these! Getting everything more consistent across the nodes is a goal so I'll be sure to update them :)

**Comment by BradyAJohnston** [comment]
Also this kind of feedback on node UI is very much appreciated - please do keep it coming!!
