### ISSUE TITLE
Different Material

### ISSUE THREAD

**Issue by hanjiahe1999** [BradyAJohnston/MolecularNodes#622]
Hello Brady!
I want to render some PBD file using MNs ,but I meet some problemswhen I want to set different materials in different element. If you modify a material, it will modify it all. Sincerely ask you to help me！！

**Describe the bug**
there is my Nodes
![20240925-105843](https://github.com/user-attachments/assets/24556f30-1dac-4fc6-943c-0bdc09638cf5)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Blender Version: 4.2.0

**Comment by hanjiahe1999** [comment]
how can I modify this Nodes

**Comment by BradyAJohnston** [comment]
This video should cover most of what you are after: https://www.youtube.com/watch?v=dqdwS-TvsnM

**Comment by hanjiahe1999** [comment]
I have watched this video before, and it seems to be unable to help me. Is there a good suggestion?

**Comment by hanjiahe1999** [comment]
> This video should cover most of what you are after: https://www.youtube.com/watch?v=dqdwS-TvsnM

I have watched this video before, and it seems to be unable to help me. Is there a good suggestion?

**Comment by BradyAJohnston** [comment]
I am not entirely sure what you you are wanting to do. If you want different materials for different elements, you have the right setup, you just need to select a different material for each of the `Style Ball and Stick` nodes - currently they are all using the same material.

**Comment by hanjiahe1999** [comment]
I set two material, but it doesn't work
![img_v3_02f2_2a792d52-6f61-4979-ba62-70d532d2ee0g](https://github.com/user-attachments/assets/f521d106-143b-404e-b45f-fdc8f58dd074)

![image](https://github.com/user-attachments/assets/0fe8cda0-7763-4bda-9caa-209cf7faf4b2)

**Comment by hanjiahe1999** [comment]
in this video, You mentioned that point clouds cannot have two materials set

**Comment by BradyAJohnston** [comment]
in the same video I also provide an answer how to vary the shader on a single point cloud as well (using the `Attribute` node inside of the material, you can access any attribute such as a selection to mix shaders while keeping a single material)

**Comment by hanjiahe1999** [comment]
I have set the styple Spheres and set a new material in the shader Editor. but it didn't work

**Comment by hanjiahe1999** [comment]
okok，I realized the problem！！did you have any better suggestion to beautify the structure？
![img_v3_02f2_d73607f8-e3a1-4b6b-95f9-407c16402d9g](https://github.com/user-attachments/assets/90f32230-4b35-49fa-a32e-fb43a57c27ab)
![img_v3_02f2_ee086b1d-53b0-4c91-98f2-e635ad9481dg](https://github.com/user-attachments/assets/e48f4f2f-1524-4064-acd4-0eea33413176)

**Comment by BradyAJohnston** [comment]
For aesthetics I recommend looking at 'Luminous Labs' tutorials on youtube, they have great material and lighting tips.

**Comment by hanjiahe1999** [comment]
thank you for your reply！！！
