### ISSUE TITLE
Error installing Molecular Nodes: missing biotite module

### ISSUE THREAD

**Issue by giovanna-deluca** [BradyAJohnston/MolecularNodes#629]
Hi Brady!

When trying to install Molecular Nodes addon I get the following message:
"Report: Error
No module named 'biotite.structure.bonds' "
and the addon is not enabled.

**Steps to reproduce the behavior:**
1. Go to Blender menu Edit/Preferences/Get Extension
2. Scroll down to 'Molecular Nodes'
3. Click on 'Install'
5. See error

**Expected behavior**
No error message.

**PC Desktop:**
 - OS: Linux Manjaro
 - Hardware: AMD Ryzen 9
 - Blender Version: 4.2.1
- MolecularNodes Version: 4.2.7

**Additional context**
After installing the addon, I imported biotite in the blender python console, and run biotite.__version__ command, obtaining '0.41.2' value.

Hope this helps, and thank you very much for your work!

All the best,
Giovanna

**Comment by BradyAJohnston** [comment]
I don't have a linux machine to try and reproduce this on - but I'm guessing the build for this particular linux is being strange for whatever reason. 

Can you try and import the problematic submodule, similar to how you imported biotite for the version number?

Are you able to post more of the error message? I'm not directly importing the bonds submodule in the add-on, so I am curious as to where this is failing when initiating.

**Comment by giovanna-deluca** [comment]
So...

Just to be clear, I do not know how to install a specific Python module inside Blender. I could import Biotite only after installing your add-on.
Importing the problematic module still gave the same error, which, in my hands, is nothing more than the following:
"Report: Error
No module named 'biotite.structure.bonds' "

Anyways, your hint was effective.
I noticed that the Python console in Blender was version 3.12.5, the current Python version in Manjaro.
After some investigation, I noticed that the modules you used were for Python 3.11.
Thus, I:
- installed the Flatpak version of Blender
- verified that it used Python 3.11.7
- successfully installed Molecular Nodes!

Arch Linux-based distributions are sooo eager to include all novelties. Too much, sometimes.

Thanks for your suggestion!
Giovanna

**Comment by BradyAJohnston** [comment]
Ah yes, Blender is very particular with python versions and I have seen countless issues with users on Linux running into problems with system python / Blender python. Good to know and I'll try to remember this for next time! Thanks for the followup info

**Comment by melomcr** [comment]
I can confirm the same issue and similar solution with Fedora 40.

Installing Blender version 4.2.2 gave me the exact same error message and behavior (no Molecular Nodes drop down menu under "Scene").

Installing Blender through the Snap store (version 4.2.3 LTS) allows the Molecular Nodes module to be installed with no errors and shows the menu under `Scene`.

**Comment by BradyAJohnston** [comment]
Thanks for the additional confirmation @melomcr 

I'm re-opening this as I should add something to the documentation about it. I don't usually work on a Linux machine, would @melomcr or @giovanna-deluca want to provide a short writeup that I can include in the installation instructions?

**Comment by melomcr** [comment]
Absolutely, I can create a pull request with suggested text. Or just send it here or PM if you prefer.

**Comment by BradyAJohnston** [comment]
PR would be great :)
