### ISSUE TITLE
Add ability to animate secondary structures of a RNA molecule

### ISSUE THREAD

**Issue by sutyum** [BradyAJohnston/MolecularNodes#65]
It would great to be able to animate Molecular Beacons, or RNA molecules that fold to form their secondary structures. Would be great to visualize this for sensing applications.

If you could provide some pointers, perhaps I could try to figure it out and contribute. I have no prior experience with geometry nodes.

**Comment by BradyAJohnston** [comment]
Hi @sutyum thanks for the suggestion! A good place to start would be with my tutorials on how to make DNA in geometry nodes: https://www.youtube.com/watch?v=m7bTEABoAzo

In that tutorial series, I make DNA, but you can just drop one of the strands to do RNA potentially.
