### ISSUE TITLE
Unable to import Molecular nodes

### ISSUE THREAD

**Issue by universvm** [BradyAJohnston/MolecularNodes#651]
Hi there, 

Sorry if this is a dumb question but I'm fairly new to blender. I've installed the plugin and made my first render. However, I would like to automate this with a python script to download and generate several images of a different proteins.

However, I'm sure I'm doing something wrong:

**Describe the bug**

When I move to the "Scripting" tab and simply type:

```
import MolecularNodes as mn

Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'MolecularNodes'
```

**To Reproduce**
See above

**Expected behavior**
No error

**Error Codes**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Hardware: ARM Mac
 - Blender Version: 4.2.3
- MolecularNodes Version: 4.2.7

**Additional context**

**Comment by BradyAJohnston** [comment]
For the 4.2 update, Blender changed how add-ons are imported. Currently you can import molecularnodes like this:

```py
from bl_ext.user_default import molecularnodes as mn

mn.entities.fetch("8H1B", style="cartoon", centre="centroid")
```

The python API should not be considered stable, as it is something that is still being developed and is evolving (and isn't well documented because of this), but I welcome feedback and suggestions on how you would like this to work.

**Comment by universvm** [comment]
> For the 4.2 update, Blender changed how add-ons are imported. Currently you can import molecularnodes like this:
> 
> ```python
> from bl_ext.user_default import molecularnodes as mn
> 
> mn.entities.fetch("8H1B", style="cartoon", centre="centroid")
> ```
> 
> The python API should not be considered stable, as it is something that is still being developed and is evolving (and isn't well documented because of this), but I welcome feedback and suggestions on how you would like this to work.

Hi there, thanks for your reply, I'd be more than happy to help with the python interface. I've been getting these weird errors though:

```python
import bpy
from bl_ext.user_default import molecularnodes as mn

mn.entities.fetch("8H1B", style="cartoon", centre="centroid")
```

```
Traceback (most recent call last):
  File "/Users/leo/Desktop/prova.py", line 22, in <module>
    mn.entities.fetch("8H1B", style="cartoon", centre="centroid")
  File "/Users/leo/Library/Application Support/Blender/4.2/extensions/user_default/molecularnodes/entities/molecule/ui.py", line 65, in fetch
    mol = parse(file_path)
          ^^^^^^^^^^^^^^^^
  File "/Users/leo/Library/Application Support/Blender/4.2/extensions/user_default/molecularnodes/entities/molecule/ui.py", line 39, in parse
    molecule = parser[suffix](filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leo/Library/Application Support/Blender/4.2/extensions/user_default/molecularnodes/entities/molecule/pdbx.py", line 270, in __init__
    super().__init__(file_path)
  File "/Users/leo/Library/Application Support/Blender/4.2/extensions/user_default/molecularnodes/entities/molecule/pdbx.py", line 13, in __init__
    super().__init__(file_path=file_path)
  File "/Users/leo/Library/Application Support/Blender/4.2/extensions/user_default/molecularnodes/entities/molecule/molecule.py", line 67, in __init__
    bpy.context.scene.MNSession.molecules[self.uuid] = self
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'MNSession'
[1]    42276 segmentation fault  python prova.py
```

**Comment by BradyAJohnston** [comment]
Ensure you have the add-on enabled for this to work

**Comment by BradyAJohnston** [comment]
I haven't seen this error before, but it might be that the add-on is disabled in Blender preferences?

**Comment by universvm** [comment]
> I haven't seen this error before, but it might be that the add-on is disabled in Blender preferences?

Ah! Seems like within blender this works. However, if I create a conda environment with blender and Molecular Nodes I get that error. 

A way around it is simply to use:

```bash
blender -b --python /Users/leo/Desktop/prova.py
```

Here's a pretty protein
![1qys_render](https://github.com/user-attachments/assets/94f84ac6-be91-4d16-81c2-0909cd9f04a2)

**Comment by BradyAJohnston** [comment]
Ah yes it'll currently need to be executed by Blender to work properly. This is something that can be improved upon though, as I can skip the step that is currently failing when we are not in Blender to begin with. 

Glad to see it's working! Please do keep me update

**Comment by universvm** [comment]
> Ah yes it'll currently need to be executed by Blender to work properly. This is something that can be improved upon though, as I can skip the step that is currently failing when we are not in Blender to begin with.
> 
> Glad to see it's working! Please do keep me update

Ofc I'll keep you up to date with this :)
