### ISSUE TITLE
Syntax error in __init__.py of v12.0.1

### ISSUE THREAD

**Issue by bloyal** [BradyAJohnston/MolecularNodes#68]
Line 37 of the __init__.py file for contained in molecular_nodes_0.12.1.zip has a "\" at the end that throws a syntax error when trying to enable the Molecular Nodes plugin in Blender.

I'm on an M1 Macbook Air running Monterey, Blender v3.2.2

**Comment by BradyAJohnston** [comment]
Ah thank you for picking this up! Should now be fixed in the latest release: https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.12.2
