### ISSUE TITLE
0.12.1 version cannot be opened

### ISSUE THREAD

**Issue by Mangkun-Chen** [BradyAJohnston/MolecularNodes#69]
![image](https://user-images.githubusercontent.com/108992267/188527169-e6859640-f11c-4627-9b60-08cd23a715d3.png)
![image](https://user-images.githubusercontent.com/108992267/188527208-e197eb9f-e0de-4996-bc1e-310d36af30a2.png)

Hello, Brady

I can't enable this add-on after I update to version 0.12.1.
The problem code is shown in the screenshot. Do you know what this means?

**Comment by Mangkun-Chen** [comment]
I just saw version 0.12.2.  it's ok now

**Comment by BradyAJohnston** [comment]
Yep sorry about that, glad it's all fixed now! I'll leave this issue open for a little bit to help anyone who might be running into the same issue.

**Comment by zhaozhao-ma** [comment]
> I just saw version 0.12.2. it's ok now

Hello, I'm in China, I want to install this plugin, but can't install it can teach me

**Comment by Mangkun-Chen** [comment]
> > I just saw version 0.12.2. it's ok now
> 
> Hello, I'm in China, I want to install this plugin, but can't install it can teach me

你把默认语言先改成英语。我之前提交过这个错误。
