### ISSUE TITLE
Demo blender project / video?

### ISSUE THREAD

**Issue by LunarLanding** [BradyAJohnston/MolecularNodes#7]
Hi, I'm a newcomer to blender and I must have misread something in the tutorial.
A video with all the steps starting from a blank blender project or even the project files for a simple animation would be helpful to people like me who are new to blender.

**Comment by BradyAJohnston** [comment]
Yep I plan on making some videos doing a tutorial on how to use the addon with Blender. 

I do already have some introductory videos on how to use Blender, aimed at biochemists: https://www.youtube.com/c/bradyjohnston

Also check out CGFigures: https://www.youtube.com/channel/UCk1jnnmyARHbP9nfEWUuyhQ
And Lumnous labs: https://www.youtube.com/channel/UCdlT39IRsIP0CTi-dxJLsRg

They will be enough to get you familiar with Blender. 

There will be a tutorial video in the future for the adodn, but currently I am focusing on beta testing, fixing bugs and making it more stable before announcing more widely :)

**Comment by BradyAJohnston** [comment]
Someone has already made a video doing a introduction to the addon, so here is probably also a good place to start: https://www.youtube.com/watch?v=8pbexyLwX9A

**Comment by LunarLanding** [comment]
Thanks! following that video made me confident that I was following the same setup, and still getting an issue, so I knew the issue was something else, and found out I was on blender 3.0 instead of 3.1.2.
I'm leaving the issue open for closing when a tutorial video is done, but happy I fixed my issue.

**Comment by BradyAJohnston** [comment]
Excellent, glad that it all worked out! I haven't really tested it on earlier blender versions (I know <`3.0` will definitely break) so it's good to know that things don't work well. I'll specify the version requirements in the addon, and will be sure to keep working on tutorial videos!

**Comment by BradyAJohnston** [comment]
![image](https://user-images.githubusercontent.com/36021261/176898770-ebaf9e49-f3b1-4d15-a84a-fb837975174f.png)

I have now also started to make some tutorial videos going through some of the nodes also!: 
https://www.youtube.com/watch?v=CvmFaRVmZRU
