### ISSUE TITLE
atomium installation failed

### ISSUE THREAD

**Issue by zhaozhao-ma** [BradyAJohnston/MolecularNodes#70]
Brady Johnston    My Blender is 3.2.2 and the downloaded nodal version is 12.2. I tried several times but couldn't install atoms
![问题](https://user-images.githubusercontent.com/114054606/191434943-76ee8429-8d9f-4ede-b158-373cb38cbdbe.png)
![问题1](https://user-images.githubusercontent.com/114054606/191434952-f3993e97-adbd-4e59-8a97-7486e70fad30.png)

**Comment by BradyAJohnston** [comment]
Seems like it is networking issue, that is blocking `pip` from being able to download `atomium`. Do you have some kind of firewall enabled? Are you able to use `pip` to download on an external python installation?

**Comment by zhaozhao-ma** [comment]
Thank you, I turned off the firewall and gave it a try

**Comment by zhaozhao-ma** [comment]
Brady Johnston   I can use pin to download an external python installation

**Comment by zhaozhao-ma** [comment]
Brady Johnston   This is a new problem
![问题1](https://user-images.githubusercontent.com/114054606/191449908-25af1b20-872f-4b0c-9e9e-17a49430ec28.png)

**Comment by BradyAJohnston** [comment]
Can you try switching your Blender to English? That has some resolved some issues that others have been having #63

**Comment by BradyAJohnston** [comment]
I don't know what the issue could be. It still seems like there is a network issue, which I can't really help with as it's outside the realm of Molecular Nodes.
