### ISSUE TITLE
Biological assembly falls apart when moving to origin

### ISSUE THREAD

**Issue by SanderEwen** [BradyAJohnston/MolecularNodes#71]
Hi Brady,

When applying the biological assembly node after opening a PDB, it is made neat but is not in the origin of the coordinate system. When I use the center selection node (or set geometry to origin), the assembly is moved to the origin but the asymmetric units fall apart (as if it were being scaled). I'm using MN v 0.13.

Could this be a bug or am I doing something wrong?

Cheers,

Sander

**Comment by BradyAJohnston** [comment]
Are you able to share the PDB code that this is happening with? So that I can investigate?

**Comment by SanderEwen** [comment]
7R5K and 7N9F

**Comment by BradyAJohnston** [comment]
Ah I see what you mean. This is currently a result of how the coordinates and symmetry operations are stored inside of the actual structure files themselves. I have plans to improve the node (and this behaviour) but that likely won't happen for a couple of weeks / months. 

In the mean time you can use a transform node after the biological assembly and manually move the pore to the world origin. It should then behave as you expect after that. 
![image](https://user-images.githubusercontent.com/36021261/191903202-06610195-38fa-4d3a-becb-2a11ebb256dc.png)
