### ISSUE TITLE
Chain ids not read correctly

### ISSUE THREAD

**Issue by ErikMarklund** [BradyAJohnston/MolecularNodes#73]
I am trying to colour a dimeric protein based on chain id, but the chain ids in the pdb seem to get mangled during the import. Or maybe I am misunderstanding something. My setup is pretty simple (see image below). I take the chain_number and connect it to a Map Range node, mapping 1-2 to 0-1 (tried different ranges), which is then passed to a ColorRamp node. The colour from the ramp is passed to all elements of a MOL_style_colour node, which in turn connects to the geometry output. However, the resulting colouring seems more or less random, albeit anticorrelated between the two chains (see image). The chain labels for the two monomers in the pdb file are C and D. Pymol seems to handle this fine (third image), so I don't think the pdb file is broken.

Is this a bug? I will try and see if I can spot something in the source code and update if I find something suspicious.
![Screenshot 2022-09-27 at 12 48 40](https://user-images.githubusercontent.com/2421249/192509656-d55f9d5a-b98f-4b1a-9f5b-2217596801e3.png)
![Screenshot 2022-09-27 at 12 48 46](https://user-images.githubusercontent.com/2421249/192509674-54e57f07-f112-4206-b1fc-57567c6a5f0a.png)
<img width="354" alt="Screenshot 2022-09-27 at 13 00 48" src="https://user-images.githubusercontent.com/2421249/192509689-e41885c4-27dc-469d-b9ec-b18373775712.png">

**Comment by BradyAJohnston** [comment]
Hmmm from first glance it looks like it should be working. Are you able to provide a PDB if or file I cam test with? I've had trouble with Atomium (which powers the PDB parsing) messing up some chain ids sometimes, so you could see if just Atomium via python can parse it OK. 

Any custom AA or other out of the ordinary aspects to the file?

**Comment by ErikMarklund** [comment]
Hi again,

I checked the source code and could not find anything obviously wrong with how the chain labels are handled.

Still, the spreadsheet in blender shows that the chain_numbers are scrambled.

![Screenshot 2022-09-27 at 13 38 48](https://user-images.githubusercontent.com/2421249/192515723-a260e315-733c-4f68-8d8e-0838d87e7c52.png)

**Comment by ErikMarklund** [comment]
Yes. How can I send it to you? Can't drag&drop pdb files here it seems.

**Comment by ErikMarklund** [comment]
I will try atomium only too. Have never used it thought so we shall see what I get out of it.

**Comment by ErikMarklund** [comment]
Atomium assigns the chain ids correctly. Although atomium does not assign chain ids to atoms explicitly. A simple test script, which uses a similar logic to molecular nodes, gives the right chain ids:

```
#!/usr/bin/env python

import atomium as atm

pdb_path='MS2_sym-C_C.pdb'

struct = atm.open(pdb_path)

model = struct.models[0]
mols = model.molecules()
for mol in mols:
    currid = mol.id
 
    for res in mol.residues():
        for atom in res.atoms():
            print(f'{atom.name:6s}{res.name:6s}{res.id.split(".")[1]:5s}{currid:5s}')
```

**Comment by ErikMarklund** [comment]
> Hi again,
> 
> I checked the source code and could not find anything obviously wrong with how the chain labels are handled.
> 
> Still, the spreadsheet in blender shows that the chain_numbers are scrambled.
> 
> ![Screenshot 2022-09-27 at 13 38 48](https://user-images.githubusercontent.com/2421249/192515723-a260e315-733c-4f68-8d8e-0838d87e7c52.png)

At a closer look this seems correct. The atoms come in pairs, since the dimer is symmetric and the atom ids are the same in both chains. The chain_number is 1 and 0 for the two equivalent atoms in each case (I think).

**Comment by ErikMarklund** [comment]
Ok I solved it for my protein. The chains in my pdb file had atom ids that both started from the same number. I changed the atom ids in my pdb file so that they formed a contiguous range 1..965,966...1930. Now blender gets it (see image). I also used a slightly simpler node tree (lower image), but that doesn't matter.

Not sure if this is a bug or not, because I cannot find anything conclusive about whether the pdb format requires unique atom ids or not. But for structures with >99999 atoms this will be a problem because the atom id field is only 5 characters.

I am a bit surprised why the atom id from the pdb file should matter when Molecular Nodes or blender tries to retrieve info about an atom, but if it does I can see how non-unique ids would cause this problem.

<img width="273" alt="Screenshot 2022-09-27 at 23 22 44" src="https://user-images.githubusercontent.com/2421249/192639024-f2e6563b-b76f-43f9-a041-91fcd0d59ed6.png">
<img width="939" alt="Screenshot 2022-09-27 at 23 22 53" src="https://user-images.githubusercontent.com/2421249/192639036-59e69dc7-848f-4bcc-8578-979e402c2cea.png">

**Comment by BradyAJohnston** [comment]
Ah thanks for investigating! I see what is happening. I use the atom IDs to ensure the ordering is correct when creating the models for molecular nodes, which is why strange things are happening with the attributes.

Frustratingly Atomium doesn't currently allow ordered access to the atoms that they appear in the file, it is instead an unordered set which I then have to reorder based on their atom IDs. 

Another way to get around the issue would be reading the structure via MDAnalysis using the Molecualr Dynamnics tab, rising the `.pdb` for both the topology and the trajectory file. MDAnalysis does a nicer job of parsing the files, but doesn't give access to some other information like biological assemblies, and is harder to install, which is why I currently have a balance of the two.

**Comment by ErikMarklund** [comment]
Mm. The pdb format is deprecated for a reason...

Would it be possible to use both chain label and atom IDs for ordering?

**Comment by BradyAJohnston** [comment]
Should be able to! Will look into it when I am back from travelling in a couple of weeks.

**Comment by mruetter** [comment]
Hi all, I had exactly the same problem and may have found the reason. The first chain in my PDB was missing the terminus row. Pymol and Chimera handled it, but Atomium did not.
So I just inserted it manually and it worked. Maybe it helps you.

**Comment by BradyAJohnston** [comment]
Are you able to try with the new MolecularNodes 2.0 and see if this issue is resolved?
