### ISSUE TITLE
MDTrajectory　error

### ISSUE THREAD

**Issue by nyu777** [BradyAJohnston/MolecularNodes#74]
I want to select and import Topology and Trajectory files in MDTrajectory, but I get an error.

I have tried RE check of MDAnalysis and reinstalling MDAnalysis and Python 3.10, but it is not cured.

I am using addons 0.13for3.3x and Blender 3.3LTS.

All other functions are normal.
![tjre](https://user-images.githubusercontent.com/114099714/192703257-8dc8a44d-d34d-46c6-a5e0-e34b9591efbd.png)
![hgh](https://user-images.githubusercontent.com/114099714/192703284-bef6aea9-91b1-4d26-adb3-aa8854a3e8b1.png)

**Comment by BradyAJohnston** [comment]
Can you try using non-relative paths and seeing if that fixes the issue? (Shown in #64)

Looking at the error, it seems like your files might not be extracted from the .tar file properly, you could also try re-extracting them to a different folder and try that.

**Comment by nyu777** [comment]
Thank you. I will try it.

**Comment by BradyAJohnston** [comment]
@nyu777 did you have any success?

**Comment by nyu777** [comment]
Sorry. I've been busy with other work and my reply was delayed. I tried another folder but got the same error.

**Comment by BradyAJohnston** [comment]
Have you tried using absolute paths? As stated in #64 . It seems to be a path issue. Maybe try copying and pasting the file path directly instead of opening from Blender.

**Comment by nyu777** [comment]
I'll try it
