### ISSUE TITLE
small chemical compounds atoms problem

### ISSUE THREAD

**Issue by wanjiangbo1985** [BradyAJohnston/MolecularNodes#75]
hello, when i render my model, some problem appear.
1. i use chimera to generate small molecue dymamics file (.pdb)
2. render lost atom -br  see 2d structure reference：https://pubchem.ncbi.nlm.nih.gov/compound/66789061
3. model file and render results plz see  [https://github.com/wanjiangbo1985/mdynamics]

thank u for your great work

wanjiangbo

**Comment by BradyAJohnston** [comment]
The second link is broken for me, is the repo public?

**Comment by wanjiangbo1985** [comment]
try it again, https://github.com/wanjiangbo1985/mdynamics

**Comment by BradyAJohnston** [comment]
Okay looking at the file, the Bromine is currently the issue. While the atom is being imported and the bonds are being calculated, inside of Molecular Nodes I haven't yet defined the details for the EEVEE atoms for the higher atomic number atoms. If you untick the "EEVEE ATOMS" for the 'Ball n Stick' node, then it should show up inside of the Cycles render engine. 

This is a bug though that I will have to remedy, but won't be able to get to for a couple of weeks at least, am currently travelling.

![Uploading image.png…]()

**Comment by wanjiangbo1985** [comment]
yeah,  i use eevee as my render, wich is  faster  than cycles, have a good journey, thank u again.

**Comment by wanjiangbo1985** [comment]
any progress?

**Comment by BradyAJohnston** [comment]
This should now be fixed in the development version of MN. You will require Blender 3.4+ (currently in beta, due to be released in a couple of days). 

You can download the addon from the main branch of the GitHub repo, and install the downloaded .zip file. The interface and nodes has been changed, but should be similar. I've tested in the file your posted and it seems to now work fine.

**Comment by BradyAJohnston** [comment]
Apologies! That issue should now additionally be fixed if you re-download and reinstall from the main branch.

**Comment by wanjiangbo1985** [comment]
[image: image.png]
new version is work, but those function seems disappear, are they going to
update in the future?
default importing-style setting is cool.

millions of thanks

recently , i am trying to import 250 chemicals in blender(each blender file
25 chemicals), i have to set importing-style 250 times. OMG

thank u Johnston, from my bottom of my heart!


Brady Johnston ***@***.***> 于2022年12月10日周六 21:09写道：

**Comment by BradyAJohnston** [comment]
> new version is work, but those function seems disappear, are they going to update in the future?

I am unsure what you mean by this statement. Can you clarify? 

> recently , i am trying to import 250 chemicals in blender(each blender file 25 chemicals), i have to set importing-style 250 times. OMG

You can also use Molecular Nodes in your own python scripts inside of Blender. I will likely change and improve the python API in the future and I haven't created any documentation for it yet, but will do so soon. 

```python
import MolecularNodes as mn
mn.load.molecule_local('file_path_here.pdb', 'SomeMoleculeName', starting_style = 2)
```

That should import the pdb from the path with the ball-and-stick style. You can then (in theory, I haven't tested it extensively) include this in a loop for each of the structures.

**Comment by wanjiangbo1985** [comment]
![image](https://user-images.githubusercontent.com/114630117/207014731-793db362-9c45-4da7-a0ab-b852e27e7f7b.png)
find bond value could't set/maybe in somewhere but i can't find it
some time,there is some problem,when two atom too close,i have to set find bond value to solve it.
"find bond value" existed in old version namd"bond find scale"

old version img
![image](https://user-images.githubusercontent.com/114630117/207015935-08f89254-922e-411e-aa2b-30354508bd59.png)

thanks for u help

**Comment by wanjiangbo1985** [comment]
<img width="222" alt="image" src="https://user-images.githubusercontent.com/114630117/207017285-706e0d5b-4ba3-4e5d-a77c-d888088a6943.png">

**Comment by BradyAJohnston** [comment]
Ah yes whoops! If you press `Tab` into the node group, towards the start you will find a `MOL_bonds_find` node which you can adjust or connect to the input node to expose that option to the node group. I forgot to connect that, and will add it for the next minor bug fix as well. I will do some tests with scaling the bond find radius to try and get it just right.
![image](https://user-images.githubusercontent.com/36021261/207022239-277b1fab-193f-4112-9484-fe735e4c457c.png)

**Comment by wanjiangbo1985** [comment]
thank u, it is really helpful

**Comment by wanjiangbo1985** [comment]
it seems that, when i change this value, it is going to change all my objects' scale radius, rather than only selected object

**Comment by BradyAJohnston** [comment]
If you connect it to the input node, then when you change it on one object it should only be on that object
