### ISSUE TITLE
exporting glb file into powerpoint cannot open; animating translation of subunits does not apply to all

### ISSUE THREAD

**Issue by dvillarreal4868** [BradyAJohnston/MolecularNodes#76]
First off this is incredible you did an example of a virus, I am referring to your "Constructing a Virus | Molecular Nodes | Blender for Biochemists | Geometry Nodes" tutorial.

Two follow-up questions. First, my virus (HBV; PDB: 6vzp) doesn't have a transform feature but does have a translate feature. However, when I tried doing a similar animation (except with translation) only one of the asymmetrical units moved at the very end. How do I have it such that all the units move?

Second, I am trying to export a .glb file and import this file into PowerPoint. However, when I do, PowerPoint has a picture message "The picture can't be displayed". Not sure what I could be doing wrong.

**Comment by BradyAJohnston** [comment]
I changed the node to now use both rotation and translation separately, instead of just the one transform scale. Try the animation by controlling both the rotation and transform together and see if that works.

**Comment by BradyAJohnston** [comment]
re: your second question as well, I don't really have experience with exporting to powerpoint etc, so I don't really know what the issues could be. You could try applying the Geometry Nodes modifier and then exporting, but otherwise I wouldn't know.
