### ISSUE TITLE
AA_sequence_number not passed on with MOL_style_ribbon

### ISSUE THREAD

**Issue by ErikMarklund** [BradyAJohnston/MolecularNodes#77]
I am struggling to get the AA_sequence_number attribute to work with MOL_style_ribbon. This is problematic if I want to use the sequence ID for something other than colouring, for example, the emission strength of the material.

I have made an example below, which I tweak to show the behaviour with different node wiring. It is a dimer with chain_number 1 and 2, and each monomer has 129 aa, which are properly numbered in the pdb file. I try to store AA_sequence_number after mapping to the range 0–1 in a named property 'bzz'.

Using the chain_number instead of AA_sequence_number works fine. The chains get different colour by passing bzz through a color_ramp in the material node tree.
<img width="1728" alt="Screenshot 2022-10-06 at 13 39 51" src="https://user-images.githubusercontent.com/2421249/194305542-a54587d9-fb1b-4ef1-9bf1-a281eddb769c.png">

Mapping and storing AA_sequence_number doesn't work however.
<img width="1728" alt="Screenshot 2022-10-06 at 13 40 09" src="https://user-images.githubusercontent.com/2421249/194305779-b2e377ab-6b57-4aef-bf33-98f62840fe9d.png">

I know that AA_sequence_number is correct before the MOL_style_ribbon. I can for example use it to set the colour of C atoms and use the Color attribute for colouring the material. Note however that this doesn't solve the general problem, because I might want to use the attribute for something else, in addition to some clever colouring based on other features.
<img width="1728" alt="Screenshot 2022-10-06 at 13 40 20" src="https://user-images.githubusercontent.com/2421249/194306190-43781f78-985b-4285-a856-80ebf9db9f9f.png">

I can also access chain_number directly from the materials node tree, but AA_sequence_number is a dead end.
<img width="1728" alt="Screenshot 2022-10-06 at 13 42 04" src="https://user-images.githubusercontent.com/2421249/194306440-6b53b852-42fb-4fdb-91ab-a7f909e08c60.png">
<img width="1728" alt="Screenshot 2022-10-06 at 13 42 25" src="https://user-images.githubusercontent.com/2421249/194306477-51aa1bdb-cc8a-4855-b286-2d5227734b39.png">

I have inspected the geometry in the spreadsheet editor via a viewer node, and indeed the points are rich with attributes before the MOL_style_ribbon node, but the geometry that comes out have lost most of the attributes. I don't see a good reason why chain_number can be passed on to the ribbons but not AA_sequence_number.

**Comment by ErikMarklund** [comment]
Version 0.13.0 and blender 3.3.0. And I guess the correct term is 'shader nodes', not 'material nodes'

**Comment by ErikMarklund** [comment]
Ok I think I came up with a fix. I made some changes inside the MOL_style_ribbon node, using transfer_attribute and store_named_attribute. Everything else is like the last image in the original post, i.e., grabbing the AA_sequence_number attribute in the shader node tree.
<img width="1728" alt="Screenshot 2022-10-06 at 14 41 28" src="https://user-images.githubusercontent.com/2421249/194315625-62f90638-c524-467b-901d-eee3fc11a6e9.png">

Here is a toy example where I make use Color for colour, and AA_sequence_number to make the ribbon go from matte to mirror-y

<img width="1728" alt="Screenshot 2022-10-06 at 14 50 14" src="https://user-images.githubusercontent.com/2421249/194317449-2c2e7c99-4a36-401b-a4fe-49bae844302f.png">

**Comment by BradyAJohnston** [comment]
Thanks for figuring it out! I originally limited the number of attributes that were passed on to the mesh from the points, trying to limit the amount of data that is being passed along unnecessarily. 

This is a good example though that having access to that data would be a good idea, so I'll likely include a check box or something similar to optionally include the data from the original atoms into the mesh that is generated through the ribbon / surface nodes. 

Should be able to do this next week!

P.S. I'm liking the aesthetics in those examples :)

**Comment by ErikMarklund** [comment]
Thanks! If I can achieve what I want it might become really nice. There is something very aesthetic with the shape and symmetry of this dimer. I've managed to implement a patchwork of hacks to make a UV map for it, which unfortunately creates new problems for me to solve...

**Comment by BradyAJohnston** [comment]
Ooh I'll be sure to implement, to enable a UV map for the ribbon style. Thanks for working it!

**Comment by BradyAJohnston** [comment]
This is now fully implemented, including the UV coordinates, inside of [MolecularNodes 2.1](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.1.0)
