### ISSUE TITLE
MacOS: Wrong directory of installation of atomium ?

### ISSUE THREAD

**Issue by tubiana** [BradyAJohnston/MolecularNodes#8]
Hi Brady :-)

Thank again for this wonderfull addon =D
I was trying to set it up on my MacBook Pro, and It didn't work because blender didn't find atomium (despite the installation ended up well).
After some investigation I saw that all tools were install in my Home directory `~/.local/lib/python3.10/site-packages` instead of the blender directory (`/Applications/Blender.app/Contents/Resources/3.1/python/lib/python3.10/site-packages`)

Quick and dirty fix : 
`mv ~/.local/lib/python3.10/site-packages/* Applications/Blender.app/Contents/Resources/3.1/python/lib/python3.10/site-packages/`

Now it works, but I just wanted to reported it if anyone have the same issue at some point :-)

**Comment by BradyAJohnston** [comment]
Thanks for reporting this! I appreciate it. I believe this is the same issue as in #4 , which should be addressed in the [0.3.8 release](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/atomium-fix-2).

Please do let me know if you have any other problem!

**Comment by tubiana** [comment]
Great thank you =D 

I will test this tomorrow morning (Paris time XD) and I will close the issue if it's fixed :)

**Comment by tubiana** [comment]
https://github.com/BradyAJohnston/MolecularNodes/releases/tag/atomium-fix-2 works perfectly thank you =D
