### ISSUE TITLE
Color by ChainID with specific color schemes

### ISSUE THREAD

**Issue by heejongkim** [BradyAJohnston/MolecularNodes#81]
Hi Brady,

Thanks for developing such an awesome node for the scientific community.
I'm just getting taste of the depth of Blender and your node while watching your tutorials to reproduce.
I found most of functionalities and logical flows are very intuitive and I believe I can learn ton more by just simply connecting nodes here and there.

Unfortunately, I'm having a bit of difficulty with coloring ribbon/surface/atom by chain ID manually rather than by random value node.
For example, in ChimeraX, I would simply do "color /D #hexColor target c" for cartoon coloring with a specific color on a specific chain but I can't figure out how i can do the equivalent thing in this context.

Can you please give me some hints if possible?

Thank you so much.

best,
heejong

**Comment by BradyAJohnston** [comment]
This video should cover more information on how to combine selections to get what you are after: https://youtu.be/ruzrQ6uKvDQ

Try combining the collections and using the `MOL_colour_manual` node under `Styling` -> `Color Manual`. 

If you are still having trouble I can post some screenshots. Improving the manual selection of colours is on my to do list :)

**Comment by heejongkim** [comment]
Awesome.
thank you so much. I will get back to you once i give it a shot.

**Comment by heejongkim** [comment]
![Screen Shot 2022-10-21 at 1 35 31 AM](https://user-images.githubusercontent.com/10135880/197120468-a81f05a0-1d5a-4d27-9423-88fc58ee5a31.png)
I got into an interesting thing.
Besides all the chains, I'm also getting those Chain(AA). When I couple this with coloring and click them, I see no color changes while the actual chains get the color change.

Is it a bug or it's due to an issue from PDB?

Thank you.

**Comment by BradyAJohnston** [comment]
I don't quite understand what you mean. Are you able to provide more screenshots to explain what is happening, and what you expect to be happening?

**Comment by heejongkim** [comment]
Oh. Sorry. My bad.

So, I have a PDB with single letter chains from A thru V but somehow I see extra ChainALA, ChainARG, ChainASN, etc.
When I click those unexpected chains with manual coloring, I do not see anything gets colored but i see things get colored with single letter chains.

**Comment by BradyAJohnston** [comment]
Have you tried using the `MOL_selection_AA_name` node. The AA name node should be available under the `Selections` category. See if using the actual AA names works. 

Certainly seems like something strange is happening when parsing the structure. How are you importing it? Is it a public ally available PBD?

**Comment by heejongkim** [comment]
I tested with MOL_selection_AA_name with manual color and it seems it's working.

I imported my own model which is not available from the public repository unfortunately.
So, possibly PDB error? Do you have any recommendation to validate the PDB integrity?
I tested with pdbfixer and it got worse unfortunately.

Thank you.

**Comment by BradyAJohnston** [comment]
I am running into more and more issues with certain PDBs when they are parsed by Atomium which runs the backend for the open PDB ID and open local file. If you could try opening and inspecting the model inside of Atomium in your own python installation, that'll tell you if it's an Atomium issue or not. You could also follow the steps to install the Molecular Dynamics / MDAnalysis components, then you can try importing the `.pdb` file as both the topology and trajectory file (it will be a trajectory with only 1 frame). This might solve the issue. If it does, then it's definitely an Atomium issue. If it doesn't, then it might be a PDB formatting issue.

**Comment by heejongkim** [comment]
I quickly tested with atomium and I think I'm getting somewhere.

```
import atomium
pdb = atomium.open("file")
```

```
pdb.model.chains()
```
and i see only chains but not weird ChainResidue thingy.

```
pdb.models[0].chains()
```
Same

and now

```
pdb.models[0].molecules()
```
this throws not only chains but also ligands.
I believe you use this to iterate thru to get chain info.
https://github.com/BradyAJohnston/MolecularNodes/blob/ba21ae38e399d0d7306e5395006f4beb82ac62d0/src/import_structure.py#L426

So, maybe changing this with chains method would resolve the issue?
I'm not sure why you used molecules instead of chains so I'm just throwing an immature idea.

Thanks.

**Comment by BradyAJohnston** [comment]
Internally I use `pdb.model.molecules()` because it gives the ligands and chains, which I use both for the chain selection node for Molecular Nodes. Currently I use chains & ligands in the same field for selection, but this could potentially be split into different fields. I do this to capture the different ligands, but also to ensure that nucleic acids etc are treated as a separate chain. The issue can arise when atomium interprets some of the amino acids as individual ligands, which should not be the case.

Open to suggestions about how to change this behaviour though, if you can think of a better way to handle it.

**Comment by BradyAJohnston** [comment]
Ooh thank you so much for tracking this down! I haven't looked into it much, but this might be the issue that is causing trouble for a lot of people. I'll ask some others to see if that solves the issue.

**Comment by heejongkim** [comment]
Happy to contribute.

It's no joke. I just tested with another PDB with missing terminal TER which gave me a choppy import.
As soon as I put that last line, everything beautifully showed up.

Cheers!

**Comment by BradyAJohnston** [comment]
Ah that's good to know. Should be able to implement something to catch that issue on import.
