### ISSUE TITLE
electrostatic potential calculation and coloring

### ISSUE THREAD

**Issue by heejongkim** [BradyAJohnston/MolecularNodes#82]
Hi Brady,

Do you have a node that can handle electrostatic potential calculation from PDB?
After searching for awhile, I encountered BioBlender had functionality of it and a similar topic in the issue #52.
I'm afraid I might've missed this info from somewhere already available but I thought that at least putting this issue may help other people find it useful in the future if it's already out there.

Thank you.

**Comment by BradyAJohnston** [comment]
I haven't implemented the electrostatic potential inside of Molecular Nodes yet. Once implemented, the values that are described in #52 will be available for colouring etc. In terms of implementing nodes that would calculate fields like those that are present in BioBlender - I don't think I have the expertise for such a task but I'll be meeting with the BioBlender team in Italy later this week actually and will likely discuss how it might be done.

**Comment by heejongkim** [comment]
That would be fantastic. 
Thanks for letting me/us know what's coming in the near future.

**Comment by heejongkim** [comment]
Hi brady,

I just want to revisit if this one is getting implemented in the new version.
I looked through the nodes but i couldn't find it.
Am I missing or is it in to-do list?

Thank you for your fantastic work and generosity of sharing such awesome tool.

best,
heejong

**Comment by BradyAJohnston** [comment]
I haven't revisited this yet. 

In terms of calculating electrostatics, then that is currently beyond the scope of Molecular Nodes, but certainly still possible in the future for better interactions with other python packages.

If however you have a lookup table or dictionary of values that you would like to be added to the atoms based ato name etc, then that is very easy to implement, and I would just need the dictionary itself and it can be added quickly. 

It's not something that I have looked into, but if you collect some more info for what you would like I can probably put a PR together.
