### ISSUE TITLE
coloring DNA in Molecular Nodes

### ISSUE THREAD

**Issue by Clement-Rouillon** [BradyAJohnston/MolecularNodes#83]
Hello Brady 

I am having some problems coloring the DNA in molecular nodes, it remains gray even though the colors of the bases are defined. Any idea what might be wrong? 
Thanks

**Comment by BradyAJohnston** [comment]
Hi mate, it is likely an issue with the materials. If you first import a PDB structure, Molecular Nodes will auto-create a material and use it when you then create the DNA structure. Currently it doesn't automatically create the material if you just create the DNA structure. This is a bug and I'll be fixing it when I get a chance in a few weeks :) 

The fix should be importing a protein structure, and then creating the DNA - let me know how you go!

**Comment by Clement-Rouillon** [comment]
Awesome, thanks for taking the time to answer :)

**Comment by Clement-Rouillon** [comment]
Hey Brady! 
Sorry to bother you with more questions... I now noticed that when I do SHIFT + A, I don't find molecular nodes anymore. I tried to reinstall everything, but I cannot find it. Have you ever experienced that before, or do you know how to fix it? 

NB: Saw the video of your talk in Amsterdam, was awesome, congrats ;)
