### ISSUE TITLE
How set different materials on two different objects ? 

### ISSUE THREAD

**Issue by Thoor42** [BradyAJohnston/MolecularNodes#86]
Hi Brady,

First of all, thanks for your work, the add-on is very nice.

I just have a little problem. In the same node Tree, i tried to set two material of two elements : a membrane and two molecules. My aim is to see the molecules in membrane during the MD (simulation). When one material is set, the material appear but when i set two, the default material (grey) appear.

I also tried to duplicate the MD and set one material for the molecule (so i select the molecule AA range) and i set the other material for the second element, the membrane (i select the membrane AA range) and it works but it's way too heavy and Blender often crash.

Do you have another way to do what i want ?

![Capture d’écran 2022-10-31 à 10 07 12](https://user-images.githubusercontent.com/116819238/198971896-bf859ae2-f868-4a32-8e9d-e72a794a9704.png)

PS : When i duplicate the MD and selected the membrane using AA-range selection (3-5000), i still found the first selection (1-2 AA range selection) from the first MD loaded. So i have the two molecules displayed twice.

**Comment by BradyAJohnston** [comment]
Hi mate, have a look at this video and see if it helps you achieve what you are https://youtu.be/dqdwS-TvsnM

**Comment by InSiliRemi** [comment]
Thanks a lot, that's works

**Comment by wjm41** [comment]
Just following up on this - is there absolutely no way to set two different materials/colors on selections of a point cloud? Even if I duplicate the point cloud "geometry" object twice and join them afterwards?

**Comment by BradyAJohnston** [comment]
Similarly @wjm41 if you want to set different colours you can store the colour as an attribute. In MolecularNodes I use the `Color` attribute. This can then be accessed on a point-by point basis inside of the shader. You can use the `Set Color` node that I provide, or manually store and retrieve the attribute yourself as such: 

![image](https://user-images.githubusercontent.com/36021261/234046662-2289f313-1544-4f61-b506-6676df969c27.png)

![image](https://user-images.githubusercontent.com/36021261/234046704-0a52fb5e-329d-45b0-917f-61ac4523b747.png)

![image](https://user-images.githubusercontent.com/36021261/234046734-671b3dd6-c9b5-4930-8e3a-d78d5c9f8b40.png)
