### ISSUE TITLE
DNA conformation right handed 

### ISSUE THREAD

**Issue by Clement-Rouillon** [BradyAJohnston/MolecularNodes#87]
Hey Brady, 

I had a question about the DNA in molecular nodes: My DNA seems to be right-handed, do you know if there is an easy way to fix that and put it back to left-handed? 

Thanks a lot 
Clément

**Comment by BradyAJohnston** [comment]
DNA is supposed to be right-handed. You can change some internals of it to have it be left-handed, but I'm unsure why you would want to do so. It would likely break the alignment of some of the bases as well to reverse the handedness. You can make your own DNA here: https://youtu.be/m7bTEABoAzo in which you will be able to change the handedness hopefully quite easily.
