### ISSUE TITLE
selection chain with insert keyframs

### ISSUE THREAD

**Issue by heejongkim** [BradyAJohnston/MolecularNodes#89]
Hi Brady,

After watching your videos, I got one question for this video: https://www.youtube.com/watch?v=dqdwS-TvsnM&t=237s&ab_channel=BradyJohnston

What if you would like to change those selections dynamically over timeline (by inserting keyframes)?
For example, you have Chain A, B, C.
you start with A with surface, B with ribbon, and C with ribbon with different material.
And you want to change that styles into A with metallic, B with transparent (alpha), and C with atom with another material in later timeline.

It seems like Molecular Node (all green tag) can't insert keyframe while blue tag like selection math can insert keyframe.
I feel like I need to be a bit more clever with those "math" nodes to juggle around to make that happen.
However, I've been trying out here and there but so far no luck unfortunately.

If you have any suggestions or hints, I would really appreciate it.
Thank you.

**Comment by BradyAJohnston** [comment]
Hi mate, I can help out more when I am back from travelling in a week or so. To begin with, try using a geometry `Switch` node. 
<img width="771" alt="image" src="https://user-images.githubusercontent.com/36021261/200768890-a93dabc0-6d58-402f-a3c0-98be8b83d935.png">

You can then keyframe the boolean for the switch, to change between one representation and the other. You can also use a `Compare` and `Scene Time` node to change the input based on frame number.

**Comment by heejongkim** [comment]
Oh Cool.
Thank you for the hints.
Let me get on it and get back to you soon.
