### ISSUE TITLE
MDAnalysis Spike protein import error

### ISSUE THREAD

**Issue by lizhenan1993** [BradyAJohnston/MolecularNodes#91]
Hi Brady, 

I followed the instrction in this website (https://bradyajohnston.github.io/MolecularNodes/examples.html), but I couldnt import the spike protein. 

Thanks
![MDAnalysis](https://user-images.githubusercontent.com/62802115/201500460-f411ef6a-2e12-450a-996e-dab86f717ea5.png)

**Comment by BradyAJohnston** [comment]
Do you know what version of MDAnalysis you installed? I have gotten a couple of reports that with the latest version something is breaking with the `2.3.0` version can potentially be fixed by manually installing `2.2.0`: 
```bash
pip install MDAnalysis==2.2.0
```

**Comment by lizhenan1993** [comment]
Hi Brady,

I reinstall the MDAnalysis to 2.2.0 and it works now, Thanks!

**Comment by BradyAJohnston** [comment]
Okay I'm glad this is working! I haven't looked into what is actually behind the issue yet but I will do so at some point.
