### ISSUE TITLE
how to set modified molecular nodes as default nodes?

### ISSUE THREAD

**Issue by wanjiangbo1985** [BradyAJohnston/MolecularNodes#93]
<img width="587" alt="屏幕截图 2022-11-15 181828" src="https://user-images.githubusercontent.com/114630117/201895660-193a646e-884d-4cdd-8cbe-51f7dd2067e4.png">
hello  johnston,
i'd like to  add  nodes "MOL_style_ball_n_stick" on molecular nodes as my default style, so that when i import a molecue, the default style is "ball and stick", rather than none, is that possible to solve this problem? (my default render is eevee)

Thx
jacob wan

**Comment by BradyAJohnston** [comment]
Currently there isn't a way to set a default representation on import, but it's a good idea and I'll add it to the list of features for the next version!

**Comment by BradyAJohnston** [comment]
There is now an option to set a default style when importing via Molecular Nodes, which is available in the [`2.0`](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.0.1) release. If you could give it a try and report back, that would be great!
