### ISSUE TITLE
is:issue is:open Coloring DNA bases bleads color into backbone and vice versa when using DNA_style_atoms!

### ISSUE THREAD

**Issue by viltakus** [BradyAJohnston/MolecularNodes#97]
Whenever I try to create a DNA strand with custom colors, I cannot get a ball model of DNA with appropriate coloring with Eevee. It only works with Cycles and DNA_style_atoms node. With Eevee I try using DNA_style_atoms_Eevee node and everything seems to work fine but the coloring patterns in the dsDNA get messed up, where the colors from bases bleed into the backbone and vice versa... If you could help me figure this out, I would appreciate it greatly!
P.S. I'll attach two screenshots indicating the problem. Maybe you'll spot something that I'm not seeing.
P.P.S. Your work with these nodes is just incredible! I cannot thank you enough!

**Comment by viltakus** [comment]
![Screenshot 2022-11-27 014225](https://user-images.githubusercontent.com/106834779/204115558-cbc8433e-084d-486a-b868-bb88130eb99d.jpg)
![Screenshot 2022-11-27 014035](https://user-images.githubusercontent.com/106834779/204115559-576d250d-f72a-4c96-835e-16b2c2fc4557.jpg)

**Comment by BradyAJohnston** [comment]
Thanks for reporting the issue! I think it'll be an issue with how the EEVEE atoms currently works (which is pretty dodgy). This will be _greatly_ improved, with some vital components making it easier only becoming available in Blender 3.4 (which should release in a few days / a week).

I've been going through a complete re-write of Molecular Nodes that will hopefully coincide with that release, so the issue should hopefully be fixed when that is released. Will keep you posted!

**Comment by viltakus** [comment]
That's great to hear! 
Although, will you incorporate these functions with a future update of MolecularNodes or is it already up? Because if you look in the corner of my screenshots, I was already using Blender 3.4, albeit an unstable version still.
Thanks!!!

**Comment by BradyAJohnston** [comment]
The changes are in the main branch, but I haven't made any official releases of it yet so you will have been using the older 0.13

**Comment by BradyAJohnston** [comment]
DNA is now reimplemented in the [`2.0`](https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v2.0.1) release of Molecular Nodes, please do give it a try and report back!
